### ISSUE TITLE
[callback] Callback server throw out error when callback function called too fast

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1026]
### Description

When I use IR Induction sensor on a101, I find that gpio.onchange function is called too fast and callback server throw out error.
 

### Test Code

Test code:
```
console.log("Test case for callback server");

var pins = require("arduino101_pins");
var gpio = require("gpio");

var pinA = gpio.open({
    pin: pins.IO2,
    direction: "in",
    edge: "any"
});

pinA.onchange = function(event) {
    console.log("Senser read value: ", pinA.read());
};

```
 

### Steps to Reproduction

1. Connect sensor to a101.
2. Code test case for reading sensor value.
3. Callback server throw out error.
 

### Actual Result

![selection_002](https://cloud.githubusercontent.com/assets/22387607/25111737/59ebc8a2-241f-11e7-9c56-98d6eb2a0da0.jpg)
![selection_001](https://cloud.githubusercontent.com/assets/22387607/25111747/729a3fe6-241f-11e7-9405-5a33baabe08d.jpg)

 

### Expected Result

Work well and no error.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 47e8aef | Arduino 101 | April 18, 2017 | Fail

**Comment by grgustaf** [comment]
I believe the test is invalid. Printing text is a [very slow operation](https://github.com/01org/zephyr.js/wiki/Performance-Experiments), so you're using like 60k clock cycles in your onchange function just for the printing.

If you change your test to instead do something fast like just reading the pin value and recording it in an array, your function will run about 10x faster and I doubt you'll see this problem.

Can you tell us what sensor you're using?

**Comment by cuiyanx** [comment]
@grgustaf As I guess and thanks to know. So, be closed. And this is an [IR Induction sensor](https://item.taobao.com/item.htm?spm=a1z10.5-c-s.w4002-15635545148.10.3Y02u0&id=15584417726).
