### ISSUE TITLE
[ashell] ashell hangs when execute command 'error'

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1027]
### Description

ashell hangs when execute command 'error'

### Test Code

[ashell.md](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md)
 
### Steps to Reproduction

1. `make ashell`
2. `make dfu`
3. `acm> error `

### Actual Result

ashell hangs

### Expected Result

Prints an error using JerryScript
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 0b11671 | Arduino 101 | Apr 18, 2017 | Fail
 
![selection_032](https://cloud.githubusercontent.com/assets/19813546/25117432/b85b8f2e-2444-11e7-9e74-b168dde8d23c.png)

**Comment by brianjjones** [comment]
This one also expects you pass it a string.  For example 'error Test!'.  @grgustaf  This seems like a useless function, shall I just remove it?

**Comment by qiaojingx** [comment]
Verified with commit 212747a.  Command 'error' was removed from ashell.
