### ISSUE TITLE
[ashell] callback server not stop while callback function wrote off after execute 'stop'

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1029]
### Description

callback server not stop while callback function wrote off after execute 'stop'

### Test Code

[ashell.md](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md)
 
### Steps to Reproduction

1. `make ashell`
2. `make dfu`
3. `acm> load test.js` and Enter
4. `RAW> /*Paste code of BMI160Accelerometer.js */`and CTRL+Z to finish transfer
5. `acm> run test.js`
6. `acm> stop`

### Actual Result

callback server not stop while callback function wrote off after execute 'stop'
![selection_034](https://cloud.githubusercontent.com/assets/19813546/25117993/e946e3a2-2446-11e7-94fb-c0aa6154e3fd.png)

### Expected Result

Sample stops running completely.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 0b11671 | Arduino 101 | Apr 18, 2017 | Fail

**Comment by grgustaf** [comment]
FYI we've now disabled sensor code from ashell by default, but you can reenable it manually in fragments/zjs.conf.dev

**Comment by brianjjones** [comment]
Currently I was not checking where in the cycle the main loop was when stopping ashell.  This means its possible for ashell to clear everything out while mainloop is trying to call a callback, causing the issue you see. Certainly a bug, working on a fix.

**Comment by qiaojingx** [comment]
Verified with commit 6a27658. This issue is not reproducible.
