### ISSUE TITLE
[ashell] ihex transfer fails from IDE with ashell in single thread change #1047

### ISSUE THREAD

**Issue by brianjjones** [01org/zephyr.js#1063]
It appears https://github.com/01org/zephyr.js/pull/1047 broke the ihex transfer code for the IDE.  If you click 'run' now, it will fail to copy the file to the filesystem. 

Likely need to add a condition for when code transfer is occurring that ashell maintains control of the thread, until the transfer is complete.

**Comment by brianjjones** [comment]
This has been fixed by #1074 and can be closed

**Comment by qiaojingx** [comment]
Verified with commit 78bc531. This issue is not reproduced.
