### ISSUE TITLE
[fs] Error seeking to position

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1100]
### Description

Throw out error seeking to position on [/tests/test-fs.js](https://github.com/01org/zephyr.js/blob/master/tests/test-fs.js).
 

### Test Code

[/tests/test-fs.js](https://github.com/01org/zephyr.js/blob/master/tests/test-fs.js)

 

### Steps to Reproduction

Run test-fs.js and check logs.
 

### Actual Result

![selection_001](https://cloud.githubusercontent.com/assets/22387607/25689052/cf1b2a34-30b6-11e7-8f41-8dc1aad5f9c5.jpg)

 

### Expected Result

Work well
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 78bc531 | Arduino 101 | May 4, 2017 | Fail

**Comment by qiaojingx** [comment]
Verified with commit 011f0fe + patch #1126. This issue is not reproducible.
Will close this issue after patch merged.

**Comment by cuiyanx** [comment]
Fixed and closed
