### ISSUE TITLE
net does not handle socket close events as it should

### ISSUE THREAD

**Issue by jprestwo** [01org/zephyr.js#1102]
As mentioned in #1093, the TCP read callback has several cases with the buffer and its elements being valid, null, zero etc. These different cases are handled incorrectly in net, specifically when a socket is closed. We need to figure out what all the possible cases are and handle them correctly.

**Comment by qiaojingx** [comment]
Verified with commit af7eadd. This issue is fixed.
socket can be closed.
![selection_124](https://user-images.githubusercontent.com/19813546/28357177-25ed0194-6c9d-11e7-96f5-517fa8450903.png)
Also fixed #1175.

**Comment by grgustaf** [comment]
Closing based on QA verification.
