### ISSUE TITLE
[ocf] Can not find resource on OCF client

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1115]
### Description

OCFClient can not find resource, it will be hanging.
 

### Test Code

Add console.log on [/samples/OcfClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClient.js):
    Add `console.log("----1----");` on line 44;
    Add `console.log("----2----");` on line 50;

Like this:
```
console.log("----1----");
client.findResources({ resourceType:"core.light" }, onfound).then(function(resource) {
    console.log("findResources() was successful, deviceId=" + resource.deviceId);
}).catch(function(error) {
    console.log("findResources() returned an error: " + error.name);
});
console.log("----2----");
```

Result:
![selection_001](https://cloud.githubusercontent.com/assets/22387607/25834967/e7ad2b2e-34ad-11e7-96fa-380679d3f08d.jpg)

 

### Steps to Reproduction

Run test case and check console logs.
 

### Actual Result

Can not find resource and will be hanging.
 

### Expected Result

Find resource and work well.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 3950beb | Arduino 101 | May 9, 2017 | Fail

**Comment by qiaojingx** [comment]
Verified with commit 011f0fe + patch #1125 . This issue is not reproducible.
Will close this issue after patch merged.

**Comment by cuiyanx** [comment]
Fixed and closed
