### ISSUE TITLE
[callbacks] test-callbacks stuck at the last result on K64f

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1116]
### Description

test-callbacks stuck at the last result on K64f
 
### Test Code

[test-callbacks.js](https://github.com/01org/zephyr.js/blob/master/tests/test-callbacks.js);
 
### Steps to Reproduction

1.  `make BOARD=frdm_k64f JS=tests/test-callbacks.js`
2.  cp outdir/frdm_k64f/zephyr.bin /media/<USERNAME>/MBED/

### Actual Result

test-callbacks stuck at the last result on K64f
![selection_064](https://cloud.githubusercontent.com/assets/19813546/25836674/56c4749c-34bb-11e7-919c-94f3571928f6.png)

### Expected Result

No issue occurs.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 3950beb| FRDM-K64F | May 8, 2017 | Fail

**Comment by jprestwo** [comment]
@cuiyanx, the K64 seems to have a weird thing where after you flash it it will run the script but then restart quickly. Sometimes it finishes the script, sometimes it doesn't. The most reliable way I have found to test on the K64 is by flashing, then resetting the board. When I do this I see it get to the `TOTAL: 41 of 41 passed` line every time.

**Comment by qiaojingx** [comment]
Verified with commit 011f0fe. This issue is not reproducible. Closed
Platform: FRDM-K64f.
