### ISSUE TITLE
[ws] new WebSocket() failed in NodeWebSocketClient.js

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1121]
### Description

new WebSocket() failed in NodeWebSocketClient.js
 
### Test Code

[NodeWebSocketClient.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/NodeWebSocketClient.js);
 
Add console.log to test code as below:
![selection_073](https://cloud.githubusercontent.com/assets/19813546/25844780/282a055c-34de-11e7-8e21-eabd77fd58ca.png)

### Steps to Reproduction

1.  `make JS=samples/websockets/NodeWebSocketClient.js`
2.  `make dfu`
### Actual Result

new WebSocket() failed in NodeWebSocketClient.js
On QEMU:
![selection_075](https://cloud.githubusercontent.com/assets/19813546/25844616/97858954-34dd-11e7-9304-78e5a59e3cbd.png)
On Arduino 101:
![selection_074](https://cloud.githubusercontent.com/assets/19813546/25844617/9792cb32-34dd-11e7-97e6-8102b06f4855.png)

### Expected Result

No issue occurs.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 3950beb| Arduino 101 | May 9, 2017 | Fail
master | 3950beb| QEMU | May 9, 2017 | Fail
 
### Additional Information

Websocket on K64f is blocked by #1098

**Comment by jprestwo** [comment]
I probably should have been more clear via a comment, but `NodeWebSocketClient.js` is a Node.js script, not meant for ZJS. There is currently no web socket client support in ZJS.

**Comment by qiaojingx** [comment]
Thanks for explanation. [NodeWebSocketClient.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/NodeWebSocketClient.js) works by command `node NodeWebSocketClient.js`
So Closed.
