### ISSUE TITLE
Can't boot BMI160Temperature.js

### ISSUE THREAD

**Issue by ttzeng** [01org/zephyr.js#1138]
The BMI160Temperature.js script no longer works after upgrading to the new API based off Zoltan's iot-js-api. No message shown in the serial output after reset.

**Comment by jimmy-huang** [comment]
I just tested it with master, it's working fine, I believe you didn't do a make update, because we just updated Zephyr.  So try make pristine; make update and build again.

**Comment by ttzeng** [comment]
You are probably right, @jimmy-huang , it works. Sorry for the false alarm.
