### ISSUE TITLE
[net] Only first string can be received by TCPEchoServ6.js on QEMU

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1151]
### Description

[reg][net] Only first string can be received by TCPEchoServ6.js on QEMU

### Test Code

[TCPEchoServ6.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ6.js); 

### Steps to Reproduction

1. `make BOARD=qemu_x86 qemu JS=samples/TCPEchoServ6.js`
2. `nc -6 2001:db8::1 4242` to connect with TCPEchoServ6.js
3. Send string

### Actual Result

Only first string can be received. 
![selection_005](https://cloud.githubusercontent.com/assets/19813546/26051664/65919494-3995-11e7-87a5-8ed9baa93b58.png)

### Expected Result

String can be received continuously.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | bd07595 | QEMU | May 15, 2017 | Pass
master | e5f62c0 - e24821c| QEMU | May 15, 2017 | Fail

### Additional Information

This issue is probably caused by commit e5f62c0.

**Comment by grgustaf** [comment]
Fixed by PR #1231.

**Comment by qiaojingx** [comment]
Verified with commit 819a41a + #1231. This issue is not reproducible.
Will close it after patch merged.

**Comment by grgustaf** [comment]
Qemu was further broken by #1104 but that is fixed by #1247.

**Comment by qiaojingx** [comment]
Verified with commit 78c9749. This issue has been fixed.
