### ISSUE TITLE
[ashell] Require module not allow using single quotes

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1165]
### Description

Require module using single quotes will occur error when running ashell 
 
### Test Code

[ashell](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md); [Button.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/digital/Button.js)
 
### Steps to Reproduction

1. `make ashell ROM=256`
2. `make dfu`
3. `acm> load test.js` and Enter
4. `RAW> /*Paste code of Button.js*/`and CTRL+Z to finish transfer
5. `acm> run test.js`

### Actual Result

[ERR] require("...") string is too long
![selection_008](https://cloud.githubusercontent.com/assets/19813546/26099950/ebeb458e-3a5e-11e7-9f27-2136758346f0.png)
![selection_007](https://cloud.githubusercontent.com/assets/19813546/26099949/ebe12950-3a5e-11e7-8fac-7b8c341ddc23.png)

 ### Expected Result

Sample runs successfully.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | e24821c | Arduino 101 | May 16, 2017 | Fail
 
### Additional Information

If modify [Button.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/digital/Button.js) as below; this issue will disappear.
Change `var gpio = require('gpio');` to `var gpio = require("gpio");`

**Comment by haoxli** [comment]
Verified with commit 82ef9f8 . This issue is not reproducible.

**Comment by qiaojingx** [comment]
Closed since not reproduced.
