### ISSUE TITLE
[net] Can not run server.address() function that will throw out error

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1173]
### Description

I test server.address() function after server listening. This function can not run and will throw out error.
 

### Test Code

**Simple test:**

```
var IPv6Address = "2001:db8::1";
var IPv6Port = 9876;
var IPv6Family = 6;
var ServerAddressInfo;

server.listen({port: IPv6Port, host: IPv6Address, family: IPv6Family}, function() {
    console.log("----1----");
    ServerAddressInfo = server.address();
    console.log("----2----");

    console.log("TCP server listen: " + IPv6Address + ":" + IPv6Port);
});
```

 

### Actual Result

![selection_002](https://cloud.githubusercontent.com/assets/22387607/26184788/71cfdbf0-3bb9-11e7-9c0f-ab307d5c1bcc.jpg)

 

### Expected Result

Get server address information.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 8a5bafc| Arduino 101 | May 18, 2017 | Fail

**Comment by grgustaf** [comment]
The test code is incomplete; server is not defined there. Are you testing on qemu or what?

**Comment by grgustaf** [comment]
I tried to piece it together from other samples and I reproduced the problem in qemu, but in more recent code base it says "Error: Expected a function." which is nicer.

Looking into it, this function is listed in the docs but is not actually implemented currently.

**Comment by grgustaf** [comment]
Fixed by PR #1231.

**Comment by cuiyanx** [comment]
@grgustaf I can get server address information, but server address is wrong.

**Comment by cuiyanx** [comment]
Created new issue #1353, so closed
