### ISSUE TITLE
[net] Server.getConnections function will be hang when there is socket connection

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1174]
### Test Code

Add simple test into [/samples/TCPEchoServ6.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ6.js):
```
server.on("connection", function(sock) {
    console.log("----1----");
    server.getConnections(function(count, error) {
        console.log("count:", count);
        console.log("There is one socket connection, I am running");
    });
    console.log("----2----");
});
```

 

### Steps to Reproduction

1. Add simple test into `/samples/TCPEchoServ6.js`
2. Flash into a101
3. Connect to client
4. Check console logs
 

### Actual Result

![selection_003](https://cloud.githubusercontent.com/assets/22387607/26185397/4f416c62-3bbd-11e7-9bc0-fd3bd646ad66.jpg)

 

### Expected Result

Work well.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 8a5bafc | Arduino 101 | May 18, 2017 | Fail

**Comment by grgustaf** [comment]
Fixed by #1231.

**Comment by cuiyanx** [comment]
@grgustaf I can get connections, but this connections count always is '0'.

**Comment by cuiyanx** [comment]
fixed and closed
