### ISSUE TITLE
Missing module not displayed in the error message

### ISSUE THREAD

**Issue by gvancuts** [01org/zephyr.js#1191]
If the JavaScript app requires a module that is missing, the console displays an error message stating so but does not display what module is missing.

Steps to reproduce this:
1. Run a ZJS image that does *not* include support for `iotivity-constrained`
2. Load [this JavaScript sample](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/led.js) via the Web IDE
3. Run it and the following message will appear on the console:
```
acm> In function require():
NotSupportedError: module not found: ''
```
I would expect the last line to actually display:
```
NotSupportedError: module not found: 'ocf'
```

**Comment by grgustaf** [comment]
Hmm, I attempted to fix a very similar problem right before the hackathon; maybe my fix was incomplete or I broke something else at the same time. :)

**Comment by qiaojingx** [comment]
Verified with commit 78c9749. This issue is not reproducible.
Close this one.
