### ISSUE TITLE
[ocf] Can not find multiple resources by ocf client

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1197]
### Description

The ocf client can not find multiple resources, it just find the last one.
 

### Test Code

Sample as server:
[/samples/OcfMultiSensor.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfMultiSensor.js)

Simple test as client:
```
var ocf = require('ocf');
var client = ocf.client;

ocf.start();

client.findResources({ resourceType:"core.light" }).then(function(resource) {
    console.log("findResources 'core.light' was successful, deviceId=" + resource.deviceId);

    client.retrieve(resource.deviceId, {observable: false}).then(function(res) {
        console.log("light: " + resource.properties.light);
    }, function(error) {
    });
}, function(error) {
    console.log("findResources() returned an error: " + error.name);
});

setTimeout(function() {
    client.findResources({ resourceType:"core.temp" }).then(function(resource) {
        console.log("findResources 'core.temp' was successful, deviceId=" + resource.deviceId);

        client.retrieve(resource.deviceId, {observable: false}).then(function(res) {
            console.log("temp: " + resource.properties.temp);
        }, function(error) {
        });
    }, function(error) {
        console.log("findResources() returned an error: " + error.name);
    });
}, 3000);
```

 

### Steps to Reproduction

1. Build [/samples/OcfMultiSensor.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfMultiSensor.js) on a101
2. Connect with BLE
3. Build and run simple test on linux
4. Check console log
 

### Actual Result

The ocf client just finds the last resource.

**Client:**

![selection_005](https://cloud.githubusercontent.com/assets/22387607/26393550/c0c83e86-409c-11e7-9bf7-5b42ceda4d41.jpg)

**Server:**

![selection_006](https://cloud.githubusercontent.com/assets/22387607/26393787/82a69ae8-409d-11e7-9a08-9187259821c7.jpg)

 

### Expected Result

Can find multiple resources.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 82ef9f89c  | Arduino 101 | May 24, 2017 | Fail

**Comment by jimmy-huang** [comment]
Can you reproduce this still?  I tried the sample, and there's a slight error, i updated to res.properties.light and res.properties.temp, and I am able to see both resources.

jimmy@jimmy-dev:~/projects/zephyrjs/zephyr.js (fix-ocf-find-resources *)$ outdir/linux/release/jslinux simpletest.js --noexit

call oc_do_ip_discovery
discovery
findResources 'core.light' was successful, deviceId=c7567a09-1557-4a09-6357-7a09b1577a09
light: 4095
call oc_do_ip_discovery
discovery
findResources 'core.temp' was successful, deviceId=c7567a09-1557-4a09-6357-7a09b1577a09
temp: 4095

**Comment by wanghongjuan** [comment]
Hi, @jimmy-huang I just tried this sample use commit de91ade, it works.

BTW, API describe function [`findResources(ClientOptions options, optional FoundListener listener);`](https://github.com/01org/zephyr.js/blob/master/docs/ocf.md#clientfindresources): `Find remote resources matching options filter`, so I changed the `OcfMultiSensor.js` and `simpletest.js`, updated all resourceTypes to `resourceTypes:[core.res]`, but only got the latest register temp resource, light is undefined.

**Comment by cuiyanx** [comment]
fixed and closed

**Comment by jimmy-huang** [comment]
@cuiyanx you can file another bug the the options parameter and we'll track it there.
