### ISSUE TITLE
[sensor] Sensor stops abnormally 

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1213]
### Description

When sensor stops, error will be triggered.

### Test Code

[SensorBLEDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/SensorBLEDemo.js); [test-bmi160accelerometer.js](https://github.com/01org/zephyr.js/blob/master/tests/test-bmi160accelerometer.js); [test-bmi160gyroscope.js](https://github.com/01org/zephyr.js/blob/master/tests/test-bmi160gyroscope.js); [test-bmi160temperature.js](https://github.com/01org/zephyr.js/blob/master/tests/test-bmi160temperature.js).
 
### Steps to Reproduction

1.  `make JS=samples/SensorBLEDemo.js ROM=256`
2.  `make dfu`
3.  Connect with nRF app via BLE.
4. Disconnect
### Actual Result

Sensor.stop cause error occurs.
![selection_028](https://cloud.githubusercontent.com/assets/19813546/26820959/4b6e5374-4ad7-11e7-9a7f-18096a06dd16.png)
 
### Expected Result

Sensor stops without error.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | fee4637 | Arduino 101 | Jun 6, 2017 | Fail

**Comment by uhofemei** [comment]
I see a similar issue based on PR https://github.com/01org/SmartHome-Demo/pull/150 being that the BLE connection goes down within <= 3 minutes after being established from the command line using the instructions here: https://github.com/01org/zephyr.js/blob/master/docs/6lowpan-ble.md.

**Comment by qiaojingx** [comment]
Verified with commit 8d1b343 + #1221. This issue is not reproducible.
Will close after patch merged.

**Comment by qiaojingx** [comment]
Verified with commit 78c9749. This issue is not reproducible.
