### ISSUE TITLE
[ble] First subscription was unsuccessful with WebBluetooth

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1215]
### Description

First subscription was unsuccessful with WebBluetooth(https://goo.gl/QEvyDZ).

### Test Code

[WebBluetoothGroveLcdDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/WebBluetoothGroveLcdDemo.js); 
 
### Steps to Reproduction

1.  `make JS=samples/WebBluetoothGroveLcdDemo.js ROM=256`
2.  `make dfu`
3.  Connect to https://goo.gl/QEvyDZ via BLE.

### Actual Result

JS callback timed out error occurs when first connect.
![selection_030](https://cloud.githubusercontent.com/assets/19813546/26822068/58c5bf9a-4adb-11e7-8ee5-678d951c485b.png)
 
![screenshot_20170607-110909](https://user-images.githubusercontent.com/19813546/26859463-728ea8bc-4b6a-11e7-9799-723b222140d8.png)

### Expected Result

No error occurs.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | fee4637 | Arduino 101 | Jun 6, 2017 | Fail
 
### Additional Information

Test environment for WebBluetooth(https://goo.gl/QEvyDZ):
Android version: 6.0.1
Hardware： Nexus 5
Chrome version: 58.0.3029.83

**Comment by grgustaf** [comment]
I think this is an occasional problem, not 100% reproducible, right?

**Comment by qiaojingx** [comment]
This problem only reproduced when first connect after A101 reset. It won't occur when second, third connect.
Verified with commit fee4637 + #1224. This issue is fixed. Will closed after patch merged.

**Comment by qiaojingx** [comment]
Verified with commit 78c9749. This issue is not reproducible.
Close this one.
