### ISSUE TITLE
[ashell] No error thrown when require a not existing module in ashell

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1226]
### Description

Error is not thrown when require a module which not stored in board.
### Test Code

[ashell.md](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md).
 
### Steps to Reproduction

1. `make ide`
2. `make dfu`
3. connect A101 with https://01org.github.io/zephyrjs-ide/#/editor
4. Run code `var temp = require('Temp.js');` (make sure Temp.js is not stored in board)
 
### Actual Result

No error thrown.
![selection_032](https://user-images.githubusercontent.com/19813546/26957519-27f1133c-4cf8-11e7-849c-88c2c934b37f.png)
 
### Expected Result

Module not found error should be thrown. 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | fee4637 | Arduino 101 | Jun 9, 2017 | Fail
 
### Additional Information

If require a stored module which is not standards compliant, it will thrown `NotSupportedError: module not found 'xxx'` . This error message will confuse user.
![selection_033](https://user-images.githubusercontent.com/19813546/26958014-ff339750-4cfa-11e7-8e65-eec33a6e76c8.png)

**Comment by brianjjones** [comment]
Shouldn't be too hard to add.

**Comment by brianjjones** [comment]
Sorry for the slow reply, got caught up in other fixes.  This should take care of it. https://github.com/01org/zephyr.js/pull/1330

**Comment by qiaojingx** [comment]
Verified with commit af7eadd. This issue is not reproduced.
