### ISSUE TITLE
Zephyr SDK 0.9.1 does not work

### ISSUE THREAD

**Issue by poussa** [01org/zephyr.js#1229]
Using Zephyr SDK 0.9.1 produces unbootable image. Nothing on console. Tried with make ide ROM=256 and make JS=samples/HelloWorld.js

**Comment by uhofemei** [comment]
I just used SDK 0.9.1 to build Smart Home PR #150 and I was able to boot.

**Comment by jimmy-huang** [comment]
@poussa see comment on #1204, anything with AIO is broken due to the Zephyr if you upgrade to 9.1, one way to get around this is adding debug to arc image, so adding CONFIG_DEBUG=y to arc/fragments/prj.conf.base

**Comment by uhofemei** [comment]
This is not set for the PR 01org/SmartHome-Demo#150 I mentioned above and it still works.

**Comment by grgustaf** [comment]
As with the 0.9.0 foibles, we'll just stick with recommending 0.9.0 until there's a decent resolution to this in Zephyr.

**Comment by qiaojingx** [comment]
AIO related samples are broken due to the Zephyr issue(https://jira.zephyrproject.org/browse/ZEP-2363) after commit 0334065(zephyr update to 1.8 and zephyrSDK update to 0.9.1). This issue blocks ashell and ide testing.
Platform: Arduino 101
Commit: 05fda87

**Comment by qiaojingx** [comment]
Verified with commit 1ff882b + #1355 . This issue is not reproducible.
