### ISSUE TITLE
convert.sh loses newlines

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#124]
If an input JS file has a newline, convert.sh drops it; the result is that if there is a comment, the rest of the file will end up looking like it's commented out.

This could be fixed, but we might be better off going to my Python-based implementation from scripts/jsrunner. So we would pull the conversion routine out of there into a convert.py that replaces convert.sh, review it and make sure it covers at least everything that convert.sh does now.

This should be more cross-platform than bash scripts, and easier for any schmoe like me to read and understand - hence more maintainable. Another thought is we may need to deal with Unicode JS input at some point, and Python would be better suited to that.

**Comment by poussa** [comment]
This is fixed.
