### ISSUE TITLE
[pme] The number of committed neurons in the network can be got as '0'

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1244]
### Description

`PME.getCommittedCount` in [/docs/pme.md](https://github.com/01org/zephyr.js/blob/master/docs/pme.md):
```

PME.getCommittedCount

unsigned short getCommittedCount();

Gets the number of committed neurons in the network.
Returns the number of comitted neurons in the network (a value between 1-128).
```
 But, I can get The number of committed neurons in the network as '0'

### Test Code

Simple test:
```
var pme = require("pme");
console.log("Committed Count: " + pme.getCommittedCount());
```

 

### Actual Result

```
ipm_console0: 'Sensor core running ZJS ARC support image'
Committed Count: 0
```

### Expected Result

Update pme.md doc.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 819a41a | Arduino 101 | June 14, 2017 | Fail

**Comment by jimmy-huang** [comment]
I think this is a typo, should be 0-128, I'll update the API docs

**Comment by cuiyanx** [comment]
Fixed and closed
