### ISSUE TITLE
[pme] Can not change neuron context value

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1245]
### Description

I can set neuron context value and no error threw out, but I always get neuron context value as '127'.
 

### Test Code

Simple test:

```
var pme = require("pme");

pme.setNeuronContext(1);
console.log("neuron context: " + pme.getNeuronContext());
pme.setNeuronContext(10);
console.log("neuron context: " + pme.getNeuronContext());
pme.setNeuronContext(100);
console.log("neuron context: " + pme.getNeuronContext());
```
 

### Actual Result

```
ipm_console0: 'Sensor core running ZJS ARC support image'
neuron context: 127
neuron context: 127
neuron context: 127
```

### Expected Result

 Can be changed.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 819a41a | Arduino 101 | June 14, 2017 | Fail

**Comment by jimmy-huang** [comment]
I think this is actually an internal API that's used for restoring context, as it only works in save/restore modes, so obviously it's not going to work if you call it directly.   I think we should actually drop the set/get neuron context api, as the regular app just calls saveNeurons() and restoreNeurons(), they don't just set/get the neuron context.

**Comment by cuiyanx** [comment]
@jimmy-huang OK, wait for PME doc updated. I will close this issus and remove the test point.

**Comment by cuiyanx** [comment]
Remove the test point and closed
