### ISSUE TITLE
[pme] There are some error about function parameter description

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1249]
### Description

Parameter definition as `number ` in [/docs/pme.md](https://github.com/01org/zephyr.js/blob/master/docs/pme.md):
```
    learn(number[] pattern, unsigned long category);
    unsigned long classify(number[] pattern);
```

Parameter definition as `char ` in [/docs/pme.md](https://github.com/01org/zephyr.js/blob/master/docs/pme.md):
```
 PME.learn

void learn(unsigned char[] pattern, unsigned long category);

Takes a pattern and commits it to the network as training data for a given category.
The pattern is an array of bytes, up to 128 bytes in length. The category indicates to the PME which category this training vector belongs to, that is, if a future input has a sufficiently similar pattern, it will be classified as the same category passed with this pattern.

PME.classify

unsigned long classify(unsigned char[] pattern);

Takes a pattern and uses the committed neurons in the network to classify the pattern.
The pattern is an array of bytes, up to 128 bytes in length.
Returns PME.NO_MATCH if the input data did not match any of the trained categories. Otherwise, the trained category assigned by the network will be returned.
```

### Expected Result

 Definitions and descriptions are consistent

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 819a41a | Arduino 101 | June 15, 2017 | Fail

**Comment by qiaojingx** [comment]
Verified with commit 418c871. This issue has been fixed. Parameter definition are `number` in both [Web IDL ](https://github.com/01org/zephyr.js/blob/master/docs/pme.md#web-idl)and [API Documentation ](https://github.com/01org/zephyr.js/blob/master/docs/pme.md#api-documentation)sections.

**Comment by cuiyanx** [comment]
fixed and closed
