### ISSUE TITLE
native module 'ble' and 'ws' are not found

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1256]
### Description

This is an regression issue. Require native module "ble" or "ws" got `NotSupportedError: module not found: ''` error.

### Test Code

[BLE.js](https://github.com/01org/zephyr.js/blob/master/samples/BLE.js); [WebSocketServer.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer.js) 
### Steps to Reproduction

1. make JS=samples/BLE.js ROM=256
2. make dfu
3. Reset 
### Actual Result

got `NotSupportedError: module not found: ''` error.
![selection_040](https://user-images.githubusercontent.com/19813546/27221525-74325d6e-52bb-11e7-998a-54c0e565c1ca.png)
 
### Expected Result

BLE or websocket server started.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 44a5e6b | Arduino 101 | Jun 16, 2017 | Fail
master | a09bd64 | Arduino 101 | Jun 16, 2017 | Pass

**Comment by grgustaf** [comment]
The empty module string is fixed by #1258; that's a step toward finding the real problem here.

**Comment by qiaojingx** [comment]
Verified with commit 78c9749. The empty module string has been fixed. Native modules 'ble' and 'ws' still can't be found.
Platform: Arduino 101
![selection_041](https://user-images.githubusercontent.com/19813546/27267540-c8b4c850-54db-11e7-8924-28cf808076a0.png)
![selection_042](https://user-images.githubusercontent.com/19813546/27267541-c8c6d766-54db-11e7-9abc-8f8721cf4d16.png)

**Comment by grgustaf** [comment]
The fix is now merged, should work in 73a36db.

**Comment by qiaojingx** [comment]
Verified with commit 15d3847. This issue is fixed. 'ble' and 'ws' module can be found. But another issue is found for websocket. new issue is here #1291 .
Close this one.
