### ISSUE TITLE
SPI API

### ISSUE THREAD

**Issue by poussa** [01org/zephyr.js#1263]

**Comment by qiaojingx** [comment]
Basic feature of SPI is ready on Arduino 101 and FRDM-K64F. Verified with samples([SPI.js](https://github.com/01org/zephyr.js/blob/master/samples/SPI.js)). One known issue is on FRDM-K64F(#1326).
Commit: c2ca034
Platform: Arduino 101 and FRDM-K64F.

**Comment by grgustaf** [comment]
Added by @brianjjones

**Comment by qiaojingx** [comment]
Basic feature of SPI is ready on Arduino 101 and FRDM-K64F. Verified with samples([SPI.js](https://github.com/01org/zephyr.js/blob/master/samples/SPI.js)). 1 known issue(#1326) is on FRDM-K64F, which is possibly a zephyr issue(tracking by https://jira.zephyrproject.org/browse/ZEP-2353).
Commit ID: 0334065
Platform: Arduino 101 and FRDM-K64F.
ZephyrSDK: 0.9.1
Zephyr:1.8
