### ISSUE TITLE
Web Socket API

### ISSUE THREAD

**Issue by poussa** [01org/zephyr.js#1266]
Subset of WS API : https://html.spec.whatwg.org/multipage/web-sockets.html

**Comment by grgustaf** [comment]
Added by @jprestwo

**Comment by qiaojingx** [comment]
Basic feature is ready on FRDM-K64F. But there is still a block issue(#1348) on Arduino101. Verified with samples([WebSocketServer.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer.js), [WebSocketServer4.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer4.js)) and tests([test-ws-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws-server.js)). 2 other issues are found : #1234, #1369.
Commit ID: de91ade + #1374 
Platform: Arduino 101 and FRDM-K64F.
ZephyrSDK: 0.9.1
Zephyr:1.8

**Comment by qiaojingx** [comment]
Basic feature is ready on Arduino101 and FRDM-K64F. Verified with samples([WebSocketServer.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer.js), [WebSocketServer4.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer4.js)) and tests([test-ws-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws-server.js)). 4 issues are found : #1234, #1369, #1385, #1386. 
Commit ID: 5c65f11
Platform: Arduino 101 and FRDM-K64F.
ZephyrSDK: 0.9.1
Zephyr:1.8
