### ISSUE TITLE
[uart] Uart functions are broken

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1279]
### Description

I test those function:
```
void write(Buffer data)
void setReadRange(number min, number max)
function onread(Buffer data)
```
I always get `Error: Expected a function`. Is this a bug or functions to be completed?

### Test Code

[/samples/UART.js](https://github.com/01org/zephyr.js/blob/master/samples/UART.js)

 

### Actual Result

 Throw out error.

### Expected Result

 Work well.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 78c9749 | Arduino 101 | June 20, 2017 | Fail

**Comment by brianjjones** [comment]
This is fixed by #1310

**Comment by qiaojingx** [comment]
Verified with commit c2ca034, this issue is not reproducible.

**Comment by cuiyanx** [comment]
Fixed and closed
