### ISSUE TITLE
[SPI] "Hello World\0" is identified as invalid ascii

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1280]
### Description

When running [SPI.js](https://github.com/01org/zephyr.js/blob/master/samples/SPI.js); on Arduino 101. "Hello World\0" is identified as invalid ascii

### Test Code

[SPI.js](https://github.com/01org/zephyr.js/blob/master/samples/SPI.js); 

### Steps to Reproduction

1. add console.log to SPI.js as below:
     
![selection_060](https://user-images.githubusercontent.com/19813546/27322689-9cc76d78-55d1-11e7-9816-86dc2fdc5e12.png)

2. `make JS=samples/SPI.js`
3. `make dfu`

### Actual Result

Error `SPI error: buffer has invalid ascii ` is print.
![selection_062](https://user-images.githubusercontent.com/19813546/27322709-b46d20d0-55d1-11e7-8c2a-154a73e6994d.png)

 ### Expected Result

Running SPI sample successfully.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 78c9749 | Arduino 101 | Jun 20, 2017 | Fail

### Additional Information

When running [SPI.js](https://github.com/01org/zephyr.js/blob/master/samples/SPI.js); on K64F. The below error is print.
![selection_046](https://user-images.githubusercontent.com/19813546/27320439-d9a1cb8e-55c8-11e7-9949-3f28e5708cd3.png)
Is that SPI module supported on K64F, too?

**Comment by grgustaf** [comment]
Brian things you didn't have the MOSI and MISO lines connected with a wire. That makes the "read" come in as all 1's, which triggers that message when we try to convert to ASCII.

Really, we can't be guaranteed that we'll get ASCII back from a SPI read so makes more sense to fix this by printing the buffer in hex.

This does point out an interesting fact about JS strings - they can contain NULL bytes, which is useful for specifying buffers like this as strings in a compact form. So e.g. the size of the "Hello World\0" string above is (I think) 12 bytes, containing a 0 at the end.

**Comment by qiaojingx** [comment]
@brianjjones, this issue has been fixed on Arduino101, but still failed on K64F. Does it support on k64f, or only for Arduino101?
Result:
Arduino101:
![selection_075](https://user-images.githubusercontent.com/19813546/27567068-fd04932e-5b1b-11e7-9156-42599c77375c.png)
K64F:
![selection_076](https://user-images.githubusercontent.com/19813546/27567072-017b06cc-5b1c-11e7-9094-d1340f7b4fa1.png)
Commit ID: 8a95b21

**Comment by brianjjones** [comment]
Currently its only tested for A101.  I'll start looking into K64 this week

**Comment by brianjjones** [comment]
@qiaojingx  I've updated things so that it 'works' on k64f https://github.com/01org/zephyr.js/pull/1323

However, I'm only seeing zero's in the reply buffer.  Currently I'm not sure if it's an issue with Zephyr, the board itself, or the current example's configuration.  I'll keep looking into it and let you know if I find a solution.

**Comment by qiaojingx** [comment]
Verified with commit c2ca034 on both Arduino101 and FRDM-K64F. This issue is not reproducible.
Created a new issue for only seeing zero's in the reply buffer on K64F( #1326 ).
Close this one.
