### ISSUE TITLE
[spi] SPI bus can only read and write array and string

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1294]
### Description

Now, SPI bus can only read and write array and string. I test buffer data as `number` and `boolean`, SPI bus will be hang.
 

### Test Code

Change `"Hello World\0"` to `true` or `1024` in [/samples/SPI.js](https://github.com/01org/zephyr.js/blob/master/samples/SPI.js) on line 10.

 

### Actual Result

Logs: `SPI test starting..`
 

### Expected Result

 Can read and write number or boolean or some buffer data.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 15d3847 | Arduino 101 | June 21, 2017 | Fail

**Comment by brianjjones** [comment]
Currently numbers and bools are not supported.  But I don't see why they couldn't be so I'll look into adding it.

**Comment by grgustaf** [comment]
I really don't think that makes sense. Accepting Buffer, however, makes a lot of sense. :)

**Comment by grgustaf** [comment]
Marking P2, but this is for handling Buffer.

**Comment by brianjjones** [comment]
https://github.com/01org/zephyr.js/pull/1315 will add the ability to pass it a Buffer

**Comment by qiaojingx** [comment]
Verified with commit 3403f93. Buffer object can be passed.

**Comment by cuiyanx** [comment]
fixed and closed
