### ISSUE TITLE
[ocf] Segmentation fault occurs when running ocf client on Linux

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1316]
### Description

When running [OcfSensorClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorClient.js) and [test-ocfclient.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfclient.js) on Linux, `Segmentation fault (core dumped)` error occurs.

### Test Code

[OcfSensorClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorClient.js);
[OcfSensorServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorServer.js);
[test-ocfserver.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfserver.js);
[test-ocfclient.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfclient.js)
 
### Steps to Reproduction

Scenario 1:
1. Build [OcfSensorServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorServer.js) on Arduino101 via BLE.
2. Build [OcfSensorClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorClient.js) on Linux

Scenario 2:
1. Running [test-ocfserver.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfserver.js) in terminal 1 on Linux
2. Running [test-ocfclient.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfclient.js) in terminal 2 on Linux

### Actual Result

Scenario 1 and 2 both got `Segmentation fault (core dumped)` error.
Scenario 1:
Client on Linux:
![selection_077](https://user-images.githubusercontent.com/19813546/27569122-666a455a-5b28-11e7-8c05-8ea4d19cc666.png)
Server on A101:
![selection_079](https://user-images.githubusercontent.com/19813546/27569137-852a1178-5b28-11e7-862c-be9e7c5ac3ac.png)
Scenario 2:
Client on Linux:
![selection_080](https://user-images.githubusercontent.com/19813546/27569218-f9a16cae-5b28-11e7-8641-e814d8dc0608.png)

Server on Linux:
![selection_078](https://user-images.githubusercontent.com/19813546/27569178-ae5488f8-5b28-11e7-9f8d-f1d730bd9c90.png)

### Expected Result

No error occurs.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 8a95b21 | Linux | Jun 27, 2017 | Fail

**Comment by jimmy-huang** [comment]
It's crashing on
client.update(resource).then(function(res) {
}).catch(function(error) {
});

And the callstack is showing it crashing on executing the callback in the job queues for promises.
For now, it appears to segfault only when the function passed into the .then() function has a empty body, so a work-around is to add a single statement like console.log() or ASSERT() in the .then(function(res) {
}).

It might be a upstream JerryScript bug, maybe @jprestwo have some insights on this one?

**Comment by jprestwo** [comment]
A cleaner workaround would be to just not call `.then()` or `.catch()` at all.

```
client.update(resource);
```

**Comment by qiaojingx** [comment]
Verified with 4e44cc6 + #1332 . `Segmentation fault (core dumped)` error is not reproduced when running [test-ocfclient.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfclient.js). But it still occurs when running [OcfSensorClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorClient.js);
![selection_100](https://user-images.githubusercontent.com/19813546/27893860-07520106-623b-11e7-9807-2f397c804e7f.png)

**Comment by qiaojingx** [comment]
Verified with commit 1ff882b + #1332 . `Segmentation fault (core dumped)` error is not reproducible. 
But, "update" events didn't get called on ocf client.
![selection_110](https://user-images.githubusercontent.com/19813546/28155015-4670c4ae-67df-11e7-89a9-61a65061893f.png)

**Comment by jimmy-huang** [comment]
@qiaojingx, @grgustaf and I discussed a little bit on the API, we agree that the update() events should only be called when the resource has changed, so it doesn't make sense for the events to be called each time you call retrieve(), does that make sense?

**Comment by qiaojingx** [comment]
Verified with commit af7eadd. This issue is not reproduced.
