### ISSUE TITLE
[aio] aioPin.read and aioPin.readAsync cost more time than before.

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1329]
### Description

This is a regression issue. aioPin.read and aioPin.readAsync will take more time to finish reading. The efficiency is lower than before

### Test Code

[test-aio.js](https://github.com/01org/zephyr.js/blob/master/tests/test-aio.js);

or simple code:
```
console.log("Wire IO4 to A0!"); 

var aio = require("aio");
var gpio = require("gpio");
var pins = require("arduino101_pins");
var pinA = aio.open({pin: pins.A0});
var pinB = gpio.open({pin: "IO4", mode: 'out'});
var readFlag = 0;

// test AIOPin read

setInterval(function () {
    pinB.write(readFlag);
    console.log("pinB.write:  " + readFlag);
    console.log("pinA.read:  " + pinA.read());
    pinA.readAsync(function (rawValue) {
		console.log("readAsync: " + rawValue);
		console.log("------------------------");
      });

	readFlag = 1 - readFlag;
}, 5000);
```
### Actual Result

Test result for test-aio.js:
![selection_097](https://user-images.githubusercontent.com/19813546/27824566-7878433e-60df-11e7-886c-be820d1f4ee1.png)

Test result for simple code: aioPin.read and aioPin.readAsync can't finish reading in time.
![selection_096](https://user-images.githubusercontent.com/19813546/27824293-8b5b21ca-60de-11e7-95c1-fd944d8e7c79.png)
 
### Expected Result

Test result for test-aio.js:
![selection_098](https://user-images.githubusercontent.com/19813546/27824823-49b63a78-60e0-11e7-8d36-6997786c921f.png)

Test result for simple code: 
![selection_099](https://user-images.githubusercontent.com/19813546/27824968-b175c6e2-60e0-11e7-9182-380cb56fb24b.png)

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 418c871 | Arduino 101 | Jul 4, 2017 | Fail
master | a09bd64 | Arduino 101 | Jul 4, 2017 | Pass
 
### Additional Information

This issue is caused by commit e989092

**Comment by jimmy-huang** [comment]
The issue is that now AIO.read() and readAsync() reads the cached value to speed up the read calls, and doesn't see the updated value until later when it actually changed, we can fix this by reverting the patch, but it will bring back the high latency of ADC reads, so maybe the question for the 0.4 release is which is more important?  Maybe @grgustaf can comment?

**Comment by qiaojingx** [comment]
Verified with commit 7054087 + #1404 . This issue is not reproduced.
I will close it after patch merge.

**Comment by qiaojingx** [comment]
Verified with commit ca7af31 on Arduino101. This issue is not reproduced.
