### ISSUE TITLE
[ashell] acm> cannot print normally

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1368]
### Description

`acm>` cannot print normally. Console log doesn't print as really input/output. It affect the next input.

### Test Code

[ashell](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md).
 
### Steps to Reproduction

1. `make ashell ROM=256`
2. `make dfu`
3.  Then use the following command to connect to the ashell from a terminal:
     `$ screen /dev/ttyACM0 115200`
 
### Actual Result

acm> does not print at the end of console log.
![selection_118](https://user-images.githubusercontent.com/19813546/28263452-65330dec-6b19-11e7-96df-bfcc8ee6a0a2.png)
 
### Expected Result

`acm>` should print as end 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | af7eadd| Arduino 101 | Jul 17, 2017 | Fail
 
### Additional Information

This issue is not reproduced in WebIDE.

**Comment by brianjjones** [comment]
The fix for this can be found here
https://github.com/01org/zephyr.js/pull/1431

**Comment by qiaojingx** [comment]
Verified with commit ca7af31 + #1431. This issue is not reproduced.

**Comment by qiaojingx** [comment]
Verified with commit 528a6f0. This issue is fixed. Close
