### ISSUE TITLE
[net] net.on('up') function is broken

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1371]
### Description

This is a regression issue. Got `Error: Expected a function` error when test with function  
```
net.on("up", function() {
});
```
### Test Code

[TCPClient6.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPClient6.js);
[test-tcp6-client.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp6-client.js)
 
### Steps to Reproduction

1. add console.log to [TCPClient6.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPClient6.js); as below:
![selection_119](https://user-images.githubusercontent.com/19813546/28299608-bcd6c9ec-6bac-11e7-93f4-829c55a802ec.png)
2. `make JS=samples/TCPClient6.js ROM=256`
3. `make dfu`
 
### Actual Result

Got `Error: Expected a function` error 
![selection_120](https://user-images.githubusercontent.com/19813546/28299632-dd32e81a-6bac-11e7-96d2-3db1226550b2.png)

 ### Expected Result

No error thrown. 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | af7eadd | Arduino 101 | Jul 18, 2017 | Fail
master | 05fda87 | Arduino 101 | Jul 11, 2017 | Pass

**Comment by jprestwo** [comment]
The networking up/down events were moved (and renamed to netup/netdown) into the net-config module. These scripts must not have been updated. You will have to add the following code:
```
var net_cfg = require('net-config');
net_cfg.on('netup', function() {
    // rest of code here
}
```

**Comment by qiaojingx** [comment]
@jprestwo ， Ok then，please update [docs/net.md](https://github.com/01org/zephyr.js/blob/master/docs/net.md). I will close this issue after document updated.
