### ISSUE TITLE
[ocf] How to stop a running ocf client

### ISSUE THREAD

**Issue by wanghongjuan** [01org/zephyr.js#1387]
## Description
I want to stop a running ocf client via code instead of `Ctrl + C`

## Test Code
[OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js)
[OcfClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClient.js)

## Steps to reproduce
1. Build [OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js) on A101
2. Connect with BLE
3. Build and run [OcfClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClient.js) on linux, after getting the output, exit the process

## Actual Result
The client file is hang, unless used `Ctrl + C` to exit the process

## Excepted Result
Using code to exit the process, maybe we can use `process.exit()` or add a `client.stop()` method.

**Comment by jimmy-huang** [comment]
+1

**Comment by wanghongjuan** [comment]
Verified the `process.exit` can work well in `OcfClient.js` with commit 1143544.
