### ISSUE TITLE
Key 'JSON' is not in deps list

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1393]
### Description

This is a regression issue. Building [PMESaveRestore.js](https://github.com/01org/zephyr.js/blob/master/samples/PMESaveRestore.js) and [test-pme-save-restore.js](https://github.com/01org/zephyr.js/blob/master/tests/test-pme-save-restore.js) failed for a101.

### Test Code

[PMESaveRestore.js](https://github.com/01org/zephyr.js/blob/master/samples/PMESaveRestore.js);
[test-pme-save-restore.js](https://github.com/01org/zephyr.js/blob/master/tests/test-pme-save-restore.js)
 
### Steps to Reproduction

 1. `make JS=samples/PMESaveRestore.js`

### Actual Result

![selection_128](https://user-images.githubusercontent.com/19813546/28516886-4f82874e-7095-11e7-909e-7199613e535b.png)
 
### Expected Result

 Building succeed.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 5c65f11 | Arduino 101 | Jul 24, 2017 | Fail
master | af7eadd | Arduino 101 | Jul 18, 2017 | Pass

**Comment by jimmy-huang** [comment]
Did something changed recently on analyze?  I think this should be JSON not json as it's checking for the use of JSON object or constructors in JS, usually a call to JSON.parse()?

**Comment by qiaojingx** [comment]
Verified with commit 5726f4e. This issue is fixed.
