### ISSUE TITLE
[net-config] Function netConfig.setStaticIP() is undefined

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1401]
### Description

I test net-config APIs and get an error. The function netConfig.setStaticIP() is undefined.
 

### Test Code

Simple test:
```
console.log("simple test");

var WebSocket = require("ws");
var netConfig = require("net-config");

var IPv6 = "2001:db8::100";
console.log("----mark----");
var IPState = netConfig.setStaticIP(IPv6);
console.log("setStaticIP(IPv6): " + IPState + " expected result 'true'");
```

 

### Steps to Reproduction

1. Run simple test on a101
2. Check console log.
 

### Actual Result

Log:
```
simple test
----mark----
Error: Expected a function.
```

 

### Expected Result

Work well.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 5726f4e | Arduino 101 | July 25, 2017 | Fail

**Comment by jprestwo** [comment]
The 'p' in 'IP'  should be lowercase:

`netConfig.setStaticIp(IPv6);`

**Comment by cuiyanx** [comment]
@jprestwo Well, I think we will update net-config.md

**Comment by cuiyanx** [comment]
fixed and closed
