### ISSUE TITLE
[ocf] Segmentation fault error occurs

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1407]
### Description

This is a regression issue. When running [OcfClientUpdate.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClientUpdate.js) on Linux, `Segmentation fault (core dumped)` error occurs.

`Segmentation fault (core dumped)` error occurred before in OcfSensorClient.js(#1316), it was fixed and didn't reproduce with commit af7eadd in last weekly testing.

### Test Code

[OcfClientUpdate.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClientUpdate.js)
[OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js);
 
### Steps to Reproduction

1. Build [OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js) on Arduino101 via BLE.
2. Build [OcfClientUpdate.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClientUpdate.js) on Linux

### Actual Result

`Segmentation fault (core dumped)` error occurs:
![selection_131](https://user-images.githubusercontent.com/19813546/28606883-dc4f156c-720b-11e7-882a-5c5cfd2a42c0.png)

### Expected Result

No error occurs.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 1143544 | Linux | Jul 26, 2017 | Fail
master | af7eadd | Linux | Jul 18, 2017 | Pass

**Comment by jimmy-huang** [comment]
I can't reproduce this with master e6d1bf82aa4eb7bb12444d5a5f9a4a115ac63c7a

**Comment by qiaojingx** [comment]
Closed since not reproduced with commit e6d1bf8.
