### ISSUE TITLE
[ocf] ocfclient cannot connect to ocfserver after connecting and disconnecting 4-5 times

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1408]
### Description

Try to connect and disconnect ocfclient with ocfserver, after repeating 4-5 times, ocfclient will be no longer able to connect to ocfserver.
 
### Test Code

[OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js);
[OcfSensorServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorServer.js);
[OcfMultiSensor.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfMultiSensor.js);
[OcfClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClient.js);
[OcfClientUpdate.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClientUpdate.js);
[OcfSensorClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorClient.js); 
[OcfDeviceInfo.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfDeviceInfo.js); 
[OcfPlatformInfo.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfPlatformInfo.js); 

### Steps to Reproduction

1. Build OcfServer on Arduino101.
2. Running OcfClient on Linux.
3. CTRL+C to disconnect OcfClient.
4. Repeat step 2 and 3 for 4-5 times(OcfClient can be different client samples).

### Actual Result

After 4-5 times, ocfclient will be no longer able to connect to ocfserver, it stuck at `Started OCF client`:
![selection_132](https://user-images.githubusercontent.com/19813546/28607274-b328e062-720d-11e7-90d7-c8c85004fe68.png)

### Expected Result

OcfClient can always connect to OcfServer successfully.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 1143544 | Arduino 101 | Jul 26, 2017 | Fail
 
### Additional Information

Reset OcfServer can fix this issue, but it will be reproduced again after connecting 4-5 times.

**Comment by wanghongjuan** [comment]
I just tested this with commit e40cd69, after running 10 times `OcfClientUpdate.js`, the client can connect the server, and the registered resource can be found/updated.

**Comment by qiaojingx** [comment]
Closed since not reproduced with commit e40cd69.
