### ISSUE TITLE
[ocf] Fatal fault occurred when running sample with Grove Chainable RGB LED sensor

### ISSUE THREAD

**Issue by wanghongjuan** [01org/zephyr.js#1415]
## Description
I an writing a sample using OCF API with [Grove Chainable RGB LED](http://www.seeedstudio.com/depot/twig-chainable-rgb-led-p-850.html?cPath=156_157) sensor, there is a fatal fault occurred when update the state of the sensor at second time.

## Test Code
**Server**: [rgbled.js](https://github.com/01org/zephyr.js/files/1182678/rgbled.txt)
**Client**: [client.js](https://github.com/01org/zephyr.js/files/1182681/rgbled-client.txt)

## Steps to Reproduce
1. Build rgbled.js on A101.
2. Connect with BLE
3. Build and run client.js on linux, after getting the output, exit the process

## Actual Result
This is the log of master:

![fatal-master](https://user-images.githubusercontent.com/5309217/28713111-60c4d89e-73c0-11e7-8e07-08fb6ed50e9a.png)

I also try to run this sample with commit 8d1b343, get more detail information as below:

![fatal-8d1b343](https://user-images.githubusercontent.com/5309217/28713115-66b7c432-73c0-11e7-9f74-fff293834d45.png)

The client is ok:
![client](https://user-images.githubusercontent.com/5309217/28713598-43a33808-73c2-11e7-8d13-76b3b8d75e66.png)

## Excepted Result
There is no error no matter how many times that update the RGB LED resource's state

**Comment by grgustaf** [comment]
@jimmy-huang feel free to lower priority but first take a look at it.

**Comment by wanghongjuan** [comment]
@jimmy-huang  I still can reproduce this issue. The led seems doesn't light, I updated the client code that only invoke the `updateResource(data['/a/rgbled'], [255,255,255])` one time, all code runs normally, no error, and I checked the led again, the led is fine.

**Comment by jimmy-huang** [comment]
@wanghongjuan, you getting a segfault in client or the server?  For the client, you might wanna try pr #1416 if it helps.

**Comment by wanghongjuan** [comment]
@jimmy-huang I tried the pr and got undefined when invoking the function zjs_create_promise directly in client.js, am i missing something?

**Comment by jimmy-huang** [comment]
@wanghongjuan the #1416 may not be ready, but try #1424

**Comment by wanghongjuan** [comment]
@jimmy-huang #1424 is work, thanks for you support.
