### ISSUE TITLE
[ws] Parameters in websocketconnection.onclose are undefined 

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1422]
### Description

Code and reason in onclose event are as undefined, when websocketconnection.onclose is triggered. Besides, description of onclose event in [Web IDL](https://github.com/01org/zephyr.js/blob/master/docs/web-socket.md#web-idl) and [API Documentation](https://github.com/01org/zephyr.js/blob/master/docs/web-socket.md#api-documentation) are not consistent. One has parameters and the other one doesn't.
[Web IDL](https://github.com/01org/zephyr.js/blob/master/docs/web-socket.md#web-idl):
```
interface WebSocketConnection {
    // WebSocketConnection Events
    onmessage(Buffer data);
    onping(Buffer data);
    onpong(Buffer data);
    onclose(Number code, String reason);

```
[API Documentation](https://github.com/01org/zephyr.js/blob/master/docs/web-socket.md#api-documentation):
```
WebSocketConnection.onclose Event

onclose(void)

The close event is emitted when the web socket has closed.
```

### Test Code

[WebSocketServer.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer.js);
[WebSocketServer4.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer4.js);
[test-ws-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws-server.js);
 
### Steps to Reproduction

1. `make JS=tests/test-ws-server.js ROM=256`
2. `make dfu`
3.  connect via ble and add soft router on linux:
    ` ip -6 route add 2001:db8::/64 dev bt0`
4. run ws client on linux by `node /tests/test-ws-client-node.js` 
5. CTRL+C to disconnect websocket connection.

### Actual Result

code and reason display as undefined.
[test-ws-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws-server.js):
![selection_134](https://user-images.githubusercontent.com/19813546/28867448-bf3584fa-77a8-11e7-97f7-14e49d116b14.png)
[WebSocketServer.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer.js):
![selection_135](https://user-images.githubusercontent.com/19813546/28867470-d1310288-77a8-11e7-8b4d-57405271ff28.png)

### Expected Result

1. Should these two parameters be defined as [Web IDL](https://github.com/01org/zephyr.js/blob/master/docs/web-socket.md#web-idl) said? Or just remove this test point and update onclose event in [Web IDL](https://github.com/01org/zephyr.js/blob/master/docs/web-socket.md#web-idl) as no parameters.

2. Description of onclose event in [Web IDL](https://github.com/01org/zephyr.js/blob/master/docs/web-socket.md#web-idl) and [API Documentation](https://github.com/01org/zephyr.js/blob/master/docs/web-socket.md#api-documentation) should be consistent.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 4d9b084 | Arduino 101 | Aug 2, 2017 | Fail

**Comment by brianjjones** [comment]
This is fixed by https://github.com/01org/zephyr.js/pull/1423

**Comment by qiaojingx** [comment]
Verified with commit ca7af31 on Arduino101, FRDM-K64F and Linux. This issue is not reproduced.
