### ISSUE TITLE
[sensor] Gyroscope and temperature sensors are not supported on K64F

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1450]
### Description

W3C Sensors should support on-board sensors on the FRDM-K64F according to feature #1320. But gyroscope and temperature sensors are still not supported on K64F. They are undefined.

### Test Code

[BMI160Gyroscope.js](https://github.com/01org/zephyr.js/blob/master/samples/BMI160Gyroscope.js);
[BMI160Temperature.js](https://github.com/01org/zephyr.js/blob/master/samples/BMI160Temperature.js);

### Steps to Reproduction

1. `make BOARD=frdm_k64f JS=samples/BMI160Gyroscope.js`
2. `cp outdir/frdm_k64f/zephyr.bin /media/<username>/MBED/`

### Actual Result

 ![selection_150](https://user-images.githubusercontent.com/19813546/29157990-c11be2da-7ddb-11e7-9cc5-2ea7fd41eac9.png)

![selection_151](https://user-images.githubusercontent.com/19813546/29158012-d4086d28-7ddb-11e7-960d-54980bd4fcd6.png)

### Expected Result

Gyroscope and temperature sensors are supported on K64F
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | ddc30dc | FRDM-K64F | Aug 10, 2017 | Fail

**Comment by jimmy-huang** [comment]
Yeah, we don't currently support any on-board temperature or magnetometer sensors with w3c sensors for the frdm board.

**Comment by haoxli** [comment]
Thanks for your clarification.  @qiaojingx please close this one.
