### ISSUE TITLE
[sensor] incorrect update frequency / sampling rate of the Sensor API implementation

### ISSUE THREAD

**Issue by ttzeng** [01org/zephyr.js#1451]
The [IDL of the ZJS Sensor interface](https://github.com/01org/zephyr.js/blob/master/docs/sensors.md#web-idl) states the sampling rate 'frequency' is in Hz, however if we changed the sampling rate of the [Accelerometer](https://github.com/01org/zephyr.js/blob/master/samples/BMI160Accelerometer.js), [Gyroscope](https://github.com/01org/zephyr.js/blob/master/samples/BMI160Gyroscope.js), or [Temperature](https://github.com/01org/zephyr.js/blob/master/samples/BMI160Temperature.js) sample to 1 Hz, the actual update frequency is faster than every 1 second.

**Comment by grgustaf** [comment]
@jimmy-huang please look into what the limits of the frequency are. If very low frequency isn't possible, maybe we could implement it with timers.

**Comment by jimmy-huang** [comment]
@ttzeng can you clarify which sample you were running, was this in the ashell/ide or just build and flash on the device?  Because I think the ashell/ide use the polling while the flash image uses triggers.

**Comment by ttzeng** [comment]
@jimmy-huang thanks for looking into this. Hereby I confirm this issue has been fixed by #1462 :+1:
