### ISSUE TITLE
[ws] BUS FAULT error when running dhcp websocket

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1458]
### Description

This is a regression issue. When running websocket-dhcp, got `BUS FAULT` error on FRDM-K64F.

### Test Code

[WebSocketServer4.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer4.js);
[test-ws4-server-dhcp.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws4-server-dhcp.js);
[test-dhcp-ws-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-dhcp-ws-manual.js);

### Steps to Reproduction

1. Build [WebSocketServer4.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer4.js) on FRDM-K64F.
3. Connect to a router which assigns a DHCP address
4. `node node samples/websockets/NodeWebSocketClient4.js <ip address> <port>`

### Actual Result

BUS FAULT error:
![selection_159](https://user-images.githubusercontent.com/19813546/29206842-4e250d70-7eb6-11e7-8391-16c4139bb491.png)

### Expected Result

No error
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | e3e4dde | FRDM-K64F | Aug 11, 2017 | Fail
master | f3625a8 | FRDM-K64F | Aug 11, 2017 | Pass

**Comment by grgustaf** [comment]
@qiaojingx, just wanted to comment that you guys do a really great job and in particular giving us a commit id where it passed and then failed for a regression is really helpful. :)

**Comment by qiaojingx** [comment]
I found BUS FAULT error begins with commit 46d73b5. A little different is:  `(ERROR) no handle found
` will print when first connect, then bus fault error occurs when second connect.
![selection_160](https://user-images.githubusercontent.com/19813546/29256036-d5651e54-80d9-11e7-9965-ffca4b926b74.png)
Hope it is also helpful. :)

**Comment by grgustaf** [comment]
The no handle found issue should be fixed by #1503; please retest.

**Comment by grgustaf** [comment]
Oops that was net, this is ws - I'll need to check this out. It might well be the same type of problem that I just fixed in net.

**Comment by brianjjones** [comment]
I tested it and see the same thing qiaojingx did.  I didn't get a chance to start trouble shooting it, but its easily reproducible.

**Comment by qiaojingx** [comment]
Verified with a0b1217 + #1513. It only fixes `bus fault` issue in [WebSocketServer4.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer4.js); But, other two tests([test-ws4-server-dhcp.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws4-server-dhcp.js); [test-dhcp-ws-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-dhcp-ws-manual.js;)) still get `bus fault` issue when exit node by `ctrl+c`

Besides, `BUS FAULT` error is also caused in [UDPEchoServ6.js](https://github.com/01org/zephyr.js/blob/master/samples/UDPEchoServ6.js), [UDPEchoServ4.js](https://github.com/01org/zephyr.js/blob/master/samples/UDPEchoServ4.js) and [test-ws6-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws6-server.js)

**Comment by grgustaf** [comment]
Fixed by updated #1513

**Comment by qiaojingx** [comment]
Verified with commit 5403f92. This issue is not reproduced.
