### ISSUE TITLE
[tcp] 'no handle found' error happens when running TCPEchoServ4_DHCP.js

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1468]
### Description

This is a regression issue. When running [TCPEchoServ4_DHCP.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ4_DHCP.js), got `no handle found ` error on FRDM-K64F.

### Test Code

[TCPEchoServ4_DHCP.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ4_DHCP.js);

### Steps to Reproduction

1. Build [TCPEchoServ4_DHCP.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ4_DHCP.js) on FRDM-K64F.
3. Connect to a router which assigns a DHCP address
4. `echo "hello" | nc <DHCP ip> 4242`

### Actual Result

no handle found error occurs when try to connect with net-tools. if try to connect many times, it also can reproduce bus fault error.
![selection_163](https://user-images.githubusercontent.com/19813546/29310051-e67f0172-81de-11e7-9937-3884bcaf88ec.png)

### Expected Result

No error
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | e3e4dde- 46d73b5 | FRDM-K64F | Aug 15, 2017 | Fail
master | 9f75ded | FRDM-K64F | Aug 15, 2017 | Pass

### Additional Information

Not sure if it is the same as #1458 ,but they are caused by the same commit 46d73b5.

**Comment by jimmy-huang** [comment]
I am also seeing this when I run the BLE.js sample on the nRF52 board, but not on the Arduino 101:

BLE sample...

src/zjs_event.c:397 zjs_emit_event():
(ERROR) no handle found

**Comment by qiaojingx** [comment]
Verified with commit 06cce05 on FRDM_K64F. `Cannot send data to peer(-9)` is print instead of `No handle found` error when send data by net-tools. But `BUS FAULT` error still occurs after connect with net-tools for many times.
![selection_144](https://user-images.githubusercontent.com/19813546/29595143-428b0204-87e8-11e7-9062-379fb8fa8034.png)
![selection_145](https://user-images.githubusercontent.com/19813546/29595161-5ae35108-87e8-11e7-94e3-fbf71cd3bff7.png)

**Comment by qiaojingx** [comment]
Verified with commit a0b1217, this issue is not reproduced. But another issue is found, tracking by #1512
