### ISSUE TITLE
[dhcp] dhcp does not work with ENC28J60

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1488]
### Description

dhcp function is broken on Arduino101 with ENC28J60 Ethernet Board. 
 
### Test Code

[WebSocketServer4.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer4.js);
[test-ws4-server-dhcp.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws4-server-dhcp.js);
[test-dhcp-ws-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-dhcp-ws-manual.js);
[TCPEchoServ4_DHCP.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ4_DHCP.js);
 [test-tcp4-server-DHCP.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server-DHCP.js);

### Steps to Reproduction

1. connect ENC28J60 to Arduino101 by wiring the below pins on boards.
```
CS  -> IO10
SI -> IO11
SO -> IO12
SCK -> IO13
VCC -> 3.3v
GND -> GND
INT -> IO4
```
2. Connect ENC28J60 Ethernet Board and PC to the same router.
3. Flash Arduino101 with test sample.
```
$ make JS=samples/TCPEchoServ4_DHCP.js FORCE=zjs_net_l2_enc28j60.json
$ make dfu
```
4. Connect TCPEchoServ4_DHCP.js using net-tools.
`$ nc <DHCP IP> 4242`
 
### Actual Result

![selection_140](https://user-images.githubusercontent.com/19813546/29596479-f351821e-87ef-11e7-8a0d-0c657d3ad4ac.png)

### Expected Result

 dhcp works on Arduino101 with ENC28J60 Ethernet Board.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 06cce05 | Arduino 101 | Aug 23, 2017 | Fail

**Comment by grgustaf** [comment]
Zephyr JIRA #1753 covered this issue and it was dropped as "Won't Do" because A101 is no longer a reference platform of concern. I git bisected the problem in Zephyr and it's a result of Zephyr commit db11fcd, net_pkt / net_buf changes. So if we care enough, we could look further into that.

**Comment by grgustaf** [comment]
This was fixed by zephyrproject-rtos/zephyr#1284 which will presumably go into 1.9.

**Comment by grgustaf** [comment]
Oh weird, apparently semaphores were broken back at that db11fcd commit; when I update to 1.8 w/ your patch, it works great!

**Comment by haoxli** [comment]
@grgustaf So we will remove those tests in #1488 from 0.4 testing scope. Is that OK?

**Comment by grgustaf** [comment]
@haoxli sounds good, yes.
