### ISSUE TITLE
[timer] Running test-timers.js on ArduinoDUE and F411RE cause BUS FAULT 

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1498]
### Description

When running [test-timers.js](https://github.com/01org/zephyr.js/blob/master/tests/test-timers.js) on ArduinoDUE and F411RE, BUS FAULT occurs, a lot of garbled log is printed continuously.

### Test Code

[test-timers.js](https://github.com/01org/zephyr.js/blob/master/tests/test-timers.js)
 
### Steps to Reproduction

1.  F411RE:
```
$ make JS=tests/test-timers.js BOARD=nucleo_f411re
$ cp outdir/nucleo_f411re/zephyr.bin /media/<username>/NODE_F411RE/
```

2. ArduinoDUE:
```
$ make BOARD=arduino_due JS=tests/test-timers.js
$ bossac -p ttyACM0 -e -w -v -b outdir/arduino_due/zephyr.bin
```

### Actual Result

 F411RE:
![screenshot from 2017-08-25 16-41-51](https://user-images.githubusercontent.com/19813546/29706965-2de74bb2-89b6-11e7-8aad-ce81d8e60fa1.png)

ArduinoDUE:
![screenshot from 2017-08-25 16-39-59](https://user-images.githubusercontent.com/19813546/29706967-2eb63832-89b6-11e7-8064-7b955697659f.png)

### Expected Result

No error occurs.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 528a6f0 | Arduino Due | Aug 25, 2017 | Fail
master | 528a6f0 | Nucleo F411RE | Aug 25, 2017 | Fail

**Comment by grgustaf** [comment]
We have Due boards and should get F411RE soon, so we can take a look at this. But these haven't been supported board to date so won't fix for 0.4.

**Comment by brianjjones** [comment]
Nucleo F411RE works fine for me on the latest master, we might have already fixed the issue.  I see:

PASS - clearInterval: intervalID does not exist
UPASS - clearTimeout: timeoutID does not exist
UPASS - setInterval: set delay
PASS - clearInterval: intervalID
PASS - setInterval: set delay and optional arg
PASS - setTimeout: set delay
PASS - setTimeout: set delay and optional arg
PASS - setTimeout: set 20 arg for timeout
PASS - clearTimeout: timeoutID
TOTAL: 9 of 9 passed

@qiaojingx  are you still seeing this issue?

**Comment by qiaojingx** [comment]
Verified with latest commit 087938a in master. This issue is not reproduced on Nucleo F411RE and Arduino due anymore.
Close
