### ISSUE TITLE
[tcp] Cannot receive TCP packet when send single data pack by net-tools

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1512]
### Description

 When sending single data pack by command `echo "hello" | nc 192.0.2.1 4242` to [TCPEchoServ4.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ4.js), tcpserver cannot recevie tcp packet(`(ERROR) Cannot receive TCP packet (family 10), ret=-9`). By if connect with `nc 192.0.2.1 4242` first, then send data, this issue will not reproduce. The same issue also occurs when running tcp server6. But It works fine on Arduino101.

### Test Code

[TCPEchoServ4.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ4.js);
[TCPEchoServ4_DHCP.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ4_DHCP.js);
[TCPEchoServ6.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ6.js)
 
### Steps to Reproduction

1.  `make JS=samples/TCPEchoServ4.js BOARD=frdm_k64f`
2.  `cp outdir/frdm_k64f/zephyr.bin /media/<username>/MBED/`
3.  add router and address on Linux
`ip route add 192.0.2.0 dev <ethX>`
`ip addr add 192.0.2.2 dev <ethX>`
4. send single data pack by net-tools: 
`echo "hello" | nc 192.0.2.1 4242`

### Actual Result

 TCP4:
![selection_008](https://user-images.githubusercontent.com/19813546/29905185-abea9518-8e3f-11e7-92f7-b24eea666126.png)

TCP6:
![selection_006](https://user-images.githubusercontent.com/19813546/29905109-3f3782a0-8e3f-11e7-88ac-07788ceb0c02.png)

### Expected Result

Arduino101:
![selection_007](https://user-images.githubusercontent.com/19813546/29905114-42c01f22-8e3f-11e7-96b4-2a350b7f3e8b.png)
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | a0b1217 | FRDM-K64F | Aug 31, 2017 | Fail
master | a0b1217 | Arduino101 | Aug 31, 2017 | Pass

**Comment by LWY931119** [comment]
When I run TCPEchoServ4.js on my arduino101 I can't  connect to it by 'nc 192.0.2.1 4242',but TCPEchoServ6.js works fine .Whether arduino101 support TCPEchoServ4.js?
I already added router and address on Linux  by ' ip route add 192.0.2.0 dev  bt0 'and ' ip addr add 192.0.2.2 dev bt0'.

**Comment by qiaojingx** [comment]
@LWY931119, TCPEchoServ4.js is only supported on arduino101 over Ethernet board, not over ble. Because 6lowpan is used for arduino over ble, and it is IPv6.  For IPv4 testing, you need a ENC28J60 Ethernet Board. Please refer to [ENC28J60 Ethernet Board](https://github.com/01org/zephyr.js#enc28j60-ethernet-board) for IPv4 testing on Arduino101.

**Comment by LWY931119** [comment]
@qiaojingx Thank you for your help. I still want to know there are any Http sample can run on Arduino101. The zephyr/samples/net/http_server says 'This sample is meant to be compilable in QEMU only'.

**Comment by qiaojingx** [comment]
http api is a further feature for ZJS. Feature #374.
For zephyr OS, http should supported in either QEMU or real device like Freedom Board (FRDM-K64F) according to https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/net/http_server.

**Comment by qiaojingx** [comment]
Verified with latest commit 087938a in master, this issue occurs on Arduino101 over Ethernet(not reproduce with d04ae00). Data "hello" is not received.
![selection_017](https://user-images.githubusercontent.com/19813546/30154216-c8384cfe-93eb-11e7-82b5-0bc2caecc87a.png)

**Comment by grgustaf** [comment]
Fixed by #1522

**Comment by qiaojingx** [comment]
Verified with commit 79e8164 + #1522. `Cannot receive TCP packet` issue is fixed. But new issues are brought.
An minor error is printed on K64F:
![selection_001](https://user-images.githubusercontent.com/19813546/30201270-ba6c7c46-94ac-11e7-82e0-dfd6cdbd8722.png)

Cannot connect by net-tools second time on Arduino101 over Ethernet.
![selection_002](https://user-images.githubusercontent.com/19813546/30201450-6a505d80-94ad-11e7-9739-c1748962f5ec.png)

**Comment by grgustaf** [comment]
There's nothing wrong with the first one - maybe we need to think about whether this should be an "error" or not. The socket has already been closed by the remote end by the time the socket write is attempted, so the write fails. But there's no getting around that.

The second one I'll have to look into I guess.

**Comment by grgustaf** [comment]
The problem w/ A101 + Eth is fixed in #1523

**Comment by qiaojingx** [comment]
Verified with commit 2a71022. This issue is not reproduced.
