### ISSUE TITLE
[ashell] 'grove_lcd' module can't be found  

### ISSUE THREAD

**Issue by xiaoyu3x** [01org/zephyr.js#1553]
## Issue description
'grove_lcd' module can't be found  when running [GroveLCD.js](https://github.com/01org/zephyr.js/blob/master/samples/GroveLCD.js) in ashell. 

## Test Code
[GroveLCD.js](https://github.com/01org/zephyr.js/blob/master/samples/GroveLCD.js)

## Steps to reproduce
1. Connect grove lcd and Arduino 101 board.
2. Flash ashell into 101 board, open minicom port. 
3. Copy [GroveLCD.js](https://github.com/01org/zephyr.js/blob/master/samples/GroveLCD.js) to ashell and run it.
4. When running this sample on Web IDE, get the same result as ashell

## Actual Result

**Ashell and Web IDE**
`Not SupportedError: module not found:'grove_lcd'`
![selection_009](https://user-images.githubusercontent.com/17694094/30794425-92cc0138-a1fa-11e7-9a16-ba525d410729.png)

## Expected Result
Grove LCD works normally and no error.

## Test Build
Branch| Commit id | Target Device |Test Date | Result 
---| ---| ---| ---|--- 
master | [cbe7e8f](https://github.com/01org/zephyr.js/commit/cbe7e8f98910f07a9d30bea7fccf880b449bb3d3) | Arduino 101 | Sep 25, 2017 | Fail 
master | [174f35f](https://github.com/01org/zephyr.js/commit/174f35f2a022037ca6559e5f66c961022210ac82) | Arduino 101 | Sep 25, 2017 | Pass

**Comment by jimmy-huang** [comment]
We took grove lcd out of ashell/IDE recently due to growing ROM size with ashell, that it will no longer fit, so yeah, grove_lcd is not expected to work out of the box, so this is not a bug.

**Comment by xiaoyu3x** [comment]
OK, according to developer's advice, this bug will be closed.
