### ISSUE TITLE
[ashell] The program is hanged after running 'BMI160Accelerometer.js' for a period of time

### ISSUE THREAD

**Issue by xiaoyu3x** [01org/zephyr.js#1560]
## Issue description
There is 7/10 times that 'BMI160Accelerometer.js' will be hanged  after running it for a period time  in ashell or IDE.

## Test Code
[BMI160Accelerometer.js](https://github.com/01org/zephyr.js/blob/master/samples/BMI160Accelerometer.js)

## Steps to reproduce
1. Flash ashell into 101 board and start it : `minicom -D /dev/ttyACM0`
2. Copy 'BMI160Accelerometer.js' to ashell and run it.
4. When running this sample on Web IDE, get the same result as ashell

## Actual Result

The program is hanged after running 'BMI160Accelerometer.js' for a period of time

## Expected Result
'BMI160' works normally and no hang.

## Test Build
Branch| Commit id | Target Device |Test Date | Result 
---| ---| ---| ---|--- 
master | [cbe7e8f](https://github.com/01org/zephyr.js/commit/cbe7e8f98910f07a9d30bea7fccf880b449bb3d3) | Arduino 101 | Sep 26, 2017 | Fail 
master | [174f35f](https://github.com/01org/zephyr.js/commit/174f35f2a022037ca6559e5f66c961022210ac82) | Arduino 101 | Sep 25, 2017 | Pass

**Comment by grgustaf** [comment]
@xiaoyu3x how long were these runs?

**Comment by xiaoyu3x** [comment]
hi, @grgustaf 
I just retested 10 times with commit [cbec79d](https://github.com/01org/zephyr.js/commit/cbec79db327b51501806851685eb896739a9a424) and it costs about 5 min every time, but it wasn't reproduced.

**Comment by xiaoyu3x** [comment]
This issue isn't reproduced on [1b970c8](https://github.com/01org/zephyr.js/commit/1b970c822e051d900777c0b66e3723e8c40cd74f), so closed it.
