### ISSUE TITLE
[ashell] command boot not working properly

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1561]
### Description

1. After set [BMI160Accelerometer.js](https://github.com/01org/zephyr.js/blob/master/samples/BMI160Accelerometer.js) as boot file in ashell, then reboot device, `ringbuf put errors` will print at the beginning. And sensor start delay.

2. Not all the samples can start automatically after be set by boot. e.g. [BLE.js](https://github.com/01org/zephyr.js/blob/master/samples/BLE.js)

### Test Code

[Ashell](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md);
 
### Steps to Reproduction

1. `make ashell ROM=256`
2. `make dfu`
3. load the code of samples to ashell with name as test.js
4. `acm>boot test.js`
5. `acm>reboot`

### Actual Result

1. ringbuf put errors print first if boot BMI160Accelerometer.js in ashell
![selection_017](https://user-images.githubusercontent.com/19813546/30838501-6ecd306e-a29e-11e7-8945-5d1583c41ccf.png)

2. BLE service not start if boot BLE.js in ashell although can see `BLE sample...` in `/dev/ttyUSB0`.
![selection_018](https://user-images.githubusercontent.com/19813546/30838929-1ba60642-a2a1-11e7-9d1e-164eff295497.png)

### Expected Result

No error and boot file can start automatically after reboot.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | cbe7e8f | Arduino 101 | Sep 26, 2017 | Fail
master | b11dc55 | Arduino 101 | Sep 26, 2017 | Fail

**Comment by xiaoyu3x** [comment]
This issue is reproduced when using commit [3ca5e23](https://github.com/01org/zephyrjs-ide/commit/3ca5e23effd1ef9dddcfa49a963c660fd225cf0a)

**Comment by brianjjones** [comment]
This is fixed by #1615

**Comment by qiaojingx** [comment]
Verified with commit e19ed4f. This issue is fixed.
