### ISSUE TITLE
[ocf] Ocf Server doesn't work after zephyr update to 1.9

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1586]
### Description

After update zephyr to 1.9.0, `CPU exception` occurs when running Ocf Server on A101(ble mode and Ethernet mode) and OcfClient cannot connect to OcfServer on FRDM_K64F.
 
### Test Code

[OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js);
[OcfSensorServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorServer.js);
[OcfMultiSensor.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfMultiSensor.js);
[test-ocfserver.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfserver.js)
 
### Steps to Reproduction

Arduino 101 over BLE:
1. `make JS=samples/OcfServer.js ROM=256` 
2. `make dfu`

Arduino 101 with Ethernet board:
1. `make JS=samples/OcfServer.js FORCE=zjs_net_l2_enc28j60.json ROM=256` 
2. `make dfu`

FRDM_K64F:
1. `make JS=samples/OcfServer.js BOARD=frdm_k64f`
2. `cp outdir/frdm_k64f/zephyr.bin /media/<USERNAME>/MBED/`

### Actual Result

Scene 1:  Arduino 101 over ble
 
1). [OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js):
![selection_031](https://user-images.githubusercontent.com/19813546/31487767-2be45e12-af6e-11e7-8559-2d64976e4a2c.png)

2). [OcfSensorServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorServer.js) and [OcfMultiSensor.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfMultiSensor.js):

No console log is printed.

3). [test-ocfserver.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfserver.js):
![selection_032](https://user-images.githubusercontent.com/19813546/31487822-503c08be-af6e-11e7-8703-83ac61e4a191.png)

Scene 2:  Arduino 101 with Ethernet board

1). [OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js):
![selection_003](https://user-images.githubusercontent.com/19813546/31934470-2b68e68c-b87a-11e7-84ea-12cdb3c5374c.png)

2). [OcfSensorServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorServer.js):
![selection_004](https://user-images.githubusercontent.com/19813546/31934507-4a95106c-b87a-11e7-9faa-a1c87d314c66.png)

3). [OcfMultiSensor.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfMultiSensor.js):
![selection_005](https://user-images.githubusercontent.com/19813546/31934514-4ff223e2-b87a-11e7-847d-88974b86981c.png)

4). [test-ocfserver.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfserver.js):
![selection_006](https://user-images.githubusercontent.com/19813546/31934529-562e8f02-b87a-11e7-832a-aad31fac5275.png)

Scene 3:  FRDM_K64F
1). OcfClient cannot connect to OcfServer
![selection_001](https://user-images.githubusercontent.com/19813546/31713157-55bcb16a-b3cb-11e7-8723-3c85825c4271.png)
![selection_002](https://user-images.githubusercontent.com/19813546/31713158-5626f0b6-b3cb-11e7-8d1f-1878ab01cbb2.png)

### Expected Result

OcfServer started without error and OcfClient can connect to OcfServer.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 6eedbe4 - 1d5a99d | Arduino 101 | Oct 12, 2017 | Fail
master | 03cc671 | Arduino 101 | Oct 12, 2017 | Failed by #1565 
master | 6eedbe4 - 1d5a99d | FRDM_K64F | Oct 12, 2017 | Fail
master | 03cc671 | FRDM_K64F | Oct 12, 2017 | Failed by #1565

**Comment by xiaoyu3x** [comment]
This issue is reproduced with commit [1d5a99d](https://github.com/01org/zephyr.js/commit/1d5a99d5e2b8b09602e79cd4c1cd1c260eaf224b)

**Comment by xiaoyu3x** [comment]
There isn't any output information on minicom when flashing [temperature.js]( https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/temperature.js),[multiserver.js](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/multiserver.js) and [multiserver2.js](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/multiserver2.js) to Ard 101 with [1d5a99d](https://github.com/01org/zephyr.js/commit/1d5a99d5e2b8b09602e79cd4c1cd1c260eaf224b)

**Comment by qiaojingx** [comment]
Verified with commit dcf56a9. OcfServer works on Arduino101, but it still doesn't work on FRDM-K64F. Create a separate issue(#1660) to track it.
