### ISSUE TITLE
[board] board is not supported in qemu

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1594]
### Description

Building samples and tests of Board API failed in qemu. Other tests which used board api are also failed.
 
### Test Code

[test-board.js](https://github.com/01org/zephyr.js/blob/master/tests/test-board.js);
[test-board-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-board-manual.js);
[Board.js](https://github.com/01org/zephyr.js/blob/master/samples/Board.js);
[test-tcp6-client.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp6-client.js);
[test-dhcp-ws-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-dhcp-ws-manual.js);

### Steps to Reproduction

1. `make BOARD=qemu_x86 qemu JS=samples/Board.js`
 
### Actual Result

![selection_037](https://user-images.githubusercontent.com/19813546/31601506-aca36f36-b28c-11e7-9baf-aeef00afe472.png)
 
### Expected Result

 
![selection_038](https://user-images.githubusercontent.com/19813546/31602374-65e35392-b28f-11e7-90d5-1439b4846dd8.png)

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | fae50ff - 1d5a99d | qemu | Oct 16, 2017 | Fail
master | 6eedbe4 | qemu | Oct 16, 2017 | Pass

**Comment by grgustaf** [comment]
Works for me on master, can you try again @qiaojingx?

**Comment by qiaojingx** [comment]
Verified with commit cbec79d in master. This issue is fixed. Close.
