### ISSUE TITLE
K64F build is blocked by bug in Zephyr SDK 0.8.2

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#160]
When you try to build for K64F now, you run into an error where gettimeofday() hasn't been declared. This is [ZEP-644](https://jira.zephyrproject.org/browse/ZEP-644) in the Zephyr project. This issue is just to keep track of that one because it's blocking K64F development in Zephyr.js.

**Comment by jprestwo** [comment]
I was having a similar problem. I never saw the line:
`/opt/zephyr-sdk/sysroots/i686-pokysdk-linux/usr/libexec/arm-poky-eabi/gcc/arm-poky-eabi/5.2.0/real-ld: error: /opt/zephyr-sdk/sysroots/armv5-poky-eabi/usr/lib/./libc.a(lib_a-setjmp.o): Conflicting CPU architectures 13/1`

But I was getting the same `..VFP register arguments...` error. I just removed my Zephyr sdk (`sudo rm -rf /opt/zephyr-sdk`), and updated to version 0.8.2 and now I am able to build for the K64.

**Comment by pfalcon** [comment]
There was an issue in master with building frdm_k64f which was fixed by https://github.com/01org/zephyr.js/issues/282, but now waits cherry-pick to devel. @poussa : Ping. Or I can resubmit that patch against devel branch indeed.

**Comment by poussa** [comment]
Hmm, I though I did the cherry-pick to devel. See 4a0eeefc6b3d96e56a28a3937568e776c8f31ba5

**Comment by pfalcon** [comment]
@poussa, oops, sorry, looked at the wrong place. Then both master and devel branch now build for frdm_k64f, confirmed by @jprestwo and me, and I suggest this issue to be closed. (The original issue of SDK 0.8.2 compatibility was worked around on both JrS and Z.js sides, and that workaround is formally correct (specifying API level expected from system headers), so no need to worry about it further).
