### ISSUE TITLE
Allow modules to unregister service routines

### ISSUE THREAD

**Issue by jimmy-huang** [01org/zephyr.js#1619]
There's a zjs_register_service_routine() function but no corresponding unregister_service_routine(), this means that when module is cleaned up in IDE, there will be resource leaks, and also each time a module is initialized, it will kept adding to the resource routine map and eventually break.

**Comment by brianjjones** [comment]
#1635 will add this functionality.

**Comment by jimmy-huang** [comment]
closing this as it is merged
