### ISSUE TITLE
[ashell] ble cannot be enabled again after execute 'stop'

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1621]
### Description

After stopping samples/BLE.js in ashell, bluetooth cannot be re-enabled.
 
### Test Code

[ashell](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md)
[BLE.js](https://github.com/01org/zephyr.js/blob/master/samples/BLE.js) 
### Steps to Reproduction

1. `make ashell ROM=256`
2. `make dfu`
3.  `$ screen /dev/ttyACM0 115200` to connect to the ashell from a terminal
4. `acm> load test.js` and Enter
5. `RAW> /*Paste code of BLE.js */ `
6. `acm> run test.js`
7. `acm> stop`
8. `acm> load test.js`
### Actual Result

Failed to enable bluetooth.
![selection_015](https://user-images.githubusercontent.com/19813546/32257255-69a82e38-be8a-11e7-97ff-777ebced9ec5.png)

 If connect to this ble server with phone, error message will print.
![selection_016](https://user-images.githubusercontent.com/19813546/32257278-824ca072-be8a-11e7-8250-c8397336ecc8.png)

### Expected Result

BLE can be enabled without error.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 6d751ea | Arduino 101 | Nov 1, 2017 | Fail
 
### Additional Information

This issue is also reproduced in Zephyr IDE.

**Comment by jimmy-huang** [comment]
this is a know issue, the reason is that Zephyr doesn't have a way to disable BT after it has been up, thus we added a error message when you run this in the IDE that you'll need to reboot the board in order to get the BLE sample to work again.  So this will be won't fix until Zephyr has added support to disable/re-enable BT.

**Comment by qiaojingx** [comment]
Closed since Zephyr doesn't support to disable/re-enable BT
