### ISSUE TITLE
[gfx] Out of memory when draws a solid rectangle

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1627]
### Description

When test [/samples/SPI_Screen.js](https://github.com/01org/zephyr.js/blob/master/samples/SPI_Screen.js), throw out an error.

Error log:
```
511:(ERROR) malloc(40960) failed
SPI error: argument cannot have an error flag
```

 

### Test Code

[/samples/SPI_Screen.js](https://github.com/01org/zephyr.js/blob/master/samples/SPI_Screen.js)

 

### Actual Result

Throw out an error.
 

### Expected Result

Work well.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | e19ed4f | Arduino 101 | Nov 1, 2017 | Fail

**Comment by grgustaf** [comment]
@brianjjones is this fixed by your new frameless mode for A101?

**Comment by grgustaf** [comment]
@cuiyanx was this on A101 I assume? That matters because of the low available RAM.

**Comment by cuiyanx** [comment]
@grgustaf Yes, I think so.
@brianjjones Can we work around this?

**Comment by cuiyanx** [comment]
Fixed and closed.
