### ISSUE TITLE
[gfx] Missing GFX module

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#1629]
### Description

When test [/samples/SPI_Screen.js](https://github.com/01org/zephyr.js/blob/master/samples/SPI_Screen.js), throw out an error.

Error log:
`NotSupportedError: module not found: 'gfx'`

 

### Test Code

 [/samples/SPI_Screen.js](https://github.com/01org/zephyr.js/blob/master/samples/SPI_Screen.js)

 

### Actual Result

Throw out error.
 

### Expected Result

No error.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 82c3083c9 | Arduino 101 | Nov 3, 2017 | Fail

**Comment by brianjjones** [comment]
This is because we switched to using Jerry modules and GFX wasn't set up for that yet.  #1636 will take care of this issue.

**Comment by cuiyanx** [comment]
Fixed and closed
