### ISSUE TITLE
[webusb] webusb module is missing

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1637]
### Description

This is a regression issue. After patch #1575. webusb module is missing.
 
### Test Code

[WebUSB.js](https://github.com/01org/zephyr.js/blob/master/samples/WebUSB.js);
[WebUSBConfig.js](https://github.com/01org/zephyr.js/blob/master/samples/WebUSBConfig.js); 
[WebUSBConfigGroveLCD.js](https://github.com/01org/zephyr.js/blob/master/samples/WebUSBConfigGroveLCD.js); 
[test-webusb-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-webusb-manual.js); 

### Steps to Reproduction

1. `make JS=samples/WebUSB.js`
2. `make dfu`
### Actual Result

![selection_031](https://user-images.githubusercontent.com/19813546/32430433-45ab0eb2-c29d-11e7-8a94-f931f1a8b9d9.png)
 
### Expected Result

Sample runs successfully and  a pop up notification displays in chrome.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | a8ff356 - eaee8d5 | Arduino 101 | Nov 6, 2017 | Fail
master | 6149191 | Arduino 101 | Nov 6, 2017 | Pass

**Comment by brianjjones** [comment]
This should be fixed by #1642

**Comment by qiaojingx** [comment]
Verified with commit 687af46 + #1642. This issue can be fixed.
I will close it after patch merged.

**Comment by qiaojingx** [comment]
Verified with commit 8fe2e17. This issue is fixed. Close
