### ISSUE TITLE
[event/ble] Type Error occurs in event and ble

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1638]
### Description

This is a regression issue. After patch #1575. `Error: handle was incorrect type` occurs when running event and ble related samples and tests.
 
### Test Code

[Events.js](https://github.com/01org/zephyr.js/blob/master/samples/tests/Events.js);
[test-event.js](https://github.com/01org/zephyr.js/blob/master/tests/test-event.js); 
[BLE.js](https://github.com/01org/zephyr.js/blob/master/samples/BLE.js);
[SensorBLEDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/SensorBLEDemo.js);
[test-ble.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ble.js); 

### Steps to Reproduction

1. `make JS=samples/tests/Events.js`
2. `make dfu`
### Actual Result

result of Events.js
A101 and K64F:
![selection_025](https://user-images.githubusercontent.com/19813546/32430654-2f4f56d6-c29e-11e7-95bf-b6fe45e2638e.png)
Linux:
![selection_031](https://user-images.githubusercontent.com/19813546/32430753-97e59dcc-c29e-11e7-9cad-459dc696078a.png)

result of BLE.js
A101:
![selection_025](https://user-images.githubusercontent.com/19813546/32484099-ab774416-c36c-11e7-95bf-56f4b51ce9b3.png)

### Expected Result

Sample runs successfully.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | a8ff356 - eaee8d5 | Arduino 101 & FRDM-K64F & Linux | Nov 6, 2017 | Fail
master | 6149191 | Arduino 101 & FRDM-K64F & Linux | Nov 6, 2017 | Pass

**Comment by brianjjones** [comment]
This should be fixed by #1642

**Comment by qiaojingx** [comment]
Verified with commit 687af46 + #1642. TypeError in Events can be fixed.
But TypeError in BLE is still there.

**Comment by brianjjones** [comment]
The updated version of #1642 should take care of the issue for BLE as well.

**Comment by qiaojingx** [comment]
Verified with commit 8fe2e17. This issue is fixed. Close
