### ISSUE TITLE
[dhcp] Failed to build with net-config module.

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1639]
### Description

This is a regression issue. After patch #1575 merged, unable to build samples and tests which required `net-config` module.
 
### Test Code

[TCPEchoServ4_DHCP.js](https://github.com/01org/zephyr.js/blob/master/samples/TCPEchoServ4_DHCP.js);
[WebSocketServer4.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer4.js); 
[test-dhcp-ws-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-dhcp-ws-manual.js); 
[test-tcp4-server-DHCP.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server-DHCP.js); 
[test-ws4-server-dhcp.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws4-server-dhcp.js);
 
### Steps to Reproduction

1. `make JS=samples/TCPEchoServ4_DHCP.js`
2. `make BOARD=frdm_k64f JS=samples/TCPEchoServ4_DHCP.js`

### Actual Result

Unable to build:
![selection_027](https://user-images.githubusercontent.com/19813546/32431198-83b377be-c2a0-11e7-842a-55a88aa3edf9.png)
![selection_028](https://user-images.githubusercontent.com/19813546/32431207-8e1c14d6-c2a0-11e7-9003-fa3b8444aa02.png)

### Expected Result

Build succeed without error.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | a8ff356 - eaee8d5 | Arduino 101 & FRDM-K64F | Nov 6, 2017 | Fail
master | 6149191 | Arduino 101 & FRDM-K64F | Nov 6, 2017 | Pass

**Comment by brianjjones** [comment]
It looks like '-' isn't a valid character for Jerry modules, I've changed it to '_' to fix this.

**Comment by brianjjones** [comment]
This will be fixed by #1643

**Comment by qiaojingx** [comment]
Verified with commit 687af46 + #1643 . This issue can be fixed.
I will close it after patch merged.

**Comment by qiaojingx** [comment]
Verified with commit b81ee15. This issue is fixed. Close
