### ISSUE TITLE
[callback] Callbacks function of on event isn't triggered.

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1640]
### Description

This is a regression issue. After patch #1575 merged. Callbacks function of on event isn't triggered. It effects websocket, tcp and ocf.
 
### Test Code

[WebSocketServer.js](https://github.com/01org/zephyr.js/blob/master/samples/websockets/WebSocketServer.js);
[test-ws4-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws4-server.js); 
[test-ws6-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ws6-server.js); 
[test-tcp4-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server.js); 
[test-tcp6-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp6-server.js); 
[test-tcp4-client.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-client.js)
### Steps to Reproduction

Take WebSocketServer.js on K64F as an example:
1. `make BOARD=frdm_k64f JS=samples/websockets/WebSocketServer.js`
2. `cp outdir/frdm_k64f/zephyr.bin /media/<username>/MBED/`
3. add router and address on Linux
```
ip -6 route add 2001:db8::/64 dev eno1
ip addr add 2001:db8::2 dev eno1
```
4. `node samples/websockets/NodeWebSocketClient.js`

### Actual Result

WebSocketServer.js: 
![selection_032](https://user-images.githubusercontent.com/19813546/32432024-e266b4d0-c2a3-11e7-9994-e6042db01ae5.png)

test-ws4-server.js & test-ws6-server.js:
![selection_030](https://user-images.githubusercontent.com/19813546/32432051-00781d88-c2a4-11e7-9fb1-fcbbc5e88431.png)

test-tcp4-server.js & test-tcp6-server.js：
![selection_033](https://user-images.githubusercontent.com/19813546/32432298-0ee48694-c2a5-11e7-8391-ed5ffcd777d9.png)

### Expected Result

WebSocketServer.js: 
![selection_034](https://user-images.githubusercontent.com/19813546/32432702-899b7a18-c2a6-11e7-9436-7f8e4ce8e9c8.png)

test-ws4-server.js & test-ws6-server.js:
![selection_036](https://user-images.githubusercontent.com/19813546/32433105-da8fc2fc-c2a7-11e7-8a6c-958ce3df3361.png)

test-tcp4-server.js & test-tcp6-server.js：
![selection_035](https://user-images.githubusercontent.com/19813546/32433132-f7659b04-c2a7-11e7-8616-0b539804c0f6.png)
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | a8ff356 - eaee8d5 | Arduino 101 & FRDM-K64F | Nov 6, 2017 | Fail
master | 6149191 | Arduino 101 & FRDM-K64F | Nov 6, 2017 | Pass

**Comment by brianjjones** [comment]
I don't have a router to test this, but it might be fixed by #1642

**Comment by qiaojingx** [comment]
Verified with commit 687af46 + #1642. This issue can be fixed.
I will close it after patch merged.

**Comment by brianjjones** [comment]
@qiaojingx  thanks, #1642 has now been merged.

**Comment by qiaojingx** [comment]
Verified with commit 8fe2e17. This issue is fixed. Close
