### ISSUE TITLE
[board] Fail to build with board module

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1652]
### Description

This is a regression issue. Building samples and tests of Board API failed for Arduino101 and FRDM-K64F. Other tests which used board api also failed.
 
### Test Code

[test-board.js](https://github.com/01org/zephyr.js/blob/master/tests/test-board.js);
[test-board-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-board-manual.js);
[Board.js](https://github.com/01org/zephyr.js/blob/master/samples/Board.js);
[test-spi.js](https://github.com/01org/zephyr.js/blob/master/tests/test-spi.js);
[test-tcp6-client.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp6-client.js);
[test-dhcp-ws-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-dhcp-ws-manual.js);

### Steps to Reproduction

1. `make JS=samples/Board.js`
2. `make BOARD=frdm_k64f JS=samples/Board.js`
### Actual Result

![selection_002](https://user-images.githubusercontent.com/19813546/32717766-7d6b9cd0-c820-11e7-9063-ae23a07ae3c9.png)
 
![selection_001](https://user-images.githubusercontent.com/19813546/32717770-82525428-c820-11e7-9900-4e62a8c275fb.png)

### Expected Result

 Build successful without error

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 8248192 - b81ee15 | Arduino101 & FRDM-K64F | Nov 13, 2017 | Fail
master | e369954 | Arduino101 & FRDM-K64F | Nov 13, 2017 | Pass

**Comment by brianjjones** [comment]
I'm working on a fix for this, should be a simple #if check.

**Comment by brianjjones** [comment]
#1653 will fix this compiler issue.

**Comment by qiaojingx** [comment]
Verified with commit 8fe2e17. This issue is fixed. Close
