### ISSUE TITLE
[k64f] LEDR,LEDG,LEDB cannot write

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1657]
### Description

This is a regression issue. LEDR,LEDG,LEDB on FRDM-K64F cannot write.
 
### Test Code

[ButtonLEDs-k64f.js](https://github.com/01org/zephyr.js/blob/master/samples/ButtonLEDs-k64f.js)
[Blink-k64f.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/Blink-k64f.js) 
[test-k64f-pins.js](https://github.com/01org/zephyr.js/blob/master/tests/test-k64f-pins.js)

### Steps to Reproduction

1. `make BOARD=frdm_k64f JS=tests/test-k64f-pins.js `
2. `cp outdir/frdm_k64f/zephyr.bin /media/<username>/MBED/`

### Actual Result

test-k64f-pins.js:
![selection_005](https://user-images.githubusercontent.com/19813546/32816649-c56dbf74-c9f4-11e7-9b44-df8f7af9a5cc.png)

ButtonLEDs-k64f.js & Blink-k64f.js:
On board led is not lighted.

### Expected Result

test-k64f-pins.js:
No error.

ButtonLEDs-k64f.js & Blink-k64f.js:
On board led blinks.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 8248192 - b81ee15 | FRDM-K64F | Nov 15, 2017 | Fail
master | e369954 | FRDM-K64F | Nov 15, 2017 | Pass

**Comment by grgustaf** [comment]
This should be fixed by #1685.

**Comment by qiaojingx** [comment]
Verified with commit cbec79d + #1685 , this issue can be fixed.
I will close this bug after patch merged.
