### ISSUE TITLE
[samples] WebBluetoothDemo.js and WebBluetoothGroveLcdDemo.js need to update

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1674]
### Description

`tmp36.on("change", null);` will cause error `424:(ERROR) error calling listener ` when disconnect BT connection from WebBluetoothDemo.js and WebBluetoothGroveLcdDemo.js on A101.
 
### Test Code

[WebBluetoothDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/WebBluetoothDemo.js);
[WebBluetoothGroveLcdDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/WebBluetoothGroveLcdDemo.js);
 
### Steps to Reproduction

1. `make JS=samples/WebBluetoothDemo.js ROM=256 `
2. `make dfu`
3. connect with nRF app 
4. disconnect
 
### Actual Result

![selection_002](https://user-images.githubusercontent.com/19813546/33112823-25c97c46-cf90-11e7-82ed-eff598155b35.png)
 
### Expected Result

No error.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | dcf56a9 | Arduino 101 | Nov 22, 2017 | Fail

**Comment by cuiyanx** [comment]
Fixed and closed
