### ISSUE TITLE
'bad BLE address string' is printed and default address 'FF:EE:DD:CC:BB:AA' can't be obtained

### ISSUE THREAD

**Issue by xiaoyu3x** [01org/zephyr.js#1678]
## Description

'170:(error) bad BLE address string' is printed when running [led.js](https://github.com/intel/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/led.js) and default address 'FF:EE:DD:CC:BB:AA' can't be obtained.

## Steps to Reproduce

1.Build sample [led.js](https://github.com/intel/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/led.js)
`make ROM=256 JS=led.js`
2. Flash it into A101
`make dfu`
3. Open minicom port.
`sudo minicom -D /dev/ttyUSB0 `
4. Press 'reset' key on A101 and check port output.

## Actual Result

'170:(error) bad BLE address string' is printed and default  'FF:EE:DD:CC:BB:AA' can't be obtained.
![selection_007](https://user-images.githubusercontent.com/17694094/33192440-8aaea19a-d0fd-11e7-84cd-71813f13d44d.png)
![selection_008](https://user-images.githubusercontent.com/17694094/33193185-dab8d7a6-d101-11e7-9569-0bf9cbccf94f.png)

## Expected Result

No error outputs and default BLE address can be obtained.

## Test Build

Branch| Commit id | Target Device |Test Date | Result 
---| ---| ---| ---|--- 
master | [58ebd9e](https://github.com/01org/zephyr.js/commit/58ebd9e3c13afaaa2d2b2882dbf6ae356623f2d2) | Arduino 101 | Nov 24, 2017 | Fail 
master | [dcf56a9](https://github.com/01org/zephyr.js/commit/dcf56a9f0ed511c96abe67e26f4dc502d1212cc4) | Arduino 101 | Nov 24, 2017 | Pass

**Comment by qiaojingx** [comment]
Verified with commit 62697b3 + #1681 . This issue isn’t reproduced.
