### ISSUE TITLE
[error] Error Type is not subdivided

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1689]
### Description

This is a regression issue. When running test-error.js on Arduino101 and FRDM-K64F, two exception tests fails.
 
### Test Code

[test-error.js](https://github.com/01org/zephyr.js/blob/master/tests/test-error.js)
 
### Steps to Reproduction

1. `make JS=tests/test-error.js`
2. `make dfu`

### Actual Result

![selection_012](https://user-images.githubusercontent.com/19813546/33598603-5c6cb6c0-d9de-11e7-848e-aa890f5d428c.png)

### Expected Result

 No FAIL

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | cbec79d | Arduino 101& FRDM-K64F | Nov 4, 2017 | Fail
master | 62697b3 | Arduino 101& FRDM-K64F | Nov 4, 2017 | Pass
 
### Additional Information

This issue is caused by #1658.

**Comment by cuiyanx** [comment]
I test this bug with commit 39112c74, this bug has been fixed. Please test again.

**Comment by qiaojingx** [comment]
Verified with commit 1b970c8. This issue is fixed.
Close.
