### ISSUE TITLE
[ashell] ashell doesn't work

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#1712]
### Description

This issue a regression issue. 'Zeph' is outputted instead of commands list when ashell start. Ashell doesn't work.
 
### Test Code

[ashell](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md);
 
### Steps to Reproduction

1. `make ashell ROM=256`
2. `make dfu`

### Actual Result

![selection_018](https://user-images.githubusercontent.com/19813546/33928862-5daee234-e022-11e7-82ac-553edd803fb6.png)

![selection_019](https://user-images.githubusercontent.com/19813546/33928900-7106b08c-e022-11e7-961e-e62dc8d8d544.png)

### Expected Result

commands list of ashell should be outputted via `screen /dev/ttyACM0 115200`.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 1b970c8 | Arduino 101 | Dec 13, 2017 | Fail
master | cbec79d | Arduino 101 | Dec 5, 2017 | Pass

### Additional Information

IDE works fine.

**Comment by brianjjones** [comment]
It appears the cmake change broke the command line ashell.  Its rather strange as the IDE version works fine, and you can even use the command line within the console no problem.  Anyway, I'm working on a fix.

**Comment by brianjjones** [comment]
OK I've finally found the cause, I've created the fix here #1721

**Comment by qiaojingx** [comment]
Verified with commit b32969f. This issue is fixed.
Close.
