### ISSUE TITLE
Unable to run HelloWorld.JS on Arduino 101 with 144K partition

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#188]
Steps to reproduce:

* Have an Arduino 101 with default factory settings, i.e. 144K x86 partition
* Connect a terminal (e.g. minicom) to the serial port
* Follow the instructions here to flash ARC and x86 image: https://github.com/01org/zephyr.js#build-the-arc-image

Expected result: a "hello world" message appears to the console

Actual result: no message appears

It may well be that this is expected, because the README says "The default build settings currently expect you to be using the 256KB partition."  (https://github.com/01org/zephyr.js#getting-more-space-on-your-arduino-101), but in that case I find it confusing that the default  ZJS_PARTITION set by zjs-env.sh is 144.

**Comment by poussa** [comment]
This is fixed.
