### ISSUE TITLE
Enable easy prototyping using remote node.js

### ISSUE THREAD

**Issue by kenchris** [01org/zephyr.js#20]
One of the very nice features of Johnny-Five is that you can have a node.js instance running on your computer and then control your Arduino using that. That of course is not great for a shippable product :) but it is super nice for rapid development.

It would be interesting if we could enable something similar, by having something like a _prototype flash image_.

**Comment by grgustaf** [comment]
I'm not familiar with what Johnny Five has but this sounds similar to what @sergioamr has done with ashell, so closing.

**Comment by rwaldron** [comment]
> this sounds similar to what @sergioamr has done with ashell, so closing.

Not at all, but that's besides the point. 

@kenchris 

Johnny-Five should work fine with Arduino 101 when using [StandardFirmata or StandardFirmataBLE](https://github.com/firmata/arduino/releases)

**Comment by grgustaf** [comment]
Sorry this is another one I probably misinterpreted as I skimmed quickly, reviewing all the open issues. I guess if I understand right now, the logic runs on the host and has a minimal backend on the device. Definitely a different path than we're focusing on right now, so I'll leave this closed and mark "reconsider later".

**Comment by rwaldron** [comment]
@grgustaf no worries, and I don't think you need to mark it "reconsider later" either. It's a different "wheel house" ;)
