### ISSUE TITLE
WebBluetoothGroveLcdDemo maybe broken

### ISSUE THREAD

**Issue by poussa** [01org/zephyr.js#249]
With current master (a06678264c86fe70f2cd2d34b979f80e159c8f5c)

The temperature **notifications do not work**. The phone UI stays N/A for temperature. LCD text does not show the temperature.

LCD color change works.

Logs are clean:

```
ipm_console0: 'Sensor core running Zephyr.js ARC support image'
ipm_console0: 'Grove LCD initialized'
ipm_console0: 'Grove LCD print: Web BLE Demo'
WebBluetooth Demo with BLE...
Subscribed to temperature change
Advertising as physical web device
Color change: #ff0000
Color change: #76ff7a
```

With f8fbfa2678f6f7c59c09cd1cf639c953c3ff7445

The temperature updates but I get tons of messages on console:

```
Temperature change: 27 degrees Celsius
zjs_glcd_alloc_msg: cannot allocate message
zjs_glcd_alloc_msg: cannot allocate message
zjs_glcd_call_remote_function: invalid send message
```

**Comment by grgustaf** [comment]
Closing, this hasn't been a problem for quite a while I think.
