### ISSUE TITLE
slowness when missing grove lcd

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#258]
Before we open the repo, we should probably fix the problem where it wastes 10s to give up on the Grove LCD when booting up. Either disable that feature by default on ARC side or add the proper support to the analyze.sh feature I guess.

**Comment by grgustaf** [comment]
@jimmy-huang this is effectively fixed by your custom builds of ARC image, right? Confirm and close.

**Comment by jimmy-huang** [comment]
@grgustaf yes, this is fixed with ARC modules
