### ISSUE TITLE
[Buffer] Unable to create buffer with max value of unsigned long

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#269]
We test [test-buffer.js](https://github.com/01org/zephyr.js/blob/master/tests/test-buffer.js),  fail to create buffer with unsigned long value(2^32-1)
We find the buffer only accept the max unsigned long value smaller than 257, but the range is 0~4294967295

| Commid id | Date | Result |
| --- | --- | --- |
| c21b9fe79926732da25c78f6c6883c96f974b72d | Sep 23 | Pass |
| 147bb63c305ea58d94ed1bf6689e7352eff1a03f | Oct 7 | Fail |

Log info:
FAIL - The length of Buffer(4294967295) expected:4294967295 got:undefined
zjs_buffer_create: unable to allocate buffer
FAIL - The length of Buffer(4294967296) expected:4294967295 got:undefined

**Comment by grgustaf** [comment]
Obviously it was never going to work to have a 4GB buffer on a machine with 80KB of RAM. :)

Someone should dig into how exactly this got limited to 256 so we understand and document it, but really that is probably fine.

**Comment by xiaolongx** [comment]
This issue cannot reproduce with commit a162db1 on both Arduino_101
