### ISSUE TITLE
"docs" subdir isn't mentioned in README

### ISSUE THREAD

**Issue by pfalcon** [01org/zephyr.js#285]
"docs" subdir isn't mentioned anywhere in README, even though there's a special "Subdirectories" section. I guess it makes sense to mention it to minimize chance that users miss it, as well as gives hints how it's supposed to be used (is viewing online on Github the recommended way to read them)?

To not create a separate issue, there's a misplaced/weird line at the end of "Subdirectories" secion https://github.com/01org/zephyr.js#subdirectories : "The command will display the current expected partition size to remind you of the expected target."

**Comment by poussa** [comment]
Good catch. Need to be fixed. First PR wins!

**Comment by pfalcon** [comment]
Ok, my try is at https://github.com/01org/zephyr.js/pull/292.

**Comment by poussa** [comment]
Fixed
