### ISSUE TITLE
[Buffer] Precise data bus error in K64F 

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#295]
After flashing [BufferMemory.js](https://github.com/01org/zephyr.js/blob/master/samples/tests/BufferMemory.js) on commit a162db1 in master branch, and then rebooting frdm_k64f, precise date bus error occus

```
Error log:
Buffer stress test...
Allocating buffer 1
Allocating buffer 2
Allocating buffer 3
Allocating buffer 4
Allocating buffer 5
Allocating buffer 6
Allocating buffer 7
***** BUS FAULT *****
  Executing thread ID (thread): 0x200069d4
  Faulting instruction address:  0x00019958
  Precise data bus error
  Address: 0x00f41ccc
Fatal fault in essential thread! Spinning...

```

**Comment by poussa** [comment]
Which branch and commit ID you have?

**Comment by xiaolongx** [comment]
In devel branch.
Commit ID: aa0ba22297bf0c6b9a4be867854a7ee084737270

**Comment by grgustaf** [comment]
Based on my comment in #297 I guess that is now commit 81a0351 on master.

**Comment by brianjjones** [comment]
This appears to be fixed on master, I ran Blink-k64f.js for several minutes without any issue.  @xiaolongx please retest with the master branch

**Comment by xiaolongx** [comment]
Sorry for the confusion, update the description, please take a look.

**Comment by brianjjones** [comment]
@xiaolongx  BufferMemory.js  works for me on the current master branch.  I see it count up to 1000 with no issue.

**Comment by xiaolongx** [comment]
This issue only reproduce on FRDM_K64F, pass on Arduino 101.
But now, it blocked by #524 after commit dc703a1.

**Comment by brianjjones** [comment]
Sorry I wasn't clear, but I tested sing the FRDM_K64 and had no issues.

**Comment by xiaolongx** [comment]
This issue cannot reproduce after #535 merged on FRDM-K64F, close.
