### ISSUE TITLE
Fail to find frdm_k64f via BLE with commit aa0ba22 in devel branch

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#297]
After flashing [BLE.js](https://github.com/01org/zephyr.js/blob/master/samples/BLE.js) with commit aa0ba22297bf0c6b9a4be867854a7ee084737270, nRF-Connect and Physical Web fail to find frdm_k64f using Nexus 5

**Comment by poussa** [comment]
Is this a regression? Did it work prior to the commit?

**Comment by haoxli** [comment]
Not a regression, we test it first time on K64F after K64F can build successfully.

**Comment by grgustaf** [comment]
BTW I had to rebase devel to merge it onto master, so the commit aa0ba22 is now 81a035 on master.

**Comment by grgustaf** [comment]
Oh, there is no BLE hardware on the K64F nor has anyone looked at BLE on anything besides A101 yet. So this is invalid, but we should plan to add another supported board that does have BLE at some point and make it work.
