### ISSUE TITLE
[GPIOPins] Fail to close GPIOPins

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#311]
After closed the GPIO pin, I can read and write this pin. It is different to description of GPIOPin.close function.

GPIOPin.close
void close();
Free up resources associated with the pin. The onchange function for this pin will no longer be called, and the object should not be used for reading and writing anymore.

**Comment by grgustaf** [comment]
Technically, it doesn't say that won't work. It says you *shouldn't* do that. (I.e. it might not work in the future.) But yeah, probably we should force it to not work so people don't rely on this behavior.

**Comment by cuiyanx** [comment]
So, I think it is better method of forcing it to not work.

**Comment by grgustaf** [comment]
FWIW I see onchange does get disabled, but you're right, read/write don't.

**Comment by grgustaf** [comment]
This should be fixed by #577.
