### ISSUE TITLE
[console.log] Fail to output log via console.log

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#319]
There are two issues in console.log after merge 14dd37fe0e94635463258a21b34792bb0e56f7dd 
1. Console.log does not support output number and boolean type directly.
   Impacted samples: [AnalogReadSerial.js](https://github.com/01org/zephyr.js/blob/devel/samples/arduino/basics/AnalogReadSerial.js) and [DigitalReadSerial.js](https://github.com/01org/zephyr.js/blob/devel/samples/arduino/basics/DigitalReadSerial.js)
   Could you please confirm?
2. Fail to connect string and value with ",", it should be "+".
   Impacted samples: [Buffer.js](https://github.com/01org/zephyr.js/blob/devel/samples/Buffer.js) and [BufferMemory.js](https://github.com/01org/zephyr.js/blob/devel/samples/tests/BufferMemory.js)

**Comment by haoxli** [comment]
close this, move discussion to #343
