### ISSUE TITLE
linux: Unable to pipe stdout

### ISSUE THREAD

**Issue by gabrielschulhof** [01org/zephyr.js#330]
Given file `tmp.js`:

``` JS
setInterval( function() { print( "ABC" ); }, 1000 );
```

if you run `./jslinux ./tmp.js`, it will output as expected, however, if you run `./jslinux ./tmp.js | cat -` it doesn't output anything.

Does `jslinux` require a tty?

Context: I am trying to integrate `jslinux` with the [OCF test suite](https://github.com/01org/iot-js-api/tree/ocf-new-api/tests), which relies on launching a client/server pair which both transmit information about the progress of the test via JSON objects on stdout.

**Comment by gabrielschulhof** [comment]
The workaround, I think:
```
script -c './jslinux ./tmp.js' /dev/null
```

**Comment by gabrielschulhof** [comment]
Actually, I'd much rather not use that because it introduces a whole slew of complications. Is there a way of piping the output of jslinux?

**Comment by pfalcon** [comment]
I'd add that there're other issues with jslinux. For example, it "hangs" instead of terminating even for simple apps like `print("Hello World!")`. Perhaps that's a "faithful emulation" of an embedded system, which can't "quit" somewhere, but I guess it would make sense to make jslinux adhere to *nix command line convention instead (including piping, etc.)

**Comment by gabrielschulhof** [comment]
@pfalcon Yeah, but that's less of a concern for me. I can just output something that will cause the parent process to terminate it. OTOH, being unable to pipe the output to anywhere is hurting me badly.

**Comment by jprestwo** [comment]
@gabrielschulhof, printing (console.log or print) just use printf. Should it be using fprintf and print to stderr AND stdout? What solution do you suggest?

**Comment by gabrielschulhof** [comment]
@jprestwo The output given as Javascript's `print( "something" );` arrives at the terminal just fine if you run `./jslinux file-that-contains-the-print-something-statement.js`. However, if you redirect the output like so: `./jslinux file-that-contains-the-print-something-statement.js | grep "something"` then it doesn't output anything. This tells me that `./jslinux` expects the standard file descriptors to have pty capabilities. If stdout is a mere pipe, it will not print.

**Comment by gabrielschulhof** [comment]
@jprestwo thus, the binding of Javascript's `print()` works just fine, as long as `jslinux` runs in a terminal. The problem is that at some point in the execution of `jslinux` a decision is made not to output anything if the standard file descriptors do not have pty capabilities.

**Comment by gabrielschulhof** [comment]
Overall, I have found a seemingly reasonable workaround for running the OCF test suite with `jslinux`. There's a npm package called "pty.js", which provides a [`spawn()`](https://github.com/chjj/pty.js/#example-usage) function that behaves the same way as node's own [`spawn()`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options), but which runs the child process in a pty.

**Comment by grgustaf** [comment]
I do think we should solve the tty output problem and the hanging forever problem. We've talked elsewhere that we might be able to exit if there are no outstanding timers or events registered? Otherwise we could at least have a -t 5 timeout arg or something that would close the app after 5s? Or a flag that causes it to quit just because there are no timers defined. Something along these lines.

**Comment by grgustaf** [comment]
Another of our ideas was adding an "exit" API that we could add to our tests to make them exit after completion.

**Comment by jprestwo** [comment]
You should now be able to pipe stdout from jslinux using one of the new exit mechanisms. You can either pass in `--autoexit` for jslinux to automatically exit if it thinks there are no more events to process, or you can specify a timeout in milliseconds using `-t <ms>`.

@gabrielschulhof, could you confirm that this does what you needed for piping the output.

**Comment by jprestwo** [comment]
@gabrielschulhof, @grgustaf,

The Linux auto-exit feature will allow piped output. Can this be closed?

**Comment by qiaojingx** [comment]
Verified with commit b29dbbc.  `./jslinux` supports `--noexit` and `-t <ms>` parameters now.
`./jslinux samples/Timers.js | cat -` can get output log .

**Comment by jprestwo** [comment]
@grgustaf, @gabrielschulhof, @qiaojingx,

Can one of you close this.

**Comment by qiaojingx** [comment]
I have no permission to close issue reported by others.

**Comment by grgustaf** [comment]
Sorry, closing now...
