### ISSUE TITLE
[BLE] Add argument for ble.disconnect()

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#334]
With one client, the function ble.disconnect() and ble.disconnect(clientAddress) are perfectly working, but with two or more client, it is difference between ble.disconnect() and ble.disconnect(clientAddress).
The function ble.disconnect(clientAddress) is more directional. So, I suggest Adding argument and description for ble.disconnect().

**Comment by kenchris** [comment]
@zolkis ^

**Comment by grgustaf** [comment]
Can someone clarify the issue here? I'm not sure what priority to assign.

**Comment by cuiyanx** [comment]
fixed and closed
