### ISSUE TITLE
BLE notification bug on subscribe/unsubscribe

### ISSUE THREAD

**Issue by jimmy-huang** [01org/zephyr.js#349]
There's a bug currently in BLE that it immediately start sending notification to the client as soon as the client is connected, since before we couldn't detect which service the client subscribed to due to Zephyr bluetooth driver limitation, now Zephyr upstream added an extra param in their ccc_cfg_changed() callback, we should fix the BLE to monitor subscription/unsubscription on notifcation from the client, and only send update notification if they've subscribed.

**Comment by grgustaf** [comment]
@jimmy-huang, is this done?

**Comment by jimmy-huang** [comment]
submitted a fix here https://github.com/01org/zephyr.js/pull/528

**Comment by xiaolongx** [comment]
This issue should be fixed on Arduino 101 with commit 2345f96.
