### ISSUE TITLE
[BLE] Add support for 128bit UUIDs

### ISSUE THREAD

**Issue by jimmy-huang** [01org/zephyr.js#356]
Currently we only support 16bit UUID values, we'll also need to support 128bit UUID values in the spec.

**Comment by grgustaf** [comment]
This is a good example of one of those things not to do until we know we need it though. :)

**Comment by grgustaf** [comment]
I'm adding a new tag for this kind of thing "reconsider later" where I'll close it but we can review and reopen in the future.
