### ISSUE TITLE
Feature list for release 0.1

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#369]
Document the features assigned to 0.1 so that QA knows what to test and users know what they are getting. Features are github issues labeled with "feature" and assigned to milestone "0.1".

**Comment by baleboy** [comment]
Here is the initial list: https://github.com/01org/zephyr.js/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.1

**Comment by baleboy** [comment]
@grgustaf @poussa anything missing?

**Comment by grgustaf** [comment]
@baleboy It looks good to me but of course proving a negative is hard work. :)

**Comment by grgustaf** [comment]
Closing as the release is out.
