### ISSUE TITLE
Analog I/O (AIO) API

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#376]
API Spec: https://github.com/01org/zephyr.js/blob/master/docs/aio.md

**Comment by xiaolongx** [comment]
Basic feature is ready, verified with Samples: [AIO.js](https://github.com/01org/zephyr.js/blob/master/samples/AIO.js), [ReadAnalogVoltage.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/ReadAnalogVoltage.js), [AnalogReadSerial.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/AnalogReadSerial.js), [WebBluetoothDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/WebBluetoothDemo.js)
Commit: 2ff271b
Hardware: Arduino_101
