### ISSUE TITLE
General Purpose I/O (GPIO) API

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#377]
https://github.com/01org/zephyr.js/blob/master/docs/gpio.md

**Comment by xiaolongx** [comment]
Basic feature is ready, verified with Samples: 
GPIO input only: [DigitalReadSerial.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/DigitalReadSerial.js)
GPIO output only: [Blink.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/Blink.js), [RGB.js](https://github.com/01org/zephyr.js/blob/master/samples/RGB.js)
GPIO input/output: [AutoButton.js](https://github.com/01org/zephyr.js/blob/master/samples/AutoButton.js), [Button.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/digital/Button.js), [ButtonLEDs.js](https://github.com/01org/zephyr.js/blob/master/samples/ButtonLEDs.js), [TwoButtons.js](https://github.com/01org/zephyr.js/blob/master/samples/TwoButtons.js)
Using openAsync: [ButtonLEDsAsync.js](https://github.com/01org/zephyr.js/blob/master/samples/ButtonLEDsAsync.js)
Commit: 2ff271b
Hardware: Arduino_101
