### ISSUE TITLE
Pulse-Width Modulation (PWM) API

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#378]
https://github.com/01org/zephyr.js/blob/master/docs/pwm.md

**Comment by xiaolongx** [comment]
Basic feature is ready, verified with Samples: [PWM.js](https://github.com/01org/zephyr.js/blob/master/samples/PWM.js), [Fade.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/Fade.js), [WebBluetoothDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/WebBluetoothDemo.js)
Commit: 2ff271b
Hardware: Arduino_101
