### ISSUE TITLE
Bluetooth Low Energy (BLE) API

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#379]
https://github.com/01org/zephyr.js/blob/master/docs/ble.md

**Comment by xiaolongx** [comment]
Basic feature is ready, verified with Samples: [BLE.js](https://github.com/01org/zephyr.js/blob/master/samples/BLE.js), [WebBluetoothDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/WebBluetoothDemo.js), [WebBluetoothGroveLcdDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/WebBluetoothGroveLcdDemo.js), [HeartRateDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/HeartRateDemo.js)
Commit: 2ff271b
Hardware: Arduino_101
