### ISSUE TITLE
Grove LCD API

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#380]
https://github.com/01org/zephyr.js/blob/master/docs/grove_lcd.md

**Comment by xiaolongx** [comment]
Basic feature is ready, verified with Samples: 
Grove LCD only: [GroveLCD.js](https://github.com/01org/zephyr.js/blob/master/samples/GroveLCD.js)
Demos: [WebBluetoothGroveLcdDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/WebBluetoothGroveLcdDemo.js), [HeartRateDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/HeartRateDemo.js)
Commit: 2ff271b
Hardware: Arduino_101
