### ISSUE TITLE
Board support for Arduino 101

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#381]
https://github.com/01org/zephyr.js/blob/master/docs/a101_pins.md

**Comment by xiaolongx** [comment]
Basic feature is ready, verified with Samples: [TwoButtons.js](https://github.com/01org/zephyr.js/blob/master/samples/TwoButtons.js), [PWM.js](https://github.com/01org/zephyr.js/blob/master/samples/PWM.js), [AIO.js](https://github.com/01org/zephyr.js/blob/master/samples/AIO.js)
Commit: 2ff271b
Device: Arduino_101
