### ISSUE TITLE
Board support for FRDM-K64F

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#382]
https://github.com/01org/zephyr.js/blob/master/docs/k64f_pins.md

**Comment by xiaolongx** [comment]
Basic feature is ready, verified with Samples: [Blink-k64f.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/Blink-k64f.js), [ButtonLEDs-k64f.js](https://github.com/01org/zephyr.js/blob/master/samples/ButtonLEDs-k64f.js)
Commit: 2ff271b
Hardware: Frdm_k64f
