### ISSUE TITLE
Node.JS Buffer API

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#383]
https://github.com/01org/zephyr.js/blob/master/docs/buffer.md

**Comment by xiaolongx** [comment]
Basic feature is ready, verified with Samples: [Buffer.js](https://github.com/01org/zephyr.js/blob/master/samples/Buffer.js), [WebBluetoothDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/WebBluetoothDemo.js)
Commit: 2ff271b
Hardware: Arduino_101
