### ISSUE TITLE
Timers API

### ISSUE THREAD

**Issue by baleboy** [01org/zephyr.js#384]
https://github.com/01org/zephyr.js/blob/master/docs/timers.md

**Comment by xiaolongx** [comment]
Basic feature is ready, verified with Samples: [Timers.js](https://github.com/01org/zephyr.js/blob/master/samples/Timers.js), [Spaceship2.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/starterkit/Spaceship2.js)
Commit: 2ff271b
Hardware: Arduino_101
