### ISSUE TITLE
[I2C.js] One more "WORLD" displays on LCD after running 3-4 hours

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#397]
After running [I2C.js](https://github.com/01org/zephyr.js/blob/zjs-0.1/samples/I2C.js) 3-4 hours with commit [b1be3ba](https://github.com/01org/zephyr.js/commit/b1be3ba69cd5c53bdc69500d97529be9306af054) in zjs-0.1 branch, one more "HELLO" or "WORLD" displays on LCD screen, please refer to the attached images. 
Expect output: one "HELLO!" displays with orange in background, and one "WORLD!" displays with blue in background.

![image1](https://cloud.githubusercontent.com/assets/16217857/20132349/7e71e800-a69d-11e6-97da-e0067de439cc.jpg)
![image2](https://cloud.githubusercontent.com/assets/16217857/20132379/a7db80ca-a69d-11e6-9d00-cec467f9e528.jpg)

Branch | Build ID | Date | Result
---|---|---|---
zjs-0.1 | b1be3ba | Nov 9, 2016 | FAIL
zjs-0.2 | cd4e16a | Jan 12, 2017 | FAIL

**Comment by grgustaf** [comment]
Heh I just saw this same bug yesterday (except mine said HELLO!) and showed Brian. Basically what must be happening is that one out of thousands of I2C commands is getting dropped. It's hard to know whether that is in the Zephyr driver or hardware or just unavoidable. Seems doubtful that it could be in our code though.

**Comment by grgustaf** [comment]
(That is, the I2C command to move the cursor back to the beginning of the line is the one that gets dropped.)

**Comment by grgustaf** [comment]
I'll let Brian look into it. Not a high priority. :) But one thing we could do is try to estimate how often it happens 1/1000? 1/10k? Etc. By measuring the average time for the problem to occur. If we spit out a timestamp instead of the Hello and World then it might leave the evidence right on the LCD for us.

And then we'd want to approach Zephyr folks with the issue, probably by reproducing it in a native Zephyr app first.

**Comment by grgustaf** [comment]
@xiaolongx, had you ever tried this before? Two nights ago was the first time I'd ever left I2C.js running overnight, so I assumed the problem might have always been there.

**Comment by xiaolongx** [comment]
Yes, I tried in master branch(commit 2ff271b) for 6 hours, but cannot reproduce this issue, I will rerun again over night.

**Comment by brianjjones** [comment]
I think this is a case of, I need to check the return when I write to I2C.  If it fails try again rather than going forward.  Basically it fails to move the cursor back, and then writes the text anyway.

**Comment by brianjjones** [comment]
The fix for this has now been merged into master
https://github.com/01org/zephyr.js/pull/468

**Comment by grgustaf** [comment]
That's not a fix, that's masking over the problem. Guess that slipped in, I didn't intend to merge that. :)

**Comment by grgustaf** [comment]
I guess the difference is a bit subtle. In a product, sure you might do this to work around a bug. But we're enabling, we should be interested in monitoring and investigating the root cause of such a failure. So I would revert that part of the patch.

**Comment by grgustaf** [comment]
It's not clear whether the bug is in hardware or Zephyr, or a timing / race condition type thing in ZJS, but that's less likely.

**Comment by brianjjones** [comment]
It happens because a i2c_write call to zephyr fails.  Specifically the "shift cursor back to the beginning" write call.  The next word is then written at the end of the first, causing the double word.  The real fix would be to either a.) Have the I2C API be smart enough to try again if the write fails b.) Add a return value to the I2C API so that the javascript is aware it needs to try again.

**Comment by brianjjones** [comment]
This should be fixed by https://github.com/01org/zephyr.js/pull/525 which will offer a return value on writes.  This way the javascript can request a write again should it fail.

**Comment by grgustaf** [comment]
So you've actually been able to log that you do get a write failure reply from that function, once in a blue moon? It probably does make sense to have retry logic right in the API then. At least for just a single retry to cover flukes.

**Comment by xiaolongx** [comment]
This issue reproduce on Arduino 101 branch with commit cd4e16a(zjs-0.2 branch).

**Comment by qiaojingx** [comment]
This issue can not be reproduced after running over night on Arduino 101 branch with commit eafdfe9(zjs-0.2 branch).

**Comment by xiaolongx** [comment]
Closed since it is not reproducible.
