### ISSUE TITLE
[docs] Missing I2C index in API.md

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#404]
[I2C API](https://github.com/01org/zephyr.js/blob/zjs-0.1/docs/i2c.md) is a feature of release 0.1 following [Feature list for release 0.1](https://github.com/01org/zephyr.js/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.1), but missing the index in [API.md](https://github.com/01org/zephyr.js/blob/zjs-0.1/docs/API.md) in zjs-0.1 branch (commit [b1be3ba](https://github.com/01org/zephyr.js/commit/b1be3ba69cd5c53bdc69500d97529be9306af054)).

**Comment by grgustaf** [comment]
Fixed by PR #387 in commit b9f4c5d
