### ISSUE TITLE
[docs] Wrong link for Spaceship2.js in timer.md

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#405]
Wrong link for [Spaceship2.js](https://github.com/01org/zephyr.js/blob/zjs-0.1/arduino/starterkit/Spaceship2.js) in [timer.md](https://github.com/01org/zephyr.js/blob/zjs-0.1/docs/timers.md) in zjs-0.1 branch(commit b1be3ba)
The right path is: 
```
*  [Spaceship2 sample](../samples/arduino/starterkit/Spaceship2.js)
```

**Comment by grgustaf** [comment]
I cherry-picked your patch for this into the zjs-0.1 branch as commit a7a21b0.

**Comment by xiaolongx** [comment]
The link is updated on zje-0.1 branch, close
