### ISSUE TITLE
jslinux crashes with invalid filename argument

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#430]
With #429 it will at least give you a hint at why first. :)

**Comment by jprestwo** [comment]
Fixed with: https://github.com/01org/zephyr.js/pull/435

**Comment by jprestwo** [comment]
The fix is now in master. This can be closed.

**Comment by grgustaf** [comment]
Works for me, good for QA to see and verify though. I'll let them close it.

**Comment by xiaolongx** [comment]
QA verified this issue in commit 3254c5cc, no crashes with invalid filename argument.
The error log:
```
[ERROR] src/zjs_script.c:17 zjs_read_script(): error opening file
[ERROR] src/main.c:124 main(): could not read script file 111
```
