### ISSUE TITLE
The Readme.md need to be updated following commit 916cb71

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#433]
The samples for AIO, GroveLCD, I2C does not works following [README.md](https://github.com/01org/zephyr.js/blob/master/README.md). Such as AIO.js:

```
make arc
make dfu-arc
make JS=samples/AIO.js
make dfu
```
The command "make JS=" need to be replaced with "make all JS=" following commit 916cb71, and the new commands works fine.

```
make all JS=samples/AIO.js
make dfu-all
```

**Comment by jimmy-huang** [comment]
see #440

**Comment by xiaolongx** [comment]
README.md has been updated, close.
