### ISSUE TITLE
[install] getting started with linux

### ISSUE THREAD

**Issue by mulderp** [01org/zephyr.js#467]
just a quick check on a Linux Debian machine, I tried:

```
patrick@kiste:~/projects/zephyr.js$ source zjs-env.sh 
basename: invalid option -- 'z'
Try `basename --help' for more information.
ZJS_PARTITION: 144
ZJS_BASE: /home/patrick/projects/zephyr.js
patrick@kiste:~/projects/zephyr.js$ vi zjs-env.sh 
patrick@kiste:~/projects/zephyr.js$ ls
arc   fragments  Makefile.app        Makefile.ocf_zephyr  NOTICES    scripts  version
deps  LICENSE    Makefile.linux      Makefile.zephyr      README.md  src      zjs-env.sh
docs  Makefile   Makefile.ocf_linux  modules              samples    tests
patrick@kiste:~/projects/zephyr.js$ make
Makefile:30: *** ZEPHYR_BASE not set. Source deps/zephyr/zephyr-env.sh.  Stop.

```

it is unclear what build system is used and what paths should be set to use it.

**Comment by jprestwo** [comment]
Just running `make` will build the Zephyr target by default. If you want to build for linux you need to run `make linux`. 

If you do want to build for Zephyr though, you need to set `ZEPHYR_BASE` like the error message says e.g.
```
export ZEPHYR_BASE=/path/to/zephyr/repo
```
or you can source the `zephyr-env.sh` file which is located in the Zephyr repository.

**Comment by mulderp** [comment]
thanks - this is exactly what i needed to get started
