### ISSUE TITLE
[OCF] "Imprecise data bus error" occurs when running OcfClientUpdate.js on FRDM-K64F

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#469]
Flashing [OcfClientUpdate.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClientUpdate.js), and then rebooting frdm_k64f, "Imprecise data bus error" occurs.

OcfClientUpdate.js on FRDM_K64F:
```
net: net_driver_slip_open (0x2000f804): Initialized slip driver
oc_main: Stack successfully initialized
Started OCF client
Outgoing message to: [ff02:0000:0000:0000:0000:0000:0000:0158]:5683:5683
***** BUS FAULT *****
  Executing thread ID (thread): 0x2000f804
  Faulting instruction address:  0x00029dfa
  Precise data bus error
  Address: 0x2008462c
Fatal fault in thread! Aborting.
***** HARD FAULT *****
  Fault escalation (see below)
***** BUS FAULT *****
  Executing thread ID (thread): 0x2000f804
  Faulting instruction address:  0x2000fe64
  Precise data bus error
  Address: 0x2008462c
Fatal fault in ISR! Spinning...
```
OcfClientUpdate.js on jslinux:
```
oc_main: Stack successfully initialized
Started OCF client
Outgoing message to [ff02:0000:0000:0000:0000:0000:0000:0158]:5683
Sent 51 bytes
Incoming message from [fe80:0000:0000:0000:3e87:0fd3:d329:7c8d]:42550
```

Branch | Build ID | Date | Result |
---|---|---|---
master | 6037375 | Nov 23,2016 | FAIL
master | e0d4559 | Nov 23,2016 | FAIL

**Comment by grgustaf** [comment]
I'm not sure OCF is really "done" and ready for testing yet, but I'll let @jprestwo comment.

**Comment by jprestwo** [comment]
@grgustaf is correct, I am not even able to run the iotivity-constrained samples on the K64F board without running into errors. We should leave this open, but I think the problem has something to do with iotivity-constrained rather than how we are using it. Iotivity-constrained has also not been updated to the unified kernel, so I am waiting on that before trying to work around these issues.

**Comment by jprestwo** [comment]
@xiaolongx, I don't see this behavior on master, could we check and see if this is relevant anymore.

**Comment by xiaolongx** [comment]
Closed
