### ISSUE TITLE
get memory stats working again and think about how to automate it

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#472]
Today, Brian and I discussed how it would be nice if we could have an automated check that would report the size of RAM and ROM usage by each new build and maybe either fail a check if it grows by too much or at least report the difference.

He tried running memorystats script and found that it has been broken, so that needs to be fixed first probably. If not the above solution, then maybe we run something on our own to alert IRC when things have grown excessively.

**Comment by brianjjones** [comment]
The fix for this has now been merged into the master branch.

**Comment by grgustaf** [comment]
Confirmed, worksforme. Closing.
