### ISSUE TITLE
[docs] read and burstRead methods missing in I2C Web IDL

### ISSUE THREAD

**Issue by haoxli** [01org/zephyr.js#475]
There are **read** and **burstRead** methods in [I2C API](https://github.com/01org/zephyr.js/blob/master/docs/i2c.md), but not defined in Web IDL:
```void read(octet device, unsigned int size, octet registerAddress);```
```void burstRead(octet device, unsigned int size, octet registerAddress);```

And I think the read method should return a value, shouldn't be a void method.

**Comment by brianjjones** [comment]
Fixed with https://github.com/01org/zephyr.js/pull/583

**Comment by xiaolongx** [comment]
Add read and burstRead methods in [i2c.md](https://github.com/01org/zephyr.js/blob/master/docs/i2c.md)     with commit #583
