### ISSUE TITLE
convert.sh doesn't like % in comments in PWM.js

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#490]
This is on line 82 of convert.sh. Probably it could be changed to:

```bash
echo -n $CHAR >> $OUTPUT
```

Also, it looks like below there's a `printf "\n"` that should probably be removed? It's not being echoed to the file, where it doesn't belong anyway AFAICT.

**Comment by jprestwo** [comment]
@grgustaf, what is the results of running convert.sh normally? It seems convert and run the JS fine for me. The printf for the newline was put there for some reason, but I cant seem to remember why. I think it was for adding a new line after we write the percentage out, essentially a aesthetic thing.

**Comment by grgustaf** [comment]
@jprestwo, just run "convert.sh samples/PWM.js out" and I think you will see the complaint in the first few lines of output, like I do.

Anyway, I just submitted a PR and you can review that.

**Comment by grgustaf** [comment]
PR  #502 fixes this.
