### ISSUE TITLE
[Sensor] Fail to get the rotation value in long-lasting test

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#505]
Flashing [Gyroscope.js](https://github.com/01org/zephyr.js/blob/master/samples/Gyroscope.js) with commit a162db1 and reboot the arduino 101, it works fine firstly, but fail to get the rotation value after 2-20 mins, and also stop output serial logs.

**Comment by jimmy-huang** [comment]
filed a bug on Zephyr https://jira.zephyrproject.org/browse/ZEP-1421

**Comment by xiaolongx** [comment]
This issue cannot reproduce on Arduino 101 with commit e0d4559, close
