### ISSUE TITLE
[REG][PWM] Fail to fades an LED in and out using PWM

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#515]
Flashing [Fade.js](https://github.com/01org/zephyr.js/blob/master/samples/arduino/basics/Fade.js) on Arduino 101 with commit a162db1, the LED do not shine. It seems `setPulseWidthCycles` does not work, and this issue also occurs in [test-pwm.js](https://github.com/01org/zephyr.js/blob/master/tests/test-pwm.js).

Branch | Target Device | Build ID | Date | Reult
---|---|---|---|---
master | Arduino 101 | 5844f9f | Dec 7, 2016 | PASS
master | Arduino 101 | a162db1 | Dec 7, 2016 | FAIL

**Comment by grgustaf** [comment]
This should be fixed by #571.

**Comment by xiaolongx** [comment]
This issue cannot reproduce on Arduino 101 with commit e034d5c, close
