### ISSUE TITLE
[uart] Error thrown when set UART device as "tty1"

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#534]
UART API docs:

> ##  UART.init
> void init(UARTOptions options);
> The options object lets you choose the UART device/port you would like to initialize. This can either be "tty0" or "tty1".

but when set UART device as "tty1", throw out error:
`UART.init({ port: "tty1", baud: 115200 })`

**Comment by jprestwo** [comment]
This is a case of bad documentation. At one point you could specify `tty0` or `tty1`, which would correspond to `UART_0` or `UART_1` devices, BUT the `UART_1` device (though a valid Zephyr device) did not result in any UART data read or writable that I could tell, so it was removed. The PR https://github.com/01org/zephyr.js/pull/540 changes the documentation to only mention `tty0`
