### ISSUE TITLE
[REG] No background color when running I2C.js on Arduino 101

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#557]
No background color in GroveLCD screen when running [I2C.js](https://github.com/01org/zephyr.js/blob/master/samples/I2C.js) on Arduino 101, but works well on FRDM-K64F.

Branch | Target Device | Build ID | Date | Result
---|---|---|---|---
master | FRDM-K64F | 5a25755 | Dec 19, 2016 | PASS
master | Arduino 101 | 5a25755 | Dec 19, 2016 | FAIL
master | Arduino 101 | 31c3908 | Dec 19, 2016 | PASS

**Comment by brianjjones** [comment]
I created a PR to fix this https://github.com/01org/zephyr.js/pull/565

**Comment by xiaolongx** [comment]
This issue cannot reproduce on both Arduino 101 and FRDM-K64F with commit e0d4559, close
