### ISSUE TITLE
Add API documentation for promises and events

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#559]
These are a bit different from the other "APIs" but we really need our own documentation since our implementation doesn't exactly match any other one out there, I think.

**Comment by jprestwo** [comment]
I have added Event documentation with https://github.com/01org/zephyr.js/pull/570. Promises have no actual JavaScript API's with the current implementation i.e. you cannot do:

```
var promise = new Promise(function() { . . . });
```

I would eventually like to add this functionality, but for the 0.2 release there is not enough time. But the above PR takes care of the Event portion of this issue.

**Comment by grgustaf** [comment]
Fixed, closing.
