### ISSUE TITLE
Fail to output long string properly via minicom

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#580]
When running [samples/tests/Console.js](https://github.com/01org/zephyr.js/blob/master/samples/tests/Console.js) on FRDM-K64F, the long string can not be displayed properly via command `minicom -D /dev/ttyACM0`, but works well via command `screen /dev/ttyACM0 115200`
Source Code:
```
console.log("\nTesting a long string...");
var longstr =
    "123456789012345678901234567890123456789012345678901234567890" +
    "123456789012345678901234567890123456789012345678901234567890" +
    "123456789012345678901234567890123456789012345678901234567890" +
    "123456789012345678901234567890123456789012345678901234567890" +
    "123456789012345";  // length 255
console.log(longstr);
```
Expect Result:
```
Testing a long string...
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345
```
Actual Result:
```
Testing a long string...
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345675
```

**Comment by grgustaf** [comment]
Did this work on older builds on K64F?

**Comment by xiaolongx** [comment]
It also did not work on older commit, I have updated the issue, it should be related with minicom command line.

**Comment by xiaolongx** [comment]
The same issue is reproduce on Arduino 101 with commit 3f8eb85. Update the title.

**Comment by grgustaf** [comment]
I forgot to comment here, but I tested this and it worked for me a few days ago on k64f.

**Comment by grgustaf** [comment]
Verified again just now with master. Please retest.

**Comment by grgustaf** [comment]
Note: It's 255 characters, so it results in 3 80-char lines of output plus fifteen characters on the fourth line: 3*80+15 == 240 + 15 == 255.

Just in case was confusing someone because there are 4+1 lines in the source (4*60+15 == 255)

**Comment by qiaojingx** [comment]
Verify with commit cc2311a on arduino 101 and FRDM-K64F. This issue is not reproducible. Closed.
