### ISSUE TITLE
[doc] Wrong links under Initial Setup documentation for windows and osx users

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#601]
Wrong links under [Initial Setup](https://github.com/01org/zephyr.js/blob/master/README.md#initial-setup) for Windows and OSX users in [Readme.md](https://github.com/01org/zephyr.js/blob/master/README.md): `Getting Started`, `Windows`, `OSX`

Branch |  Build ID | Date | Result
---|---|---|---
master | c707669 | Jan 16, 2017 | FAIL
zjs-0.2 | cd4e16a | Jan 16, 2017 | FAIL

**Comment by qiaojingx** [comment]
This issue is not reproducible with commit b022a4b.
