### ISSUE TITLE
OCF API

### ISSUE THREAD

**Issue by poussa** [01org/zephyr.js#605]
Based on the spec:
https://github.com/01org/iot-js-api/tree/master/api/ocf

**Comment by qiaojingx** [comment]
Basic feature of ocf is ready. Verified result as below:

A101/Linux with OcfServer | Linux with OcfClient | Known issues
---|---|---
[OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js) | [OcfClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClient.js)/[OcfClientUpdate.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClientUpdate.js) | #872 
[OcfNotifyServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfNotifyServer.js) | [OcfPlatformInfo.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfPlatformInfo.js)/[OcfDeviceInfo.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfDeviceInfo.js) |
[OcfSensorServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorServer.js) | [OcfClient.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfClient.js) | #872, #810 

Commit ID a6c321a + patch #871
