### ISSUE TITLE
[console] Not support placeholders for Console APIs

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#621]
Set "%d" for number and "%s" for string, there are not work.

Code : 
```
var arg1 = 1024;
console.log("console.log: %d", arg1);
var arg2 = "My love!";
console.log("console.log: %s", arg2);
```

**Comment by grgustaf** [comment]
I don't think it makes sense for us to implement support for this, unless it's already present in JerryScript or something and we can reuse it. So probably @jprestwo you can resolve this by specifying in the documentation that format specifiers are not supported. This was a surprise to me, I never knew this existed. :) But it's there in both Node and e.g. Chrome.

**Comment by jprestwo** [comment]
Docs added with: https://github.com/01org/zephyr.js/pull/787

**Comment by cuiyanx** [comment]
OK，thanks and closed.
