### ISSUE TITLE
[console] Throw out wrong error

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#623]
Set timer name as "", throw out wrong error.

Code:
```
var Timer = "";
console.time(Timer);
console.timeEnd(Timer);
```
Error:
```
src/zjs_console.c:223 console_time_end():
[ERROR] string is too long
```

**Comment by grgustaf** [comment]
This is probably fixed by my PR #618

**Comment by grgustaf** [comment]
Now it will actually work with any empty string label, no error.

**Comment by cuiyanx** [comment]
Yes, it is no error throwing out, but it will be hung. And when I build this, throw out a 'warn'. Please check this.

**Comment by cuiyanx** [comment]
fixed and closed
