### ISSUE TITLE
[I2C] No words output on Grove LCD on FRDM-K64F

### ISSUE THREAD

**Issue by xiaoyu3x** [01org/zephyr.js#642]
Flashing [I2C.js](https://github.com/01org/zephyr.js/blob/master/samples/I2C.js) on FRDM_K64F with commit 5352200, No words output on Grove LCD, this issue may caused by commit f9c0909 and also affect [test-i2c.js](https://github.com/01org/zephyr.js/blob/master/tests/test-i2c.js)

Branch | Target Device | Build ID | Date | Result
---|---|---|---|---
master | FRDM-K64F | c707669 | Jan 22,2017 | PASS
master | FRDM-K64F | f9c0909 | Jan 22,2017 | FAIL
master | FRDM-K64F | 5352200 | Jan 22,2017 | FAIL

**Comment by qiaojingx** [comment]
Verified with commit b29dbbc. This issue is not reproducible.
