### ISSUE TITLE
OCF: device and platform object implementation is missing

### ISSUE THREAD

**Issue by poussa** [01org/zephyr.js#668]
https://github.com/01org/iot-js-api/tree/master/api/ocf#ocfdevice
https://github.com/01org/iot-js-api/blob/master/api/ocf#the-ocfplatform-object

We need to be able to set these two objects from the JS app.

**Comment by jprestwo** [comment]
@poussa,

These are now present and settable in the JS app (master). The one requirement is that you fill out the objects before you call registerResource(). I have an example in OcfServer.js.

**Comment by jprestwo** [comment]
@poussa,

Can we close this? Master now has device and platform objects.
