### ISSUE TITLE
[REG] Fail to build Grove LCD sample on FRDM-K64F

### ISSUE THREAD

**Issue by xiaolongx** [01org/zephyr.js#675]
Fail to build [GroveLCD.js](https://github.com/01org/zephyr.js/blob/master/samples/GroveLCD.js), [test-grovelcd.js](https://github.com/01org/zephyr.js/blob/master/tests/test-grovelcd.js) on FRDM-K64F, but works well on Arduino 101, this issue occurs after commit a5fda85 merged.

Error Logs:
```
collect2: error: ld returned 1 exit status
/home/xiaolong/00_xiaolong/ZJS/ww05/zephyr.js/deps/zephyr/Makefile:852: recipe for target 'zephyr_prebuilt.elf' failed
make[3]: *** [zephyr_prebuilt.elf] Error 1
make[3]: Leaving directory '/home/xiaolong/00_xiaolong/ZJS/ww05/zephyr.js/arc/outdir/arduino_101_sss'
Makefile:175: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
make[2]: Leaving directory '/home/xiaolong/00_xiaolong/ZJS/ww05/zephyr.js/deps/zephyr'
/home/xiaolong/00_xiaolong/ZJS/ww05/zephyr.js/deps/zephyr/Makefile.inc:82: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/xiaolong/00_xiaolong/ZJS/ww05/zephyr.js/arc'
Makefile:238: recipe for target 'arc' failed
make: *** [arc] Error 2
```

Branch | Target Device | Commit ID | Date | Result
---|---|---|---|---
master | Arduino 101 | 21915c0 | Feb 6, 2017 | PASS
master | FRDM-K64F | 21915c0 | Feb 6, 2017 | FAIL
master | FRDM-K64F | a5fda85 | Feb 6, 2017 | FAIL
master | FRDM-K64F | 5352200 | Jan 23, 2017 | FAIL

**Comment by qiaojingx** [comment]
This issue is not reproduced on FRDM-K64F with commit 3f8eb85.
