### ISSUE TITLE
[Docs] Wrong links in ble.md and README.md files

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#684]
1. For master and zjs-0.2 branch, the anchor of Client Requirements in [ble.md](https://github.com/01org/zephyr.js/blob/master/docs/ble.md). The right link address should be #client-requirements, not #requirements. 
2. For zjs-0.2 branch, wrong links under [Initial Setup](https://github.com/01org/zephyr.js/blob/master/README.md#initial-setup) for Add udev rules in [Readme.md](https://github.com/01org/zephyr.js/blob/master/README.md):  [99-openocd.rules](https://raw.githubusercontent.com/arduino/OpenOCD/master/contrib/99-openocd.rules) (from this [Arduino github project](https://github.com/arduino/OpenOCD/blob/master/contrib/99-openocd.rules))
99-opencd.rules is not found.

Branch|Build ID|Date|Result
---|---|---|---
master|[eefc65f](https://github.com/01org/zephyr.js/commit/eefc65f8df870648b86650513fdf787f5b08b7f2)|Feb 7, 2017|FAIL
zjs-0.2|[eafdfe9](https://github.com/01org/zephyr.js/commit/eafdfe9e3f239e79e006fa7e2832eb4df5ba8305)|Feb 7, 2017|FAIL

**Comment by jimmy-huang** [comment]
submitted #831 and #832 to fix these.

**Comment by qiaojingx** [comment]
Verified with commit 8a2964e in master and commit 876b00f in zjs-0.2. This issue has been fixed.
Closed
