### ISSUE TITLE
DEBUG build is broken

### ISSUE THREAD

**Issue by poussa** [01org/zephyr.js#685]
`make VARIANT=debug`

/home/spoussa/src/iot/zephyr.js/outdir/snapshot/debug/src/zjs_common.c:29:8: error: unknown type name ‘uint8_t’
 static uint8_t init = 0;

**Comment by poussa** [comment]
Can we add debug build to travis so we catch these?

**Comment by grgustaf** [comment]
I found that commit 10086db introduced the problem. Also you won't see it if you've already built succesfully but can reproduce it again after `make pristine`.

**Comment by jimmy-huang** [comment]
submitted patch #697

**Comment by grgustaf** [comment]
Just posted PR #707 which has started doing a test build with VARIANT=debug in Travis. This simple sanity check does seem like a good idea; I looked at running it against other modules and I think the surface area is too small to be worth the penalty for slowing down Travis all the time.

I also added a bunch of new tests though, for RAM=, SNAPSHOT=off, sensors, etc. so we have better coverage now.

**Comment by poussa** [comment]
Works.
