### ISSUE TITLE
[ashell] IO10~IO13 are failed as output pins by zephyrJS IDE

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#727]
When run test/test-a101-pins.js by zephyr.js IDE, IO10~IO13 are failed as output pins. but they are passed by zephyr JS on a101.

**Comment by grgustaf** [comment]
I believe this is inevitable because those pins are being used for SPI to talk to the flash filesystem. However, we do need to document that better. AFAIK in ashell mode those will never be available.

**Comment by cuiyanx** [comment]
OK, thanks and closed.

**Comment by cuiyanx** [comment]
@grgustaf Please update [/docs/ashell.md](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md) to clarify

**Comment by brianjjones** [comment]
This is invalid since ashell requires SPI in order to work, its needed for filesystem.  If you enable SPI, then pins I010 - IO13 become SPI pins, and no longer function as GPIO.  You will see the same thing happen if you were to add require("spi") to you JS and build without ashell.

**Comment by cuiyanx** [comment]
Fixed and closed
