### ISSUE TITLE
snapshot build hides minify errors

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#729]
One of the few ways we give the user decent JS error feedback is with minify for parse errors. But this output is hidden in snapshot mode. Perhaps snapshot doesn't do minify since it doesn't really need to? But in order to give this good feedback to the user we should still do it.

**Comment by jimmy-huang** [comment]
This is fixed by pr #734

**Comment by grgustaf** [comment]
Verified, closing.
