### ISSUE TITLE
[ashell] "set transfer ihex/raw" is not working as expected

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#762]
### Description
"set transfer ihex/raw" is not working as expected
 
### Test Code
[ashell.md](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md)
 
### Steps to Reproduction
1. Set 'CONFIG_USB_CDC_ACM=y' in fragments/prj.conf.arduino_101_dev to enable USB CDC ACM device class driver.
2. Execute "make DEV=ashell" in the latest zephyrJS build
3. Execute "make dfu" to flash ashell to Arduino101 and Reset device
4. Use the following command to connect to the ashell from a terminal `$  screen /dev/ttyACM0 115200`
5. Input `acm> set transfer raw` and Enter
6. Input `acm> set transfer ihex` and Enter
### Actual Result
After 4. 
![selection_002](https://cloud.githubusercontent.com/assets/19813546/23298423/93e34804-fab8-11e6-9db1-102b759dee1b.png)

After 5.
![selection_001](https://cloud.githubusercontent.com/assets/19813546/23298429/9df45f4a-fab8-11e6-9c41-14583be12b7d.png)
 

### Expected Result
After 4. Transfer to RAW. 
acm> set transfer raw
RAW>

After 5. Transfer to IHEX. 
acm> set transfer ihex
HEX>

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 2e8c582| Arduino 101 | Feb 13, 2017 | Fail
 
### Additional Information

Test ashell with zephyrIDE, this issue is also reproduced.But nothing was returned after executing `set transfer ihex`.
![selection_003](https://cloud.githubusercontent.com/assets/19813546/23298726/bba73872-fab9-11e6-9721-c92ea182d319.png)

**Comment by xiaoyu3x** [comment]
hi, @qiaojingx 
According to latest [ashell](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md#commands) doc, 'set transfer raw' and 'set transfer ihex' cmd have been removed, so closed it please.

**Comment by qiaojingx** [comment]
Close since this command has been removed from [ashell.md](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md).
