### ISSUE TITLE
[ocf] Can not find /a/light resource

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#764]
### Issue Description

I am following the instructions on [ocf-ble.md](https://github.com/01org/zephyr.js/blob/master/docs/ocf-ble.md) to build OCF Server and Client. I have got some error message and can not find `/a/light `resource.

### Test Code

[samples/OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js)

### Steps to Reproduction

1. Build [samples/OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js) on a101 as OCF Server.
Command:  `make BOARD=arduino_101 JS=samples/OcfServer.js`.
2. Connect a101 to Ubuntu 16.04.
3. Build [iot-rest-api-server](https://github.com/01org/iot-rest-api-server) as OCF Client.
4. Find resource with `./oic-get /res`.

### Actual Result

Can not find `/a/light` resource

### Expected Result

Find `/a/light` resource

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 7c5ff3c1 | Arduino 101 | Feb 25, 2017 | Fail

### Additional Information

![selection_001](https://cloud.githubusercontent.com/assets/22387607/23349862/46b5cfd0-fcf1-11e6-995d-3ef75da96bb1.png)
![selection_002](https://cloud.githubusercontent.com/assets/22387607/23349865/4b032344-fcf1-11e6-8bea-2403b5aa82c3.png)
![selection_003](https://cloud.githubusercontent.com/assets/22387607/23349868/50a42da2-fcf1-11e6-8a3a-72a894308687.png)
![selection_004](https://cloud.githubusercontent.com/assets/22387607/23349869/53dfe380-fcf1-11e6-81bd-2b7ae57dbf3b.png)

**Comment by jprestwo** [comment]
@cuiyanx,

I have seen this behavior before. It always seems to be related to the 6lowpan Linux driver (or so we guess). I just tried on master and everything worked as expected. Sometimes the Linux box can get into a bad state, and the only way to fix it is to reboot or remove the 6lowpan driver and start the BLE connection steps over again. If you could try again with a fresh reboot that would be great.

**Comment by cuiyanx** [comment]
@jprestwo thanks for your answer.

I build OCF module following those steps:
```
$ git clone https://gerrit.zephyrproject.org/r/zephyr zephyr-project
$ cd zephyr-project
$ source zephyr-env.sh
$ cd samples/bluetooth/hci_uart
$ make BOARD=arduino_101_ble
$ dfu-util -a ble_core -D outdir/arduino_101_ble/zephyr.bin
```
here: [update BT firmware](https://www.zephyrproject.org/doc/boards/x86/arduino_101/doc/board.html#arduino-101)
