### ISSUE TITLE
[ashell] Cannot import custom module

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#782]
### Description

 Cannot import custom module in ashell

### Test Code

[I2CBMP280.js](https://github.com/01org/zephyr.js/blob/master/samples/I2CBMP280.js); [test-event.js](https://github.com/01org/zephyr.js/blob/master/tests/test-event.js); [test-accelerometer.js](https://github.com/01org/zephyr.js/blob/master/tests/test-accelerometer.js); [test-ambientlight.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ambientlight.js); [test-gyroscope.js](https://github.com/01org/zephyr.js/blob/master/tests/test-gyroscope.js)

### Steps to Reproduction

1. Set 'CONFIG_USB_CDC_ACM=y' in fragments/prj.conf.arduino_101_dev to enable USB CDC ACM device class driver.
2. Execute "make DEV=ashell" in the latest zephyrJS build
3. Execute "make dfu" to flash ashell to Arduino101 and Reset device
4. Use the following command to connect to the ashell from a terminal $ screen /dev/ttyACM0 115200
5. Input `acm> load test.js` and Enter
6. Input `RAW> /*Paste code for test cases*/ `and CTRL+Z to finish transfer
7. Input `acm> run test.js`

### Actual Result

After 7: Got error prompt: `NotSupportedError: native_require_handler: module not found` 
![selection_006](https://cloud.githubusercontent.com/assets/19813546/23490248/56a37a12-ff32-11e6-8589-536b745db393.png)
### Expected Result

After 7: Test case is executed successfully.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 06004c9| Arduino 101 | Mar 02, 2017 | Fail
zjs-0.3 | 33d88b0 | Arduino 101 | Apr 25, 2017 | Fail
 
### Additional Information

This issue is also reproduced when connected with zephyrIDE
![selection_007](https://cloud.githubusercontent.com/assets/19813546/23490334/05af6ce6-ff33-11e6-9a30-9871df939014.png)

**Comment by grgustaf** [comment]
@brianjjones, did this ever work? I did change the error to "NotSupportedError" recently but that shouldn't have affected functionality, I hope.

**Comment by brianjjones** [comment]
@grgustaf This has never worked as it is the job of analyzer.sh to append the required JS files.  Since ashell doesn't give analyzer.sh a JS file to look at during build time, this won't work at the moment.  I'll need to do some thinking on how this could be supported in ashell.

**Comment by jprestwo** [comment]
The only way to do something like this would be to have an "add module" command. And even then we would have to completely re-do our module system to dynamically add in modules, since they are all just appended to the same script currently.

**Comment by brianjjones** [comment]
I will work on adding a 'save' button to the IDE, which in turn will allow you to save a module to your file system.  Ashell when running a script will then need to search for any 'require' lines and check if those files are present on the file system, and if so append them to the javascript it intends to parse and run.

**Comment by brianjjones** [comment]
@grgustaf I would suggest taking this one off 0.3.  I might have it done by then, but there is a high likelihood of unintended consequences.

**Comment by brianjjones** [comment]
Alright I got this working, you can see the PR here https://github.com/01org/zephyr.js/pull/959

Feedback welcome!

**Comment by qiaojingx** [comment]
Will verify it after pr merged.

**Comment by qiaojingx** [comment]
Verification steps:
1. Download [Assert.js](https://github.com/01org/zephyr.js/blob/master/modules/Assert.js) module from GitHub in WebIDE. (https://01org.github.io/zephyrjs-ide/#/editor)
2. Save [Assert.js](https://github.com/01org/zephyr.js/blob/master/modules/Assert.js) module.
3. Download [test-buffer.js](https://github.com/01org/zephyr.js/blob/master/tests/test-buffer.js) from GitHub
4. Connect A101 to test-buffer.js tab.
5. Run.

Result:
Hangs issue occurred. No other error thrown.
Platform: Arduino 101 with commit 47e8aef.
               WebIDE version: v0.13.0-alpha / c60c538
![module_import](https://cloud.githubusercontent.com/assets/19813546/25123706/eea6be70-245b-11e7-9a1a-1251eab5e061.PNG)

**Comment by brianjjones** [comment]
If you are using the 'save' button on the IDE, that won't work.  Currently that just saves Assert.js to local storage on your browser.  You need to save Assert.js to the filesystem on the arduino 101.  There is not a clean, easy way to do this yet.  But here's the steps to do it, sorry it's ugly.

In the console type:
load assert.js
* Now paste your code in the window. I use the middle mouse button click to do this since right click and ctrl+v don't work *
* Press ctrl+z to save the file

Now run your test and it should find assert.js.  Please let me know if you have further issues.

**Comment by qiaojingx** [comment]
@brianjjones , assert.js module can be imported by following your steps. But it only works when running samples first time. If run again, error occurs, Please refer to the screen shot.
test-buffer.js
![selection_037](https://cloud.githubusercontent.com/assets/19813546/25258754/28b2d3c8-2674-11e7-9d73-67ed29fe6c00.png)
test-event.js
![selection_038](https://cloud.githubusercontent.com/assets/19813546/25258837/d4c86538-2674-11e7-8eb0-7c47e2f59d83.png)

Platform: Arduino101
Zephyr.js:98a3ce2
Samples: [test-buffer.js](https://github.com/01org/zephyr.js/blob/master/tests/test-buffer.js); [test-event.js](https://github.com/01org/zephyr.js/blob/master/tests/test-event.js)
Module: [Assert.js](https://github.com/01org/zephyr.js/blob/master/modules/Assert.js)

**Comment by haoxli** [comment]
@brianjjones Do you have plan to fix this issue in 0.3 release? or left it as a 0.3 know issue.

**Comment by qiaojingx** [comment]
Verified with the latest commit(93d58fa) in master. The issue which mentioned in my previous comment is not reproducible.

**Comment by brianjjones** [comment]
@haoxli Unless @grgustaf wants it back ported, it won't be in the 0.3 release.

@qiaojingx Yes I put in a fix for this and it was merged into master, good to see it worked.

**Comment by qiaojingx** [comment]
Verified with commit af7eadd in master. JS modules can be required in ashell and WebIDE. Closed
