### ISSUE TITLE
[ashell] Not enough memory if run a large size JS file.

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#783]
### Description

 Not enough memory if run a large size JS file.

### Test Code

[HeartRateDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/HeartRateDemo.js); [test-grovelcd.js](https://github.com/01org/zephyr.js/blob/master/tests/test-grovelcd.js)
 
### Steps to Reproduction

1. Set 'CONFIG_USB_CDC_ACM=y' in fragments/prj.conf.arduino_101_dev to enable USB CDC ACM device class driver.
2. Execute "make DEV=ashell" in the latest zephyrJS build
3. Execute "make dfu" to flash ashell to Arduino101 and Reset device
4. Use the following command to connect to the ashell from a terminal $ screen /dev/ttyACM0 115200
5. `acm> load test.js` and Enter
6. `RAW> /*Paste code for test cases*/ `and CTRL+Z to finish transfer
7. `acm> run test.js`
8. `acm> run test.js` again after reset device.

### Actual Result

After 6: Can't paste the whole test code one time. It will stuck
After 7: Not enough memory issue occur.
![selection_011](https://cloud.githubusercontent.com/assets/19813546/23496918/b129e6aa-ff5b-11e6-9131-30dadca3fdcd.png)
After 8: Test case will  be executed successfully.

### Expected Result

After 6: Long code can be pasted one time.
After 7: A large size JS file can always be executed successfully. No memory issue occur.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 06004c9 | Arduino 101 | Mar 2, 2017 | Fail
 
### Additional Information

It will hang if test with zephyr IDE connected.
![selection_010](https://cloud.githubusercontent.com/assets/19813546/23497646/2040e158-ff5f-11e6-9c0a-83593c647ead.png)

**Comment by grgustaf** [comment]
Well, there will always be some size where it's too big, so #7 isn't completely valid. But it is interesting that it works after reboot. That implies maybe something isn't getting completely freed, so worth looking into.

The code paste size is a separate issue. I think the right solution to that is maybe to use kermit / sz (zmodem) type stuff to send files over serial connection. Cut and paste is pretty clumsy, and no error checking.

Both issues are worth investigating.

**Comment by brianjjones** [comment]
Out of curiosity, how many lines was the file that was too big?

**Comment by grgustaf** [comment]
@brianjjones, it looked like maybe they were using HeartRateDemo.js and test-grovelcd.js? Did you try those?

**Comment by brianjjones** [comment]
@grgustaf Upping the RAM=72 ROM=272 works for me, I can fit both of those.  There are certainly things we can do to shrink the amount of memory needed for transfers, but I think this is better addressed by the new protocol task.  Should we close this one?

**Comment by grgustaf** [comment]
@brianjjones I bet with the new malloc patch, this would work even w/o the RAM=72? Could you try that?

**Comment by brianjjones** [comment]
@grgustaf  Afraid it still requires the RAM be set higher to work.

**Comment by qiaojingx** [comment]
Verified with latest commit cbe7e8f in master, this issue is not reproduced.
Close.
