### ISSUE TITLE
[promise] Import test_promise module failed

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#796]
### Description

Import test_promise module failed on Arduino 101 and FRDM-K64F. Not reproduced on Linux.
### Test Code

[test-promise.js](https://github.com/01org/zephyr.js/blob/master/tests/test-promise.js); [test-promise-stress.js](https://github.com/01org/zephyr.js/blob/master/tests/stress/test-promise-stress.js)
 
### Steps to Reproduction

1. `$ make JS=tests/test-promise.js`
2. `$ make dfu`
3. Reset device.
 
### Actual Result

![test-promises](https://cloud.githubusercontent.com/assets/19813546/23648526/12f73f92-0356-11e7-8833-e1239c70fd92.png)

 ### Expected Result

Test case should be executed successfully. No error thrown. 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | b29dbbc | Arduino 101 | Mar 7, 2017 | Fail
master | b29dbbc | FRDM-K64F | Mar 7, 2017 | Fail
master | b29dbbc | Linux | Mar 7, 2017 | Pass

**Comment by jprestwo** [comment]
Fixed with #963

**Comment by qiaojingx** [comment]
Verified with commit ddcbbbe. This issue is not reproducible.
