### ISSUE TITLE
AsyncGPIOPin.onchange and uart.on didn't work

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#797]
### Description

AsyncGPIOPin.onchange and uart.on didn't work

### Test Code

[ButtonLEDsAsync.js](https://github.com/01org/zephyr.js/blob/master/samples/ButtonLEDsAsync.js); [UART.js](https://github.com/01org/zephyr.js/blob/master/samples/UART.js); [test-gpio.js](https://github.com/01org/zephyr.js/blob/master/tests/test-gpio.js); [test-uart-read-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-uart-read-manual.js)
 
### Steps to Reproduction

1. `$ make JS=samples/UART.js`
2. `$ make dfu`
3. Reset device. 

### Actual Result

[ButtonLEDsAsync.js](https://github.com/01org/zephyr.js/blob/master/samples/ButtonLEDsAsync.js)
 Only one on board LED is always bright, not blinking.

[UART.js](https://github.com/01org/zephyr.js/blob/master/samples/UART.js)
![uart](https://cloud.githubusercontent.com/assets/19813546/23649995/773f7fdc-035b-11e7-99b1-e76e89d1ff7c.png)

[test-uart-read-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-uart-read-manual.js)
![test-uart-manual](https://cloud.githubusercontent.com/assets/19813546/23650018/9735e1c8-035b-11e7-9cd0-1b8bf1b91336.png)

[test-gpio.js](https://github.com/01org/zephyr.js/blob/master/tests/test-gpio.js)
Test stuck at the tenth case.
![test-gpio](https://cloud.githubusercontent.com/assets/19813546/23650004/8194129a-035b-11e7-88ed-a3b0054d4b02.png)

### Expected Result

[ButtonLEDsAsync.js](https://github.com/01org/zephyr.js/blob/master/samples/ButtonLEDsAsync.js)
Blink the two LEDs on and off together

[UART.js](https://github.com/01org/zephyr.js/blob/master/samples/UART.js) and [test-uart-read-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-uart-read-manual.js)
No error thrown

[test-gpio.js](https://github.com/01org/zephyr.js/blob/master/tests/test-gpio.js)
All test cases are executed successfully.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 76c4663 | Arduino 101 | Mar 1, 2017 | Pass
master | b29dbbc | Arduino 101 | Mar 7, 2017 | Fail

**Comment by qiaojingx** [comment]
Verified with commit eaf24e9 on Arduino101.  AsyncGPIOPin.onchange works fine. But issue of uart.on is still reproducible.

**Comment by grgustaf** [comment]
@jprestwo please look at the UART problem reported

**Comment by jprestwo** [comment]
This should be fixed on master now.

**Comment by qiaojingx** [comment]
Verified with commit a2ce873 on Arduino 101.
UART issue was also be fixed. Closed
