### ISSUE TITLE
ashell creates empty files when you make a typo

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#799]
If you type the wrong file name in a run, parse, or du command at the ashell command line, it will create an empty file. I think this is because the underlying Zephyr FS API creates on open. So instead we should be checking for existence first and giving an error if it doesn't exist.

The 'cat' command *does* check, however its File not found error is missing a newline so it doesn't print nicely, so that could be fixed too.

**Comment by grgustaf** [comment]
@jprestwo just copied you for your filesystem knowledge. I haven't looked yet, got to be an easy fix, either ashell is always opening for write or Zephyr APIs create on read?

**Comment by brianjjones** [comment]
@jprestwo I have a fix for this, so you don't need to work on it if you haven't started.  FYI.
