### ISSUE TITLE
[aio] Doesn't work with AIO module by 0.9.0 zephyr-SDK

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#801]
### Description

I update zephyr-SDK to 0.9.0 and check it. I find the latest Zephyr SDK doesn't work with AIO module. The issue is pointed to `var aio = require("aio")` .
 

### Test Code

[/test/test-aio.js](https://github.com/01org/zephyr.js/blob/master/tests/test-aio.js)
[/test/test-a101-pins.js](https://github.com/01org/zephyr.js/blob/master/tests/test-a101-pins.js)
[/samples/AIO.js](https://github.com/01org/zephyr.js/blob/master/samples/AIO.js)
[/samples/WebBluetoothDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/WebBluetoothDemo.js)
 

### Steps to Reproduction

1. Build and setup latest Zephyr SDK with https://www.zephyrproject.org/downloads.
2. Build test case with `make JS=test/test-aio.js`.
3. Flash a101 with `make dfu`.
4. Reboot a101 and watch the screen for console log.
 

### Actual Result

No console log.
 

### Expected Result

Print some console log like other test case.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | SDK | Result
---|---|---|---|---|---
master | b29dbbc | Arduino 101 | March 7, 2017 | 0.9.0 | Fail
master | b29dbbc | Arduino 101 | March 7, 2017 | 0.8.2 | Pass

 

### Additional Information

Simple test case:
```
console.log("----1----");
var aio = require("aio");
console.log("----2----");
var gpio = require("gpio");
console.log("----3----");
var pins = require("arduino101_pins");
console.log("----4----");
```
SDK 0.9.0:
![selection_002](https://cloud.githubusercontent.com/assets/22387607/23688482/d07450ac-03ef-11e7-9f5a-e863c8101bf0.png)
SDK 0.8.2:
![selection_001](https://cloud.githubusercontent.com/assets/22387607/23688490/de08cf68-03ef-11e7-9f67-90f83dd1a6e5.png)

**Comment by qiaojingx** [comment]
Verified with commit 6d7a58b. This issue is not reproducible.

**Comment by cuiyanx** [comment]
fixed and closed!
