### ISSUE TITLE
[ocf] Improve the information for resource and platform

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#808]
### Description

I test OCF module and I find the information of resource and platform is very good, but not perfect. Please complete it.
 

### Test Code

Server code:
```
var resourceInit = {
    resourcePath: "/test/OCFserver",
    resourceTypes: ["core.test"],
    interfaces: ["/oic/if/rw"],
    discoverable: true,
    observable: true,
    properties: TestProperties
}

ocf.platform = {
    manufacturerName: "TestManufacturer",
    osVersion: "16.04",
    model: "Arduino101",
    manufacturerURL: "testurl.com",
    manufacturerDate: "11-11-2011",
    platformVersion: "5.0",
    firmwareVersion: "9.0",
    supportURL: "testurl.com/support"
}
```
Client code:
```
console.log("on('platformfound'):");
console.log("    id: " + platform.id);
console.log("    Manufacturer Name: " + platform.manufacturerName);
console.log("    osVersion: " + platform.osVersion);
console.log("    model " + platform.model);
console.log("    manufacturerURL: " + platform.manufacturerURL);
console.log("    manufacturerDate: " + platform.manufacturerDate);
console.log("    platformVersion: " + platform.platformVersion);
console.log("    firmwareVersion: " + platform.firmwareVersion);
console.log("    supportURL: " + platform.supportURL);

console.log("on('retrieve'):");
console.log("    deviceId: " + resource.deviceId);
console.log("    resourcePath: " + resource.resourcePath);
console.log("    resourceTypes: " + resource.resourceTypes);
console.log("    interfaces: " + resource.interfaces);
console.log("    properties: " + resource.properties);
```

### Steps to Reproduction

1. Build OCFserver to a101.
2. Connect to a101 by BLE.
3. Build OCFclient with linux.

### Actual Result

![selection_001](https://cloud.githubusercontent.com/assets/22387607/23788387/31f79862-05b1-11e7-8070-f5ae2a5d276b.png)
![selection_002](https://cloud.githubusercontent.com/assets/22387607/23788406/3f5a3640-05b1-11e7-9793-1702d5acce2e.png)

 

### Expected Result

No undefined object.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 6b7abbd6 | Arduino 101 | March 10, 2017 | Fail

**Comment by jprestwo** [comment]
This should be fixed on master.

**Comment by cuiyanx** [comment]
@jprestwo Please let the information of device and platform to perfect.


![selection_001](https://cloud.githubusercontent.com/assets/22387607/24535711/640367de-1608-11e7-82e1-96ed30fac95c.jpg)
![selection_002](https://cloud.githubusercontent.com/assets/22387607/24535974/01a681aa-160a-11e7-9806-d73fde134eda.jpg)

**Comment by jprestwo** [comment]
@cuiyanx, should be fixed with https://github.com/01org/zephyr.js/pull/952

**Comment by qiaojingx** [comment]
Verified with commit ddcbbbe. OCFobject: dataModels is still undefined.
Build [test-ocfserver.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfserver.js) on A101, run [test-ocfclient.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfclient.js) on Linux.
Got one fail:
![linux-test-ocfclient](https://cloud.githubusercontent.com/assets/19813546/24699052/5d49bc9c-1a25-11e7-98cb-cac88fbcf07d.png)
