### ISSUE TITLE
[ashell] Include sensors to ashell build

### ISSUE THREAD

**Issue by poussa** [01org/zephyr.js#824]
Include the sensors to ashell build. Now they are left our for some reason.

Good sample to get running is: https://github.com/01org/zephyr.js/blob/master/samples/SensorBLEDemo.js

**Comment by brianjjones** [comment]
Easy change to the config file, I'll do that when I get in.

**Comment by poussa** [comment]
I though so also but mine was always missing the ARC part of the sensor code...

**Comment by brianjjones** [comment]
Ah yeah there has been a lot added to sensors so I need to update a few things to pull in the necessary modules for ashell.  I'll get that done today.

**Comment by brianjjones** [comment]
Unfortunately file system and sensor can't be used at the same time currently.  Because ashell relies on file system, there's no way to use sensor with it currently.  I'm working with the Zephyr team to figure out a solution.

**Comment by jimmy-huang** [comment]
submitted patch #827

**Comment by brianjjones** [comment]
I tested it and it works for me.  @poussa can you confirm and close if its fixed for you?

**Comment by jimmy-huang** [comment]
just a FYI, SensorDemo.js does not work, but it is a different issue so a separate bug should be filed, but all the other 3 samples like Accelerometer.js, Gyroscope.js and AmbientLight.js does work, which address this bug.

**Comment by jimmy-huang** [comment]
I think it's okay to close this, @poussa @grgustaf?

**Comment by grgustaf** [comment]
The author has abandoned this issue, let's close it. ;)
