### ISSUE TITLE
prj.conf construction is confusing and error-prone

### ISSUE THREAD

**Issue by pfalcon** [01org/zephyr.js#826]
I'm investigating https://github.com/01org/zephyr.js/issues/819 (which is mis-named by now).

My mental model of how prj.conf is generated is: prj.conf.base is merged with a board-specific fragment, then optionally with feature-specific one like ashell. That's why https://github.com/01org/zephyr.js/commit/b15bf43c0f1041436d73719eea0ba6b4390ac4cb#diff-51461e961b292b547a2fb47817be9f26 is expected to cover all boards. Alas, it's not how it works. Turns out, qemu_x86 doesn't use prj.conf.base, ashell config is actually arduino_101 specific (so I now can be sure ashell won't work on anything else), etc.

Can this be cleaned please? Just making prj.conf.base be used for everything would be a good start.

**Comment by brianjjones** [comment]
This should be addressed by https://github.com/01org/zephyr.js/pull/835 
Now .base is used by all and the other prj.conf files are for specific cases only.
