### ISSUE TITLE
Error thrown after subscribed to bmi160 sensor change

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#828]
### Description

 Error thrown after subscribed to bmi160 sensor change

### Test Code

[SensorBLEDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/SensorBLEDemo.js)
 
### Steps to Reproduction

1. `$ make JS=samples/SensorBLEDemo.js`
2. `$ make dfu`
3. Reset device and connect with 'nRF connect' app.
4. Subscribed to bmi160 sensor change by 'nRF connect' app.
5. Unsubscribed and then Subscribed again
 
### Actual Result

After 4. ringbug put errors occurred.
After 5. Fatal fault occurred.
![selection_009](https://cloud.githubusercontent.com/assets/19813546/23884207/648cb59e-08a6-11e7-99f9-7d775e40d2fd.png)
 
### Expected Result

No error thrown.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | eaf24e9| Arduino 101 | Mar 14, 2017 | Fail

**Comment by jimmy-huang** [comment]
@qiaojingx looks like it's caused by 100hz setting, can you lower both sensor to 20hz if it fixes your problem?  the latest patch #827 will revert them back as well.

**Comment by qiaojingx** [comment]
Verified with patch #827, this issue will not be reproducible.

**Comment by qiaojingx** [comment]
Verified with commit 8a2964e on Arduino 101. This issue has been fixed.
Closed
