### ISSUE TITLE
[fs] FsAsync can't start

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#829]
### Description

 FsAsync can't start

### Test Code

[FsAsync.js](https://github.com/01org/zephyr.js/blob/master/samples/FsAsync.js)
 
### Steps to Reproduction

 1. `$ make JS=samples/FsAsync.js`
 2. `$ make dfu`
 3. Reset device
### Actual Result

![fsasync_a101](https://cloud.githubusercontent.com/assets/19813546/23884428/9d3d8e76-08a7-11e7-91d5-85425cccbf54.png)
 
### Expected Result

FsAsync sample can be executed successfully.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | eaf24e9| Arduino 101 | Mar 14, 2017 | Fail
 
### Additional Information

According to [fs.md](https://github.com/01org/zephyr.js/blob/master/docs/fs.md#introduction), the asynchronous API's can be compiled in by enabling the pre-processor define ZJS_FS_ASYNC_APIS. How can we enable it and make FsAsync work?

**Comment by grgustaf** [comment]
Should be fixed by #931.

**Comment by qiaojingx** [comment]
Verified with commit 380261a on Arduino 101. This issue is not reproducible. Closed
