### ISSUE TITLE
[REG][event] Event object not found

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#850]
### Description

 Event object not found

### Test Code

[Events.js](https://github.com/01org/zephyr.js/blob/master/samples/tests/Events.js); [test-event.js](https://github.com/01org/zephyr.js/blob/master/tests/test-event.js)
 
### Steps to Reproduction

1. `make JS=samples/tests/Events.js`
2. `make dfu`
 
### Actual Result

1. On Arduino 101, FRDM-K64F and Linux: 
![event](https://cloud.githubusercontent.com/assets/19813546/24137937/044269b2-0e51-11e7-9ee9-c0a22565e192.png)

![test-event_linux](https://cloud.githubusercontent.com/assets/19813546/24183904/0747a612-0f06-11e7-9713-54483ea4a959.png)

2. There is another issue on linux: 
![event_linux](https://cloud.githubusercontent.com/assets/19813546/24137963/2a845a04-0e51-11e7-87bd-33c1160cfbe1.png)
 
### Expected Result

No error.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | eaf24e9 | Arduino 101 | Mar 14, 2017 | Pass
master | eaf24e9 | FRDM-K64F | Mar 14, 2017 | Pass
master | eaf24e9 | Linux | Mar 14, 2017 | Pass 
master | 02d9471 | Arduino 101 | Mar 21, 2017 | Fail
master | 02d9471 | FRDM-K64F | Mar 21, 2017 | Fail
master | 02d9471 | Linux | Mar 21, 2017 | Fail

**Comment by baleboy** [comment]
To be fixed before releasing 0.3 (and possibly before branching)

**Comment by jprestwo** [comment]
This should now be fixed in master.

**Comment by qiaojingx** [comment]
Verified with commit bb11854. This issue is not reproducible,
Closed
