### ISSUE TITLE
[buffer] buffer.writeUInt32BE and buffer.writeUInt32LE failed 1

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#851]
### Description

buffer.writeUInt32BE and buffer.writeUInt32LE failed 

### Test Code

[test-buffer-rw.js](https://github.com/01org/zephyr.js/blob/master/tests/test-buffer-rw.js);
 
### Steps to Reproduction

1. `make JS=tests/test-buffer-rw.js`
2. `make dfu`
 
### Actual Result

1. On Arduino 101, FRDM-K64F and Linux: 
![test-buffer-rw_linux](https://cloud.githubusercontent.com/assets/19813546/24139535/5dd49c56-0e57-11e7-8646-a36fcd86a4b3.png)

### Expected Result

No error.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | eaf24e9 | Arduino 101 | Mar 14, 2017 | Pass
master | eaf24e9 | FRDM-K64F | Mar 14, 2017 | Pass
master | eaf24e9 | Linux | Mar 14, 2017 | Pass 
master | 02d9471 | Arduino 101 | Mar 21, 2017 | Fail
master | 02d9471 | FRDM-K64F | Mar 21, 2017 | Fail
master | 02d9471 | Linux | Mar 21, 2017 | Fail

**Comment by baleboy** [comment]
To be fixed before releasing 0.3 (and possibly before branching)

**Comment by grgustaf** [comment]
Fixed by #934.

**Comment by qiaojingx** [comment]
Verified with commit a2ce873 + #934. This issue is not reproducible.
Will close it after patch merge.
