### ISSUE TITLE
[REG][ble] Can't start ble in SensorBLEDemo.js and HeartRateDemo.js using ZephyrSDK 0.8.2

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#863]
### Description

Can't start ble in SensorBLEDemo.js and HeartRateDemo.js
 
### Test Code

[SensorBLEDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/SensorBLEDemo.js); [HeartRateDemo.js](https://github.com/01org/zephyr.js/blob/master/samples/HeartRateDemo.js)

### Steps to Reproduction

1. `$ make JS=samples/SensorBLEDemo.js`
2. `make dfu`
 
### Actual Result
1. When using ZephyrSDK 0.8.2:
![sensorbledemos](https://cloud.githubusercontent.com/assets/19813546/24180721/85a8b074-0ef1-11e7-9cba-58adb9a8d383.png)
![selection_003](https://cloud.githubusercontent.com/assets/19813546/24180722/85aaa528-0ef1-11e7-95bf-f9834d207005.png)

2. When using ZephyrSDK 0.9:
![selection_005](https://cloud.githubusercontent.com/assets/19813546/24180737/9bb3c94e-0ef1-11e7-8d62-61618ae6bcf5.png)
![selection_004](https://cloud.githubusercontent.com/assets/19813546/24180738/9bb4501c-0ef1-11e7-8d3c-c257882b1f69.png)

### Expected Result

Able to start ble in SensorBLEDemo.js and HeartRateDemo.js when using ZephyrSDK 0.8.2
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result | SDK version 
---|---|---|---|---|---
master | 02d9471 | Arduino 101 | March 22, 2017 | Failed | 0.8.2
master | 02d9471 | Arduino 101 | March 22, 2017 | Pass | 0.9

**Comment by baleboy** [comment]
To be fixed before releasing 0.3 (and possibly before branching)

**Comment by grgustaf** [comment]
@jimmy-huang, is this specific to 0.8.2?

**Comment by jimmy-huang** [comment]
@grgustaf I reverted back to 0.8.2, I can't reproduce this, can you try?  Both the SensorBLEDemo.js and HeartRateDemo.js are working

ipm_console0: 'Sensor core running ZJS ARC support image'
Sensor (Accelerometer/Gyroscope) BLE Demo...
Advertising as Physical Web device
Client connected: 5a:5e:ea:44:99:2d (random)
Subscribed to bmi160 sensor change
Unsubscribed to bmi160 sensor change
Client disconnected: 5a:5e:ea:44:99:2d (random)
Client connected: 5a:5e:ea:44:99:2d (random)
Subscribed to bmi160 sensor change
Unsubscribed to bmi160 sensor change
Client disconnected: 5a:5e:ea:44:99:2d (random)

ipm_console0: 'Sensor core running ZJS ARC support image'
BLE state: poweredOn
advertisingStart: success
Measured 1st beat
Measured 1st beat
Measured 2nd beat
ipm_console0: 'Sensor core running ZJS ARC support image'

**Comment by qiaojingx** [comment]
Verified with latest commit bb11854 in master. This issue is not reproducible.
Closed
