### ISSUE TITLE
[REG][ashell] Build with ashell failed using the Zephyr SDK 0.9

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#864]
### Description

Build with ashell failed using the Zephyr SDK 0.9
 
### Test Code

[ashell.md](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md)

### Steps to Reproduction

1. `$ make DEV=ashell`
 
### Actual Result
1. ZephyrSDK 0.9:
![selection_006](https://cloud.githubusercontent.com/assets/19813546/24180925/c63b2314-0ef2-11e7-9f3a-3d985cb35c29.png)

### Expected Result

Build with ashell successfully using the Zephyr SDK 0.9
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result | SDK version 
---|---|---|---|---|---
master | 9f48297 | Arduino 101 | March 22, 2017 | Failed | 0.9
master | 9f48297 | Arduino 101 | March 22, 2017 | Pass | 0.8.2

**Comment by qiaojingx** [comment]
Verified with commit a6c321a. ashell still can't be built with Zephyr SDK 0.9.
But the error message changed:
![ashell_0 9](https://cloud.githubusercontent.com/assets/19813546/24232648/6e98b768-0fc7-11e7-9060-5dca4ac5f2da.png)

**Comment by jimmy-huang** [comment]
submitted patch #873

**Comment by qiaojingx** [comment]
Verified with commit a6c321a + Patch #873. This issue is not reproduced.
Will close after patch merged.

**Comment by baleboy** [comment]
To be fixed before releasing 0.3 (and possibly before branching)

**Comment by qiaojingx** [comment]
Verified with commit b7d9ff7 in master. This issue is not reproducible.
Closed
