### ISSUE TITLE
[reg][snapshot] Invalid snapshot format error thrown

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#870]
### Description

Invalid snapshot format error thrown

### Test Code

All [Samples](https://github.com/01org/zephyr.js/tree/master/samples) and [tests](https://github.com/01org/zephyr.js/tree/master/tests).
 
### Steps to Reproduction

Take [HelloWorld.js](https://github.com/01org/zephyr.js/blob/master/samples/HelloWorld.js) for an example.
1. `make JS=samples/HelloWorld.js `
2. `make dfu`

### Actual Result

 
![selection_003](https://cloud.githubusercontent.com/assets/19813546/24232117/b060b1f4-0fc3-11e7-9c6c-a936d93eb43f.png)

### Expected Result

 
![selection_004](https://cloud.githubusercontent.com/assets/19813546/24232150/e6269ee8-0fc3-11e7-8855-b3246318c333.png)

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 02d9471 | Arduino 101 | Mar 21, 2017 | Pass
master | a6c321a | Arduino 101 | Mar 23, 2017 | Fail
 
### Additional Information

It will work if build with command `make JS=samples/HelloWorld.js SNAPSHOT=off`

**Comment by jimmy-huang** [comment]
submitted patch #871

**Comment by qiaojingx** [comment]
Verified with commit a6c321a + Patch #871 . This issue is not reproduced.
Will close after patch merged.

**Comment by qiaojingx** [comment]
Verified with commit b7d9ff7 in master. This issue is not reproduced.
Closed
