### ISSUE TITLE
[ocf] ocf server down after running about 1 min

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#872]
### Description

ocf server down after running about 1 min

### Test Code

[OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js); 

 ### Steps to Reproduction

1. Build OCFserver to a101.
2. Connect to a101 by BLE.
3. Build OCFclient with linux.

### Actual Result

1 min later, ocfserver:
![selection_002](https://cloud.githubusercontent.com/assets/19813546/24232356/8768aae8-0fc5-11e7-8568-fe073ebcd9b2.png)

1 min later, ocfclient: 
![selection_001](https://cloud.githubusercontent.com/assets/19813546/24232364/97f9a164-0fc5-11e7-9a24-b401fdb56f3a.png)

### Expected Result

Ocfserver always works.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | a6c321a | Arduino 101 | Mar 23, 2017 | Fail

**Comment by jprestwo** [comment]
Fixed with https://github.com/01org/zephyr.js/pull/962

**Comment by qiaojingx** [comment]
Verified with commit ddcbbbe. This issue is not reproducible.
