### ISSUE TITLE
[ashell] ashell default connect to serial console instead of browser IDE

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#874]
### Description

ashell default connect to serial console instead of browser IDE

### Test Code

[ashell.md](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md)
 
### Steps to Reproduction

1. `make DEV=ashell `
2. `make dfu`
3. Reset device
### Actual Result

1. No notification from Chrome pop up.
2. ashell can be connected from terminal via `screen /dev/ttyACM0 115200`
![selection_002](https://cloud.githubusercontent.com/assets/19813546/24233099/fd6ad39c-0fca-11e7-883f-b91c748764eb.png)

### Expected Result

1. Ashell default connect to browser IDE. A notification from Chrome pop up when plug in device to PC.
![selection_003](https://cloud.githubusercontent.com/assets/19813546/24233179/76a4669c-0fcb-11e7-9fd0-eec6886d78b3.png)

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 02d9471 | Arduino 101 | Mar 21, 2017 | Pass
master | a6c321a | Arduino 101 | Mar 23, 2017 | Fail
 
### Additional Information

This issue is reproduced when using Zephyr SDK 0.8.2. Ashell building is not successful with Zephyr SDK 0.9(#864)

**Comment by qiaojingx** [comment]
Verified with commit c9991f0. Also reproduced with Zephyr SDK 0.9.

**Comment by brianjjones** [comment]
Ashell is now built using either:
make ide (builds ashell for the IDE)
make ashell (builds for the command line)

I will submit a patch that disables the old way of doing it to avoid confusion.

**Comment by grgustaf** [comment]
@brianjjones actually I'd like you to check for them passing DEV=ashell and give an error explaining the new ways. If we just do nothing, it builds a101 default.

**Comment by brianjjones** [comment]
@grgustaf While I like the idea short term, does it really make sense to add a bunch of errors to our Makefile explaining that old depreciated things are no longer valid?  Would it make more sense to make a catch-all error that throws if the user passes an arg we don't support? And then list the args we do support? I think that might be more sustainable in the long run.  If not, I can easily add the check no sweat.

**Comment by brianjjones** [comment]
I started this PR to get the ball rolling https://github.com/01org/zephyr.js/pull/894

**Comment by brianjjones** [comment]
This is now fixed, you'll get an error if you try and use DEV=ashell.

**Comment by qiaojingx** [comment]
Verified with commit 1c67773. 
`make DEV=ashell` is unusable now.
`make ashell` and `make ide` work.
Closed
