### ISSUE TITLE
[udp] callback function of receive data works abnormally

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#875]
### Description

callback function of receive data works abnormally

### Test Code

[UDPEchoServ4.js](https://github.com/01org/zephyr.js/blob/master/samples/UDPEchoServ4.js); [UDPEchoServ6.js](https://github.com/01org/zephyr.js/blob/master/samples/UDPEchoServ6.js); [test-udp4-server-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-udp4-server-manual.js); [test-udp6-server-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-udp6-server-manual.js); [test-udp4-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-udp4-server.js); [test-udp6-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-udp6-server.js);

 ### Steps to Reproduction

1. `make BOARD=qemu_x86 qemu JS=samples/UDPEchoServ4.js`

### Actual Result

UDP4:
![selection_005](https://cloud.githubusercontent.com/assets/19813546/24239297/655fb1f8-0fe8-11e7-97ce-90af6ccbfc2b.png)
![selection_001](https://cloud.githubusercontent.com/assets/19813546/24239371/a75b4356-0fe8-11e7-84d4-e0a1351e23cb.png)

UDP6:
![selection_004](https://cloud.githubusercontent.com/assets/19813546/24239296/655f3dc2-0fe8-11e7-9f9a-475baf2cea75.png)
![selection_003](https://cloud.githubusercontent.com/assets/19813546/24239419/d539b046-0fe8-11e7-9fd7-9ef1c6e657b8.png)

### Expected Result

UDPserver works well.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | a6c321a | Linux | Mar 23, 2017 | Fail

**Comment by grgustaf** [comment]
@pfalcon, maybe you could take a look at this. I did mess with dgram.c with a couple global changes recently and might have broken something. I'm afraid I didn't test every module...

**Comment by pfalcon** [comment]
I will. Sorry, I have some issues, so I am, and will be, slow for some time... :-I

**Comment by pfalcon** [comment]
Well, tried to look into this, and found that the latest net-tools master is broken for me: https://jira.zephyrproject.org/browse/ZEP-1965

**Comment by pfalcon** [comment]
Confirmed the issue, on packet reception I get:

~~~
src/zjs_util.c:379 zjs_print_error_message():
[ERROR] Uncaught exception: Error: Cannot read property 'address' of undefined
~~~

**Comment by grgustaf** [comment]
BTW I did fix one bug in dgram that was showing up in the screenshots above with PR #911. That was the "callback -40 does not exist" thing.

**Comment by qiaojingx** [comment]
Verified with commit a2ce873 on linux. This issue is not reproducible. Closed.
