### ISSUE TITLE
[ocf] Cannot set BLE-address for OCF server

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#876]
### Description

I follow the [/docs/ocf.md](https://github.com/01org/zephyr.js/blob/master/docs/ocf.md) to set BLE-address for OCF server, I am failed. I should try those:
```
ocf.setBleAddress 
server.setBleAddress
setBleAddress
```
All failed.
 

### Test Code

```
var ocf = require("ocf");
var BleAddress = "F1:E2:D3:C4:B5:A6";
ocf.setBleAddress(BleAddress);
```

 

### Actual Result

![selection_003](https://cloud.githubusercontent.com/assets/22387607/24239812/50d5047a-0fea-11e7-89e0-d81b9330b77e.png)

 

### Expected Result

Set BLE address for OCF server and no error.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result | SDK
---|---|---|---|---|---
master | a6c321a | Arduino 101 | Mar 23, 2017 | Fail | 0.9

**Comment by jprestwo** [comment]
This should now be fixed in master.

**Comment by cuiyanx** [comment]
Yes, this is fixed and closed.
