### ISSUE TITLE
Clean up snapshot.c build

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#880]
Move snapshot.c to a separate source directory since it is a Linux utility, not part of the Zephyr code in src/ and that is confusing. I suggest tools/snapshot.c.

Also, change it so it writes its output to outdir. Probably it should print its output to stdout and then the Makefile can > redirect it into a file in outdir, like most Unix utilities.

Also, consider maybe moving Makefile.snapshot to tools/Makefile.tools if that's not too difficult. That would just help clean up our root dir.

**Comment by jimmy-huang** [comment]
This is fixed by #892, so closing this issue.
