### ISSUE TITLE
[fs] Read data that existed in r file failed when first run after power on

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#886]
### Description

 Read data that existed in r file failed when first run after power on

### Test Code

[test-fs.js](https://github.com/01org/zephyr.js/blob/master/tests/test-fs.js);
 
### Steps to Reproduction

1. `make JS=tests/test-fs.js`
2. `make dfu`
3. Reset device(if not reproduced, please power off then power on device.)

### Actual Result

 Read data that existed in r file failed when first run after power on
![selection_001](https://cloud.githubusercontent.com/assets/19813546/24282482/a3554132-109a-11e7-9770-d3e0227e97f4.png)

### Expected Result

 Read data that existed in r file always successfully.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | b7d9ff7 | Arduino 101 | Mar 24, 2017 | Fail
 
### Additional Information

Only reproduced when first run after power on.

**Comment by jprestwo** [comment]
@qiaojingx, I just tested on master (c9991f0) and did not see that failure.

@grgustaf, @brianjjones, could one of you test this really quick. (just run tests/test-fs.js).

**Comment by qiaojingx** [comment]
Verified with commit bb11854 in master. Still can see this issue when first run after flash.

**Comment by qiaojingx** [comment]
Verified with commit a2ce873 on Arduino 101.
This issue is not reproducible. Closed
