### ISSUE TITLE
[ocf] Extra '\f' is added after '/a/light'

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#888]
### Description

Extra '\f' is added after '/a/light'

### Test Code

[OcfServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfServer.js); [OcfNotifyServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfNotifyServer.js); [OcfSensorServer.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfSensorServer.js);
 
### Steps to Reproduction

1. `make BOARD=arduino_101 JS=samples/OcfServer.js`
2. `make dfu`
3. Reset device
4. Connect device to PC via BLE([ocf-ble.md](https://github.com/01org/zephyr.js/blob/master/docs/ocf-ble.md))
5. Build [iot-rest-api-server](https://github.com/01org/iot-rest-api-server) as OCF Client.
6. Find resource with ./oic-get /res.

### Actual Result

![selection_003](https://cloud.githubusercontent.com/assets/19813546/24283159/1bf7b670-109f-11e7-996c-ca596709254d.png)

### Expected Result

![selection_004](https://cloud.githubusercontent.com/assets/19813546/24283162/2021c024-109f-11e7-8b44-00bead0858af.png)

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 02d9471 | Arduino 101 | Mar 21, 2017 | Pass
master | b7d9ff7 | Arduino 101 | Mar 24, 2017 | Fail

**Comment by grgustaf** [comment]
Should be fixed in #922.

**Comment by qiaojingx** [comment]
Verified with commit ddcbbbe. This issue is not reproducible.
