### ISSUE TITLE
#842 makes an incorrect change, broke dgram module, and should be reverted

### ISSUE THREAD

**Issue by pfalcon** [01org/zephyr.js#896]
As described in https://github.com/01org/zephyr.js/pull/842#issuecomment-289202305 . Well, removing "&" in front of `args` is an ok change ;-).

**Comment by grgustaf** [comment]
I haven't tested it yet, but #903 should address this, and my comment just now to #844 I think explains how this happened.

Your comment about prefering sizeof(args) where the compiler knows the size is a good one too; I made that change throughout the project (for zjs_signal_callback calls anyway).

**Comment by grgustaf** [comment]
This was fixed in PR #903.
