### ISSUE TITLE
[PnP] Zephyr_I2C_ROM(Byte) KPI for A101 has ~5% gap compared with master commit 02d9471 

### ISSUE THREAD

**Issue by hanyia** [01org/zephyr.js#900]
Test with WW13 master commit: bb11854, detail result as below table:

|Zephyr_I2C_ROM(Byte)|ww13 bb11854| ww12 02d9471 | ww13 vs ww12
----|----|------|----
| Result |117944| 111952  | 5.35%

**Comment by grgustaf** [comment]
Are you building with SDK 0.9? If so this is probably artificial because of a temporary workaround to build in debug mode. I recommended using SDK 0.8.2 until we clear that issue up. (Which might mean 0.9.1.)

Same for #901 I assume.

**Comment by hanyia** [comment]
Thank for you reminding, update the SDK to 0.9 ,the I2C ROM KPI get pass result, so close this bug.
