### ISSUE TITLE
[sensor] Please change sensor.onstatechange() to sensor.onactivate() following W3C sensor

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#914]
### Description

I found the function sensor.onstatechange() has be updated to sensor.onactivate() in W3C sensor. And we update [/docs/sensors.md](https://github.com/01org/zephyr.js/blob/master/docs/sensors.md) to sensor.onactivate(), but the samples and tests had not. So, please Add sensor.onactivate() for zephyr JS following W3C sensor.
 

### Test Code

[/modules/GenericSensor.js](https://github.com/01org/zephyr.js/blob/master/modules/GenericSensor.js)
[/samples/Gyroscope.js](https://github.com/01org/zephyr.js/blob/master/samples/Gyroscope.js)
[/samples/AmbientLight.js](https://github.com/01org/zephyr.js/blob/master/samples/AmbientLight.js)
[/samples/Accelerometer.js](https://github.com/01org/zephyr.js/blob/master/samples/Accelerometer.js)

 

### Actual Result

Function sensor.onactivate() has undefined.
 

### Expected Result

Be defined and work well.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 694cf15 | Arduino 101 | Mar 28, 2017 | Fail

**Comment by jimmy-huang** [comment]
@kenchris can you confirm that onactivate() completely replaces onstatechange()?  I thought onactivate is only for 1 state event from "activating" to "activated", what about other state transitions like from "activated" to "idle"?

**Comment by kenchris** [comment]
The states are still being changed a bit. Like currently it looks like the errored state is going away.

Please join the discussions on the generic sensor spec, issues 160

**Comment by jimmy-huang** [comment]
I am going to downgrade this to p3 as there's no immediately need to follow the spec change until it's finalized

**Comment by kenchris** [comment]
There is no event from activated to idle as it is sync apparently

**Comment by cuiyanx** [comment]
Fixed and closed
