### ISSUE TITLE
[gpio] Fatal fault when running test-k64k-pins.js

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#919]
### Description

Fatal fault when running test-k64k-pins.js
 
### Test Code

[test-k64f-pins.js](https://github.com/01org/zephyr.js/blob/master/tests/test-k64f-pins.js);
 
### Steps to Reproduction

1. `make BOARD=frdm_k64f JS=tests/test-k64f-pins.js` 
2. cp outdir/frdm_k64f/zephyr.bin /media/<USERNAME>/MBED/

### Actual Result

![selection_004](https://cloud.githubusercontent.com/assets/19813546/24392093/f959b57c-13c4-11e7-92a2-c8ca64b644f1.png)

 
### Expected Result

No error thrown

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | bb11854 | FRDM-K64F | Mar 28, 2017 | Fail

**Comment by grgustaf** [comment]
@brianjjones hoping you could take a look at this, try to track down what changed to cause the problem. There are a number of broken things in K64F right now so I need some help.

**Comment by qiaojingx** [comment]
Verified with commit f3d587d + #954. This issue is not reproducible.
Will close it after patch merged.

**Comment by grgustaf** [comment]
Wow, three bugs with one patch. :)

**Comment by qiaojingx** [comment]
Verified with commit ddcbbbe on K64F. This issue is not reproduced. Closed
