### ISSUE TITLE
[docs] Docs of ashell need to be updated

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#920]
### Description

Docs of ashell need to be updated
 
### Test Code

[ashell.md](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md)
 
### Actual Result

'Compilation' and 'Connect using serial console' are still using the old ones.

Compilation
![selection_010](https://cloud.githubusercontent.com/assets/19813546/24399303/e6d16642-13de-11e7-92aa-76cc56d05a08.png)

Connect using serial console 
![selection_011](https://cloud.githubusercontent.com/assets/19813546/24399304/e6d61598-13de-11e7-8390-76f8e6d6095a.png)

### Expected Result

This command will enable the shell compilation with:  
`make ide` (builds ashell for the IDE)
`make ashell` (builds for the command line)

### Test Builds

Branch | Commit Id | Test Date | Result
---|---|---|---
master | 9e666f4 | Mar 28, 2017 | Fail

**Comment by brianjjones** [comment]
This had been updated.

**Comment by qiaojingx** [comment]
@brianjjones , I think 'Connect using serial console' section also need to update. We don't need to `Set 'CONFIG_USB_CDC_ACM=y' in fragments/prj.conf.arduino_101_dev to enable USB CDC ACM device class driver.` now.

**Comment by brianjjones** [comment]
@qiaojingx good catch I'll change that as well

**Comment by brianjjones** [comment]
Update can be seen here https://github.com/01org/zephyr.js/pull/969

**Comment by qiaojingx** [comment]
Verified with commit f8f9621. Closed as fixed.
