### ISSUE TITLE
UDP does not work on Arduino 101

### ISSUE THREAD

**Issue by haoxli** [01org/zephyr.js#945]
# Description
UDP server does not work on Arduino 101, output with messy code, and cannot receive the message sent by terminal.

# Test Code
[UDPEchoServ4.js](https://github.com/01org/zephyr.js/blob/master/samples/UDPEchoServ4.js)
[UDPEchoServ6.js](https://github.com/01org/zephyr.js/blob/master/samples/UDPEchoServ6.js)

# Steps to Reproduction
1. `make JS=samples/UDPEchoServ4.js`
2. `make dfu`
3. In another terminal: `echo ‘hello’ | nc -u 192.0.2.1 33333`

# Actual Result
![screenshot from 2017-03-30 16-41-36](https://cloud.githubusercontent.com/assets/3271257/24495683/98c0b684-1568-11e7-9592-96f9f5cc7b1c.png)
![screenshot from 2017-03-30 16-41-50](https://cloud.githubusercontent.com/assets/3271257/24495688/9ff15c92-1568-11e7-8048-dd50490c2b8b.png)

# Expected Result
No messy code and receive ‘hello’ string.

# Test Builds
Branch | Build ID | Target Device| Date | Result
---|---|---|---|---
master | a2ce873| Arduino 101 | Mar 30, 2017 | Fail

**Comment by haoxli** [comment]
Sakari suggested this P1 issue should work in 0.3 release for A101.

**Comment by pfalcon** [comment]
Please see https://github.com/01org/zephyr.js/issues/918#issuecomment-290346299 for likely underlying cause and my ideas how to go about resolving such issues consistently.

**Comment by grgustaf** [comment]
So the 'garbage' is gone and now the problem is just network configuration like @pfalcon said. I suggested we start by just printing out the IP address on startup and then we'll learn whether it's fixed or randomized, and be able to get send a packet to the device presumably.

**Comment by jprestwo** [comment]
With my recent change UDP, the A101 should work. The key is to add a new ip route for the bt0 interface after you have connected to the A101 using the OCF BLE method:
```
ip -6 route add 2001:db8::/64 dev bt0
```

After this you can then ping `2001:db8::1` using nc:
```
echo "hello" | nc -u 2001:db8::1 33333
```
You should then see the echo back with the first character missing (i.e. "ello")

**Comment by qiaojingx** [comment]
Verified with commit ddcbbbe on arduino. UDP6 is working after taking @jprestwo 's steps.
UPD4 is still not working. 
`ip route add 192.0.2.0/24 dev bt0`
`echo "hello" | nc -u 192.0.2.1 33333 `

**Comment by jprestwo** [comment]
@qiaojingx, I would not expect IPv4 to work on the Arduino since its using 6lowpan, which is IPv6.

**Comment by haoxli** [comment]
@jprestwo thanks. So we will only check IPv6 on Arduino and close the issue as fixed.
