### ISSUE TITLE
Enable accelerometer and magnetometer sensors on K64F

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyr.js#956]
At least Accelerometer as a generic sensor; this will be a good way to prove we can work across different boards correctly. Does generic sensor API cover magnetometer yet?

**Comment by jimmy-huang** [comment]
Yeah, no magnetometer yet, but shouldn't be difficult to add

**Comment by kenchris** [comment]
Yes, the spec covers magnetometers

**Comment by qiaojingx** [comment]
Accelerometer sensor is enabled on K64F. Verified with samples([FXOS8700Accelerometer.js)](https://github.com/01org/zephyr.js/blob/master/samples/FXOS8700Accelerometer.js). Samples of magnetometer sensor are not added yet.
Commit: 8a95b21+ #1312 
Platform: FRDM-K64F

**Comment by qiaojingx** [comment]
Accelerometer and Magnetometer sensors are enabled on FRDM-K64F. Verified with samples([FXOS8700Accelerometer.js](https://github.com/01org/zephyr.js/blob/master/samples/FXOS8700Accelerometer.js) and [FXOS8700Magnetometer.js](https://github.com/01org/zephyr.js/blob/master/samples/FXOS8700Magnetometer.js)). One known issue is for Magnetometer sensor(#1327).
Commit: c2ca034
Platform: FRDM-K64F

**Comment by qiaojingx** [comment]
Accelerometer and Magnetometer sensors are enabled on FRDM-K64F. Verified with samples([FXOS8700Accelerometer.js](https://github.com/01org/zephyr.js/blob/master/samples/FXOS8700Accelerometer.js) and [FXOS8700Magnetometer.js](https://github.com/01org/zephyr.js/blob/master/samples/FXOS8700Magnetometer.js)). One known issue is for Magnetometer sensor(#1327).
Commit ID: 0334065
Platform: FRDM-K64F.
ZephyrSDK: 0.9.1
Zephyr:1.8

**Comment by jimmy-huang** [comment]
Closing this as it is implemented.
