### ISSUE TITLE
Support Generic Sensor APIs for common sensors

### ISSUE THREAD

**Issue by kenchris** [01org/zephyr.js#96]
Some sensors are quite impossible to implement using I2C, GPIO etc on top of JS and that might also not be very efficient if it was possible.

For this Zephyr has the sensor subsystem: https://www.zephyrproject.org/doc/subsystems/sensor.html

This works with the very common DTH22 sensor for instance: https://www.adafruit.com/product/385

Sensors are relative easy to use in Zephyr (Might require to run on ARC, that is the only thing that I tested):

```
struct device *dev = device_get_binding("DHT");
while (1) {
        struct sensor_value temp, press, humidity;

        sensor_sample_fetch(dev);
        sensor_channel_get(dev, SENSOR_CHAN_TEMP, &temp);
        sensor_channel_get(dev, SENSOR_CHAN_HUMIDITY, &humidity);

        SYS_LOG_INF("temp: %d.%06d; "
                "humidity: %d.%06d",
                temp.val1, temp.val2,
                humidity.val1, humidity.val2);

        task_sleep(sys_clock_ticks_per_sec/5);
    }
}
```

Unfortunately, a few changes might be required to Zephyr in order to set the pin from JS, as it is currently set by a build config `CONFIG_DHT_GPIO_PIN_NUM`

Here are a few of our W3C proposals for temperature and humidity sensors.

https://github.com/otcshare/thermometer/blob/gh-pages/index.html
https://github.com/otcshare/hygrometer/blob/gh-pages/index.html

These build upon: https://www.w3.org/TR/generic-sensor/#idl-index

(It is planned that the spec will align so that it will work on node.js, so I would say that it is fine replacing the EventTarget - ie `onchange`, `onerror` with an `on("change")` and `on("error")` event, at least until that gets settled)

Example code:

```
var sensor = new TemperatureSensor();
sensor.start();

sensor.onchange = function(event) {
    console.log(event.reading.celsius);
}

sensor.onerror = function(event) {
    console.log(event.error.name, event.error.message);
};
```

We could add the pin and sensor name as arguments to `TemperatureSensor`, ie 

```
var sensor = new TemperatureSensor({ name: "DHT", pin: pins.A1 })
```

**Comment by grgustaf** [comment]
Closing because the basic API is there and the A101 built-in sensors are supported. Other issues have been opened for the DHT22 specifically.
