### ISSUE TITLE
zjs_buffer_create: unable to allocate buffer error in Web Bluetooth Demo

### ISSUE THREAD

**Issue by kenchris** [01org/zephyr.js#97]
Once in a while I get `zjs_buffer_create: unable to allocate buffer` error in the WebBluetoothDemo.js and it usually recovers quickly. Unfortunately it makes the web app no longer receive temperature changes before a hard reload.

**Comment by grgustaf** [comment]
@kenchris this is pretty ancient, are you still seeing this?

**Comment by jprestwo** [comment]
@kenchris, if you are still seeing this on master, then the Kernel Upgrade may not be causing the issue. We are seeing very similar errors on that PR. I am curious if it happens on master too.

**Comment by grgustaf** [comment]
Closing because I don't think we've seen this as reported for ages.
