### ISSUE TITLE
[grovelcd] Grovelcd does not work on K64

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyr.js#977]
### Description

Grovelcd does not work on K64, no console log.
 

### Test Code

[/samples/I2C.js](https://github.com/01org/zephyr.js/blob/master/samples/I2C.js)
[/samples/GroveLCD.js](https://github.com/01org/zephyr.js/blob/master/samples/GroveLCD.js)
[/tests/test-i2c.js](https://github.com/01org/zephyr.js/blob/master/tests/test-i2c.js)
[/tests/test-grovelcd.js](https://github.com/01org/zephyr.js/blob/master/tests/test-grovelcd.js)
[/tests/test-grovelcd-rgb-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-grovelcd-rgb-manual.js)
[/tests/test-grovelcd-ds-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-grovelcd-ds-manual.js)
[/tests/test-grovelcd-cursor-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-grovelcd-cursor-manual.js)

 

### Actual Result

Does not work and no console log.
 

### Expected Result

Work well.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | ddcbbb| K64 | April 6, 2017 | Fail

 

### Additional Information

[/tests/test-i2c.js](https://github.com/01org/zephyr.js/blob/master/tests/test-i2c.js):
![selection_003](https://cloud.githubusercontent.com/assets/22387607/24741107/24d085b4-1ad7-11e7-859a-8577a136ec1a.jpg)

[/samples/I2C.js](https://github.com/01org/zephyr.js/blob/master/samples/I2C.js):
![selection_004](https://cloud.githubusercontent.com/assets/22387607/24741146/589274f2-1ad7-11e7-9189-cb3cf2409b2a.jpg)

**Comment by qiaojingx** [comment]
This issue is probably caused by #954.
commit 9e12add failed
commit ed04317 pass

**Comment by grgustaf** [comment]
Yeah, that makes sense. We probably need to identify whether I2C is being used and if so, not pinmux those pins to GPIO.

**Comment by qiaojingx** [comment]
Verified with commit f8f9621 on k64f. This issue is not reproducible.

**Comment by cuiyanx** [comment]
Fixed and closed
