### ISSUE TITLE
[udp] Can't receive message on FRDM-K64F

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyr.js#978]
### Description

 cannot receive the message sent by terminal.

### Test Code

[UDPEchoServ4.js](https://github.com/01org/zephyr.js/blob/master/samples/UDPEchoServ4.js);[UDPEchoServ6.js](https://github.com/01org/zephyr.js/blob/master/samples/UDPEchoServ6.js)
 
### Steps to Reproduction

1. `make BOARD=frdm_k64f JS=samples/UDPEchoServ4.js`
2. cp outdir/frdm_k64f/zephyr.bin /media/<USERNAME>/MBED/
3. In another terminal: `echo ‘hello’ | nc -u 192.0.2.1 33333`

### Actual Result

 No message is received.

### Expected Result

receive ‘hello’ string.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | ddcbbbe | FRDM-K64F | Apr 6, 2017 | Fail

**Comment by grgustaf** [comment]
I believe @jprestwo said this is addressed by #980.

**Comment by qiaojingx** [comment]
Verified with commit f8f9621 on K64f. Message can be received when running UDPEchoServ4.js.
Will verify UDPEchoServ6.js later because of my router problem.

**Comment by qiaojingx** [comment]
Verified with commit cc2311a on K64F. Message can be received when running UDPEchoServ4.js and UDPEchoServ6.js. Closed.
