### ISSUE TITLE
Change makefile to support  two copies of jerryscript for with/without parser

### ISSUE THREAD

**Issue by jimmy-huang** [01org/zephyr.js#983]
Currently the jerryscript is rebuilt everytime you switch back and forth between builds that uses snapshot or not to enable/disable parser, but it would be much better to have two copies of it so we don't run into issues where it doesn't get rebuilt correctly and also much faster to rebuild.

**Comment by grgustaf** [comment]
Implemented in #986.

**Comment by jimmy-huang** [comment]
this is fixed
