### ISSUE TITLE
BLE needs to support multiple client connections

### ISSUE THREAD

**Issue by jimmy-huang** [01org/zephyr.js#984]
Currently it only allows one client to connect to it, and once the first client connects, the second client won't be able to connect.

**Comment by qiaojingx** [comment]
Multiple BLE connections is supported. Verified with samples([BLE.js](https://github.com/01org/zephyr.js/blob/master/samples/BLE.js)) and tests([test-ble.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ble.js)). It can accept 4 connections at the same time.
Commit: 8a95b21
Platform: Arduino 101.
