### ISSUE TITLE
Running samples/I2C.js crashes on FRDM-K64F

### ISSUE THREAD

**Issue by jimmy-huang** [01org/zephyr.js#988]
I2C sample...
***** BUS FAULT *****
  Executing thread ID (thread): 0x20004f4c
  Faulting instruction address:  0x10dba
  Imprecise data bus error
Fatal fault in essential thread! Spinning...

**Comment by grgustaf** [comment]
Fixed by #989

**Comment by qiaojingx** [comment]
Verified with commit f8f9621 on k64f. This issue is not reproducible.
